project:
  type: book
  output-dir: _book

book:
  title: "Integrated Science Plan for Offshore Wind, Wildlife, and Habitat in U.S. Atlantic Waters"
  reader-mode: true

  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: logo7.png
  favicon: logo7.png
  site-url: https://rwsc.org/science-plan
  repo-url: https://rwscollab.github.io/science-plan/
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - executive-summary.qmd
    - intro.qmd
    - data-gov-mgmt.qmd
    - marine-mammals.qmd
    - birds.qmd
    - bats.qmd
    - sea-turtles.qmd
    - protected-fish.qmd
    - oceanography.qmd
    - seafloor.qmd
    - technology.qmd
    - review.qmd

    - part: appendices.qmd
      chapters:
        - rosters.qmd
        - append-dgdm.qmd
        - append-mm.qmd
        - append-birds.qmd
        - append-bats.qmd
        - append-st.qmd
        - append-heo.qmd
        - append-hes.qmd

format:
  html:
    theme:
      - cosmo
    code-link: true

    author-meta: "Regional Wildlife Science Collaborative for Offshore Wind"
    include-in-header: "plausible.html"
    callout-appearance: simple

editor: visual

