project:
  type: book
  output-dir: _book

book:
  title: "Integrated Science Plan for Offshore Wind, Wildlife, and Habitat in U.S. Atlantic Waters"
  original-date: "25 January 2024"
  version: "1.0"
  navbar:
    search: true
    logo: "RWSC_Logo_notext.png"
  page-navigation: true
  page-footer:
    left: "&copy; CC-By-NC-ND RWSC Steering Committee, 2024"
    right: <img src="RWSC_Logo.png" width="125">
  search:
    location: sidebar
    type: textbox
    copy-button: true
  sidebar:
    title: RWSC Science Plan
    logo: "logo7.png"
    pinned: true
    align: "center"
    #tools:
    #  - icon: globe
    #    href: https://rwsc.org
    #   text: "rwsc.org"
    #  - icon: github
    #    href: https://github.com/RWSCollab/science-plan
    #    text: "github"
  cover-image: RWSC_Logo.png
  favicon: logo7.png
  site-url: https://rwsc.org/science-plan
  repo-url: https://github.com/RWSCollab/science-plan
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  google-analytics: G-XS4FSZ7PSE
  chapters:
    - index.qmd
    - executive-summary.qmd
    - text: "---"
    - part: "Chapters"
      chapters:
        - intro.qmd
        - data-gov-mgmt.qmd
        - marine-mammals.qmd
        - birds.qmd
        - bats.qmd
        - sea-turtles.qmd
        - protected-fish.qmd
        - oceanography.qmd
        - seafloor.qmd
        - technology.qmd
        - review.qmd
    - text: "---"
  appendices:
    - append-acronyms.qmd
    - append-rosters.qmd
    - append-intro.qmd
    - append-dgdm.qmd
    - append-mm.qmd
    - append-birds.qmd
    - append-bats.qmd
    - append-st.qmd
    - append-pf.qmd
    - append-heo.qmd
    - append-hes.qmd
    - references.qmd

bibliography: references.bib
csl: elsevier-harvard

citation:
  type: article-journal
  container-title: "Regional Wildlife Science Collaborative for Offshore Wind (RWSC)"
  url: "https://rwsc.org"

crossref:
  appendix-title: "Appendix"
  appendix-delim: ":"
  chapters: true

format:
  html:
    theme:
      - cosmo
      - rwsc.scss
    code-link: true
    template-partials: [toc.html]
    toc-title: "On this page"
    author-meta: "Regional Wildlife Science Collaborative for Offshore Wind"
    callout-appearance: simple
    link-external-newwindow: true

editor: visual
