---
bibliography: references.bib
---

# Birds {#sec-append-birds}

## Introduction

This chapter of the RWSC Science Plan addresses bird research and associated scientific needs in the context of offshore wind development.
The plan is intended to reflect the research and data collection needs of RWSC's four Sectors with input from the science community.
The plan will provide a path forward to ensure appropriate data collection protocols and standards are in place to support scientific research; this document can also provide a framework that can aid RWSC participants in coordinating and aligning funding to carry out necessary scientific activities.

This plan benefits greatly from the contributions of RWSC Bird & Bat Subcommittee members; researchers, managers, and other practitioners who joined Subcommittee calls; and the many scientists who conducted research or developed reference materials referenced throughout this plan.

Following this introduction, the first section of the chapter discusses the species of birds which occur within the RWSC Study Area.
The species section is followed by a brief section summarizing primary sources of information about species' distributions.
The next section of this chapter discusses potential effects (negative or positive) of offshore wind development on bird species.
The following section summarizes common field research methods for the study of birds, with a focus on the offshore environment.
The subsequent section addresses the major research topics relevant to birds in the context of offshore wind development. 
The remainder of the chapter addresses recommended science actions of value to the four sectors that make up RWSC (state and federal agencies, eNGOs, and the offshore wind industry), in the context of recent, ongoing, and pending scientific activities relevant to recommended actions.

## Species

This chapter addresses bird species (Class Aves) which could be at risk from offshore wind development occurring in the Northwest Atlantic within U.S. waters. 
For the purposes of this plan, the geographic area of interest comprises the Atlantic Coast of the United States, extending from Maine's northern border with Canada south to the Florida Keys, and from coastal areas extending 200 nm east into the ocean, including state waters (3 nm from shore) and federal waters of the Outer Continental Shelf (3-200 nm).
This area is referred to in this plan as the RWSC Study Area. 

Hundreds of bird species occur within this area. 
At least 416 native species are regularly found in the 14 coastal states of the U.S.
Atlantic Coast, based on state [eBird](https://ebird.org/home) lists, U.S.
Atlantic Coast ranges in [*Birds of the World*](https://birdsoftheworld.org/bow/home), and [Information for Planning and Consultation (IPaC)](https://ipac.ecosphere.fws.gov/) identifications of birds using North Atlantic offshore areas. 
Many of these bird species inhabit the RWSC Study Area throughout the year. 
Others may occur in this area exclusively during the breeding or nonbreeding season, or utilize the Atlantic Flyway for migratory movements between Canada and the Caribbean, Central America, and South America (see [@afsi2015; @newton2007; @usfws2023]).

A number of these species can be expected to experience impacts from offshore wind development, including collision fatalities, displacement, attraction, barrier effects associated with avoidance, and effects on abiotic habitat features and prey populations (see [@seer2022a]); indirect effects of offshore wind energy development, like climate change mitigation, can also be expected.
While the focus of this plan is on offshore impacts of offshore wind development, potential onshore impacts of offshore wind on bird species are also possible.
For example, excavation efforts where transmission cables are coming ashore from offshore facilities could affect beach-nesting birds. 
Therefore, bird species which primarily or solely occur in the onshore environment along the U.S.
Atlantic Coast are also included within the scope of this plan, although they are not the focus of the bulk of this chapter.

All 416 species that occur in the RWSC Study Area are included in [RWSC's Bird List,](https://rwscorg.sharepoint.com/:x:/s/BirdandBatSubcommittee/ERAsPuFonjdGoLxtIeiMYdYBxV7d1avTZ7JmZvvGkAx0Kw?e=Ojl88d) a spreadsheet intended to be updated regularly to provide a complete listing of and basic information about the current regulatory and conservation status of relevant bird species, as well as characteristics relevant to exposure and vulnerability to offshore wind impacts.
Vagrants, rare visitors to U.S.
Atlantic waters, and non-native species are not included in the list. 

For additional summary information about the types of birds that occur in the RWSC Study Area, see RWSC's *Bird Descriptions by Category* \[forthcoming in 2024\].
Bird "categories" are loosely based on taxonomy, but also incorporate considerations relevant to offshore wind.
This resource provides basic information about categories of birds and their life histories as relevant to their exposure and potential vulnerability to offshore wind development. 
These sections also address other conservation threats facing these species, which could be of interest in investigating potential impacts of offshore wind or offsetting its effects. 
Species at particular risk from offshore wind development due to their life histories or conservation status are highlighted. 

Within this plan, some science recommendations are discussed within the context of five subregions of the RWSC Study Area: the Gulf of Maine, Southern New England, New York/New Jersey Bight, U.S. Central Atlantic, and U.S.
Southeast Atlantic (see @sec-intro). 
Avian assemblages and ecology may vary considerably over this geographic area.
The Gulf of Maine subregion, located at the northern edge of the Study Area, with deeper water depths and a complex coastal topography (many islands, peninsulas, and inlets), includes a suite of species adapted to colder waters and more northern climes.
Several alcid species breed along the Maine coast but are not found breeding in other states; colonies of breeding Arctic Terns and Black Terns, likewise, are only found in Maine.
At the opposite end of the Study Area, many birds of more tropical regions, like whistling-ducks, Limpkins, and American Flamingos, are only found in Florida.

### Regulatory Status

Many bird species are protected via federal regulations. 
Important and relevant federal laws include the following:

[**Endangered Species Act (ESA).**](https://www.fws.gov/law/endangered-species-act)Currently 16 bird species that regularly occur in the RWSC Study Area are listed as Threatened or Endangered under the federal ESA (see [RWSC Bird List](https://rwscorg.sharepoint.com/:x:/s/BirdandBatSubcommittee/ERAsPuFonjdGoLxtIeiMYdYBxV7d1avTZ7JmZvvGkAx0Kw?e=Ojl88d)), including two shorebird species (the Piping Plover, Red Knot) and three seabirds (Roseate Tern, Bermuda Petrel, Band-rumped Storm-petrel). 
In addition, the [Black-capped Petrel](https://ecos.fws.gov/ecp/species/4748) has been proposed for listing as Threatened [@usfws2023a].
The ESA places strict limits on the import, export, sale, possession, transportation, or "take" of listed species, with "take" defined as "to harass, harm, pursue, hunt, shoot, wound, kill, trap, capture, or collect, or to attempt to engage in any such conduct." The ESA also allows for the designation of critical habitat for a species and prohibits the destruction of that habitat.

[**Migratory Bird Treaty Act (MBTA).**](https://www.fws.gov/law/migratory-bird-treaty-act-1918) Nearly all the birds that occur in the RWSC Study Area are afforded protection under the MBTA (see [RWSC Bird List](https://rwscorg.sharepoint.com/:x:/s/BirdandBatSubcommittee/ERAsPuFonjdGoLxtIeiMYdYBxV7d1avTZ7JmZvvGkAx0Kw?e=Ojl88d)).
The MBTA was enacted in 1918 to implement four international conservation treaties that the U.S. entered into with Canada, Mexico, Japan, and Russia (several of which were amended in more recent years).
The MBTA covers over 1,000 bird species and is intended to ensure the sustainability of their populations.
The MBTA prohibits the take (including killing, capturing, selling, trading, and transport) of protected migratory bird species without prior authorization by the USFWS.
Of greatest relevance to offshore wind development is the prohibition of incidental take, that is the taking or killing of migratory birds that results from, but is not the purpose of, a lawful activity [@usfws2021].
The USFWS prioritizes for enforcement incidental take that results from activities by a public- or private-sector entity that are otherwise legal and foreseeable, and occurs where known general or activity-specific beneficial practices were not implemented [@usfws2021].
The USFWS is currently in a rulemaking process as the Service considers developing proposed regulations to authorize the incidental take of migratory birds [@usfws2023a].

[**Bald and Golden Eagle Protection Act (BGEPA).**](https://www.fws.gov/law/bald-and-golden-eagle-protection-act)The BGEPA is more limited in scope than the two proceeding regulations.
It protects Bald and Golden Eagles, both of which occur in the RWSC Study Area, prohibiting take of individuals, as well as their parts (e.g., feathers), nests, or eggs.
The Act defines "take" as "pursue, shoot, shoot at, poison, wound, kill, capture, trap, collect, molest or disturb." Regulations further define "disturb" as "to agitate or bother a bald or golden eagle to a degree that causes, or is likely to cause, based on the best scientific information available, 1) injury to an eagle, 2) a decrease in its productivity, by substantially interfering with normal breeding, feeding, or sheltering behavior, or 3) nest abandonment, by substantially interfering with normal breeding, feeding, or sheltering behavior" (50 CFR 22.6).

In addition to federal regulations, most states maintain a list of rare species which are afforded special protections under a state-level Endangered Species Act or other state statute.
Over 150 bird species are protected by these state laws in the 14 states of the RWSC Study Area.
Individual State Wildlife Action Plans also identify Species of Greatest Conservation Need (SGCN) which serve as foci for research and conservation efforts.
At least two-thirds of U.S.
Atlantic Coast birds are listed as SGCN in one or more states (see [RWSC Bird List](https://rwscorg.sharepoint.com/:x:/s/BirdandBatSubcommittee/ERAsPuFonjdGoLxtIeiMYdYBxV7d1avTZ7JmZvvGkAx0Kw?e=Ojl88d)).

### Defining Focal Species

While some scientific research methods will provide information about a variety of taxa (e.g., aerial surveys), other research methods (e.g., tagging) must by nature be species-specific.
Since over 400 bird species occur regularly or occasionally in the 14 states of the U.S.
Atlantic Coast, it is not practicable to study all these species using species-specific methods.
For certain purposes, therefore, there is a need to identify birds which should serve as focal species for species-specific field research studies and other scientific activities.

In developing a framework to guide identification of focal species for these types of studies, the RWSC Bird & Bat Subcommittee began with criteria identified in a NYSERDA Stakeholder Workshop [@gulka2020].
Through Subcommittee discussions, the list of criteria was slightly expanded to read as follows.
Focal species could include:

-   **Threatened and endangered species** (federal and/or state-listed)

-   **Species otherwise designated as of conservation concern** (e.g., Species of Greatest Conservation Need \[SGCN\] in State Wildlife Action Plans, regional SGCN \[[Northeast](https://northeastwildlifediversity.org/rsgcn) and [Southeast](https://www.nwf.org/Our-Work/Wildlife-Conservation/southeast-regional-priority-species)\], state-listed "special concern" species, or proposed/candidate endangered species)

-   **Other federally regulated species** (i.e., species protected under MBTA or BGEPA)

-   **Surrogates for rare species**, which may be the best available proxy to study and understand rare species' movements, behaviors, or expected effects of offshore wind development.
    (The Subcommittee recognizes that there are not perfect surrogates for the rare species themselves, but for some rare species, using a surrogate may be the best available option.)

-   **Species or taxa known or suspected of being sensitive to impacts from offshore wind development** due to existing information and/or aspects of their life history which might render them susceptible to offshore wind.
    (Existing information could come from pilot studies in North America, or from longer-term studies in Europe, where more research has been conducted to date. Life history aspects that inform risk could include foraging strategy, flight height distributions, sensitivity to other anthropogenic disturbances, or overlap between areas of high densities for a species and Wind Energy Areas).
    Focusing on species for which significant impacts are anticipated can increase the likelihood of having the power to detect change in a given study or studies [@nyserdaetwg].

-   Within a taxon or guild anticipated to be sensitive to offshore wind, **species with high levels of existing baseline data**, and whose population parameters (e.g., productivity, survival) can more easily be measured.

-   **Species or taxa for which very little is known about potential impacts**, because there has not yet been significant offshore development in their habitats (e.g., pelicans).

As noted previously, at least two-thirds of bird species that occur in the RWSC Study Area are listed as Species of Greatest Conservation Need in one or more states.
This categorization therefore is not particularly helpful in developing a limited list of species for consideration as focal species.
In addition, the category of "other federally regulated species" includes species protected under the Migratory Bird Treaty Act.
The regulation covers nearly all bird species in the RWSC Study Area, with the exception of some species in the Orders Gruiformes and Galliformes. 
This protection is important from a regulatory and conservation standpoint, but it is not helpful in developing a priority list of focal species.

Geography is important to consider when identifying focal species. 
Species distributions, abundance, and seasons of occurrence vary broadly across the five subregions of the RWSC Study Area.
These differences are important to consider when identifying focal species for species-specific studies within a given subregion.
If a particular marine bird or shorebird, for example, only breeds within one or two subregions, these areas will naturally be the focus for breeding season studies.
In addition, it may be important to focus studies in certain subregions where a species of interest is most common and abundant, so as to obtain a sufficient sample size The state listing status of a species and associated level of conservation concern may also vary by state and is important to factor into decision-making.

This Science Plan recommends that the RWSC Bird & Bat Subcommittee develop and maintain a shared bird exposure/risk vulnerability matrix to aid in the periodic prioritization of focal species by geography, lease area, and research topic (see Section 6).

### Regional Coastal and Offshore Distribution Information

This section addresses sources of mapped bird distributions in coastal and offshore environments which span the entire RWSC Study Area region.
The resources detailed below have been developed based on data drawn from many smaller-scale studies and incorporated into larger databases or (in the case of defining critical habitat) collated as part of regulatory review.

In addition to these sources, many individual organizations and researchers collect and analyze bird distribution data relevant to one or more species for use at a local, state, or subregional scale.
For example, many states survey nesting birds (including shorebirds and marine birds) and some, like New York, maintain a [Breeding Bird Atlas](https://www.dec.ny.gov/animals/7312.html). 
The USGS and Environment Canada maintain data from the North American [Breeding Bird Survey](https://www.pwrc.usgs.gov/bbs/) (BBS), covering the continental U.S. and Canada.
Some of this information is also captured in National Audubon efforts, including the [Christmas Bird Count](https://www.audubon.org/conservation/science/christmas-bird-count) and [Important Bird Areas](https://gis.audubon.org/portal/apps/sites/?_gl=1*1ghr9zs*_ga*MTg2ODM4MzY2NS4xNjk4Njc5Njgz*_ga_X2XNL2MWTT*MTY5ODc3NTExNS4yLjEuMTY5ODc3NTExNi41OS4wLjA.#/nas-hub-site). 

A compilation of all of these individual sources of bird distribution data is outside the scope of this Science Plan. 
However, this plan includes recommendations to include all newly collected survey and tracking data in regional databases, as well as recommendations for further compilation of historic data into these databases (see Section 6).

#### Marine Bird Distribution Maps

One of the most comprehensive analyses of marine bird distributions in the RWSC Study Area was conducted by Winship et al. [@winship2018].
Over 30 years of survey data contained in the Northwest Atlantic Seabird Catalog database, along with Eastern Canada Seabirds at Sea data from Canadian Wildlife Service, were analyzed using spatial predictive modeling to derive seasonal maps of the spatial distributions of 47 marine bird species in U.S.
Atlantic Outer Continental Shelf and adjacent waters from Florida to Maine.
Model predictions are presented as seasonal maps of the relative density of each study species, indicating where they are anticipated to be more or less abundant. 
The analysis was designed to provide relative density, and does not purport to estimate the actual number of individuals/density of a given species that would be expected in any specific location.
The maps were reviewed by experts with experience and knowledge of marine birds in the study area and their comments were incorporated into the accompanying report.

Through funding from BOEM, these maps were updated by NCCOS between 2020-2023 [@*\*review].
As an additional component of this project, predicted changes in oceanographic conditions were used to project changes in distribution of several marine bird species in the context of climate change.

#### eBird Maps

eBird is a project of the Cornell Lab of Ornithology and collaborators which collects and analyzes information about bird sightings by expert and citizen scientists in terrestrial and marine environments.
Birders enter when, where, and how they went birding, and then fill out a checklist of all the birds seen and heard.
In some cases, data submitters may be following specific protocols, such as that of the [International Shorebird Survey](https://www.manomet.org/project/international-shorebird-survey/). 
The eBird Science team uses statistical models and machine learning to analyze patterns of abundance, distribution, and migratory movements.
Raw [eBird data](https://science.ebird.org/en) are combined with high-resolution satellite imagery from NASA, NOAA, and USGS to estimate population trends and to predict distribution and abundance of bird species for every week of the year.

Because these data are often collected based on incidental observations and include limited offshore data, the marine bird distribution maps described above are considered of greater value for the marine birds included in that analysis than eBird maps.
eBird data are nevertheless valuable for species not modeled in the maps described above.
Additionally, they can provide valuable information about coastal distributions of marine birds, shorebirds, and other species.

#### Tracking Data

[Motus](https://motus.org/) and [Movebank](https://www.movebank.org/cms/movebank-main) are two databases that house data collected from automated VHF tagging/tracking and other types of tagging/tracking respectively.
These databases provide centralized locations for viewing tracking data from multiple studies, although summary products are fairly simplistic and comprehensive analyses of bird distributions are not available through these sites.
They are described in more detail in [Recommended Database Summaries](https://rwscorg.sharepoint.com/:w:/s/BirdandBatSubcommittee/EYdNwelv5IBHp6_EQPGFGPQBnsqkagkaHGNpaXUDnqfYRQ?e=wK1CV9).

#### Identified Critical Habitat

For bird species listed as Threatened or Endangered under the federal Endangered Species Act, the USFWS is required to determine whether there are identifiable areas that meet the definition of "critical habitat" [@usfws2003].
Critical habitat is defined as:

-   Specific areas within the geographical area occupied by the species at the time of listing that contain physical or biological features essential to conservation of the species and that may require special management considerations or protection; and

-   Specific areas outside the geographical area occupied by the species if the agency determines that the area itself is essential for conservation.

There are 16 bird species occurring along the U.S.
Atlantic that are identified as Threatened or Endangered across some or all of their range.
In addition, the Black-capped Petrel has been proposed for listing as Threatened.
Of these species, most either do not have critical habitat defined, or identified habitats do not occur in coastal areas.
Defined critical terrestrial habitats could be relevant to where cables come ashore to connect to grid infrastructure, but are not broadly relevant to offshore wind infrastructure development.
Critical habitat for the five listed and one proposed shorebird and marine bird species that occur along the Atlantic Coast is summarized below:

-   The Atlantic Coast breeding population of [**Piping Plovers**](https://ecos.fws.gov/ecp/species/6039) is considered Threatened.
    Critical habitat for the wintering population of Piping Plovers along the U.S.
    Atlantic Coast was designated in 2001 and updated in 2008 (see[@usfws2008]).

-   A new definition of critical habitat for the Threatened [**Red Knot**](https://ecos.fws.gov/ecp/species/1864) was proposed in April 2023. 
    The proposed revised definition includes coastal areas of Massachusetts, New York, New Jersey, Delaware, Virginia, North Carolina, South Carolina, Georgia, and Florida, which are described in detail [here](https://www.govinfo.gov/content/pkg/FR-2023-04-13/pdf/2023-06619.pdf).

-   The northeastern breeding population of the [**Roseate Tern**](https://www.fws.gov/species/roseate-tern-sterna-dougallii-dougallii) is considered Endangered; it occurs through much of the RWSC Study Area, from Maine south to South Carolina (breeding Maine to New York).
    The [Caribbean breeding population](https://ecos.fws.gov/ecp/species/B07O), which is considered Threatened, occurs north into the Florida Keys.
    No critical habitat has been defined for this species.

-   No critical habitat has been defined for the [Bermuda Petrel](https://ecos.fws.gov/ecp/species/3507) or [Band-rumped Storm-Petrel](https://ecos.fws.gov/ecp/species/1226), both of which nest outside of the RWSC Study Area.

-   The [Black-capped Petrel](https://ecos.fws.gov/ecp/species/4748) has been proposed for Threatened status.
    No critical habitat has been defined for this species.

## Potential Effects of Offshore Wind on Birds

Offshore wind development and operations could have positive, negative and/or mixed impacts on birds.
Many of the hypotheses about how offshore wind development will affect North American bird species are drawn from research in Europe, where offshore wind facilities have been in place and under study for longer time periods.
For a recent review of European avian offshore wind studies through 2019, see Fox and Petersen [@fox2019].
For a brief summary of anticipated impacts to North American birds, see *Bird and Bat Interactions with Offshore Wind Farms* [@nrel2022].
This section briefly summarizes the range of potential effects of offshore wind development on birds.
For an up-to-date list of recently published literature on this subject, search the [Tethys Knowledge Base](https://tethys.pnnl.gov/knowledge-base).

Offshore wind farms could affect birds through a variety of mechanisms.
Injuries or fatalities could occur directly through collisions with infrastructure, such as offshore wind turbine blades, towers, meteorological stations, electrical service platforms, or other facility infrastructure [@johnston2014], or via collisions with boats accessing offshore facilities as part of construction and operations activities.

Birds could also be affected in less direct ways through changes in the local environment caused by the presence of offshore wind facilities.
These impacts could occur via many mechanisms, including the physical presence of turbine infrastructure, increased lighting, changes in sound (including infrasound), changes in pressure, changes to local electromagnetic fields, effects on prey species, or effects on how humans use the area of the wind facility. 
These changes in the local environment could lead birds to be attracted to or avoid offshore wind facility infrastructure at the macro-, meso-, or micro-scale [@dierschke2016].
For example, phototaxis, the attraction of birds to lit structures [@adams2021], could attract birds to lighted offshore wind infrastructure or boats, increasing collision risk as well as changing movement patterns and distributions.
Increased sound and infrasound could affect the hearing abilities of birds both above and below the water's surface, with potential impacts on foraging, navigation, intraspecies communication, or predator avoidance [@andersonhansen2020; @mooney2019; @patrick2021].
Increased vessel traffic could increase anthropogenic disturbances of some bird species [@burger2019; @schwemmer2011].

Macro- and meso-scale avoidance of offshore wind turbines could lead to habitat loss or degradation.
Habitat displacement effects caused by offshore wind facilities have been observed in a variety of bird taxa, [\@dierschke2016](also%20see%20%5BAppendix%20C%5D(https://www.nyetwg.com/_files/ugd/78f0c4_e1ecb121e1c644c481ce2accfea6530f.pdf)%20of%20the%20Avian%20Displacement%20Guidance%20Committee's%20draft%20survey%20guidelines%20for%20a%20recent%20literature%20review).
Habitat degradation could occur if birds are less comfortable foraging within a wind facility, foraging efficiency is lower near turbine infrastructure, and/or the presence of the turbines cause stress levels to be higher, reducing birds' physiological condition.
Habitat connectivity could also be reduced via avoidance, although connectivity impacts are more likely to be a concern when considered cumulatively at the scale of multiple wind facilities [@masden2009].
Meanwhile, some species, such as cormorants, show attraction to turbine structures [@dierschke2016].
Certain bird species may therefore benefit from increased roosting and foraging opportunities around turbines -- although offshore wind facilities could also serve as ecological traps if attraction increases collision risk.

Offshore wind facilities may alter inter-species interactions in ways that benefit or negatively impact birds.
For example, the artificial reef effect might alter fish distributions, affect local fish populations, concentrate forage fish around turbine foundations, or otherwise alter the ecology of prey species [@degraer2020].
Changes in the distribution patterns or abundance of forage fish could increase or decrease the forage quality of certain habitats, bring one bird species into greater proximity to a competitor for the same food sources, or concentrate animals in a way that increases risk of disease spread.
Human interactions with birds might also change in the presence of offshore wind infrastructure -- for example, if an artificial reef effect of turbine structures brought more recreational fishing into areas of high marine bird density, entanglement in fishing gear could become more frequent.

The above focuses on offshore effects of offshore wind.
Of course, activities such as trenching for cables at coastal sites and construction of transmission corridors to connect offshore facilities with onshore grid infrastructure are land-based components of offshore wind development that could affect species that frequent shorelines and inland habitats.
Clearing of transmission corridors and installation of transmission lines have consequences for birds, including the potential for habitat loss, degradation, or creation, depending on the species [@askins2012; @martin2022].
Because transmission corridors are not novel development types in the United States, have been the subject of past research, are addressed by current environmental laws, and represent a small area of impact relative to the footprint of offshore wind facilities, they are not the focus of this section or this chapter.
However, they represent a potential source of impact that certainly must be evaluated as part of the environmental review of any wind facility.

On a global scale, the development of offshore wind facilities could serve as a major component of the transition away from fossil fuel use, reducing greenhouse gas emissions and mitigating climate change [@barthelmie2021].
The mitigation of climate change is a major conservation action affecting many bird species, including those that breed or forage at high latitudes [@bateman2020].
Because oil spills and other pollution-related impacts from fossil fuels are major stressors for many marine birds [@troisi2016], moving to a clean energy framework could also reduce direct impacts from fossil fuel use.

Offshore wind development could indirectly benefit avian species if wind facility developers implement effective voluntary off-site mitigation efforts, conducted in such a way and to such an extent that they actually provide a net benefit to species' populations.
Off-site mitigation planning is discussed later in this chapter.
In addition, a greater scientific interest and research focus on certain species in the context of offshore wind development might lead to a better scientific understanding that elucidates unrelated conservation issues and opportunities and ultimately better serves these species.

## Common Data Collection Methods and Approaches

A wide variety of scientific methods are used for studying birds in coastal and offshore environments, which are summarized below.
This section is intended to provide a brief description of different study methods, rather than a detailed assessment of the pros/cons and current state of development of each technology/methodology.
For tracking of new technologies, see the Tethys [database of monitoring technologies](https://tethys.pnnl.gov/wind-energy-monitoring-mitigation-technologies-tool).

Note that this brief review focuses on technologies or methods which can be used in the offshore environment or at coastal/island nesting sites of seabirds and shorebirds.
There are many additional survey techniques and protocols used in the onshore environment.
These are relevant to the study of terrestrial effects of offshore wind -- such as effects of trenching for cables where they are brought ashore, or clearing of transmission corridors to connect offshore wind with onshore grid infrastructure -- but for the sake of brevity and a focus on novel offshore issues, they are not addressed here.

### Observational Surveys

**At-sea aerial surveys for seabirds** were historically conducted using airplanes flying at roughly 60-200 m over the ocean surface, with live observers recording observations within a certain distance from the line of transect.
In more recent years, some at-sea surveys have transitioned over to the use of aerial photos or videos, including high-definition photos or video, which can be conducted at a higher flight altitude.
High-definition aerial photography has some advantages over live observers, including reduced bird disturbance due to the higher flight altitude, less effect of observer bias, and the availability of raw data for quality control and future re-analysis. 
In addition, there is some evidence that aerial video can cover a larger area, provide greater spatial accuracy, lead to higher numbers of sightings, and more frequently identify birds to species [@zydelis2019].
Of greatest importance to offshore wind studies is the higher flight altitude – conducting at-sea surveys at no more than 100 m over the ocean surface will not be possible at offshore wind facilities once turbines are installed.
In order to be able to accurately compare before/after survey results in the vicinity of offshore wind facilities, high-definition aerial photography (still photos or video) are recommended for all offshore surveys of seabirds moving forward. 

Censusing birds at sea is the primary objective of this research method; however, flight height estimates can in some cases be gleaned from the data.
In addition, with digital aerial photographs, or particularly video, it is sometimes possible to identify obvious behaviors, like foraging dives.
However, even with video, recordings are only brief (e.g., 6-8 frames of a bird over 1 second), and therefore not particularly informative regarding behavior.

**Boat-based** **surveys** can also be used to inventory/census bird species present at sea.
At smaller spatial scales, they can be more cost-effective than aerial surveys.
They can provide a higher level of accuracy in identifying species, age, and behavior of seabirds at sea [@camphuysen2004].
As lease areas become larger and locations further offshore, aerial surveys may naturally become more cost-effective and more common.
While all study methods have some biases, boat-based surveys tend not to be as good as aerial surveys for detecting some taxa – particularly seaducks and loons, which can be disturbed by boats [@camphuysen2004].

Boat-based or stationary (e.g., turbine platform-based) observations using live observers can also be used to estimate flight height and collect behavioral data, such as documenting foraging behavior or responses to turbines.

In coastal areas and on islands, **population surveys** of colonial nesting seabirds, long-legged wading birds, or shorebirds are common.
These surveys are sometimes aerial [@bakó2014] (using aerial still photographs or video), or may be ground-based, including surveys at nesting colonies to census the entire population at a particular site and, in some cases, to assess survival of marked individuals.
At nesting sites, other observational studies may also be conducted, including **nest monitoring to document nest productivity over time, behavioral studies, and observations of adults feeding young** to document diet.

**Incidental observations** can also provide useful information about species presence and behavior, particularly for those infrequently observed at sea.
Citizen science can also be used to collect these types of data – eBird is one database that capitalizes on this type of data to generate useful information about timing and distributions of bird occurrence, although offshore data of this type are quite limited.

### Radar and Lidar

**Radar systems** (RAdio Detection And Ranging) come in a range of types, sizes, frequencies, and modes of action, which affect the spatial and temporal scales of detection, resolution, and types of data collected.
They detect birds by emitting pulses or continuous streams of radiowaves which are scattered from any object encountered, producing an “echo” in returned energy which is detected and interpreted by the radar equipment.
They can be used to study a variety of aspects of avian ecology [@hüppop2019].

NEXRAD (WSR-88D) towers are large, S-band, Doppler weather radar stations deployed across the United States to provide information on a broad set of weather conditions, including precipitation and wind speed [@diehl2005].
These radars have a lower resolution than some, but can detect flocks of birds, including migrants leaving stopover sites for high-altitude nocturnal flights in the spring and fall, trans-Gulf of Mexico movements, and broad- and narrow-front migrations.
They have been used to identify stopover, passage, and roosting areas [@buler2014; @chilson2019], as well as to study changes in total bird abundance (measured as biomass) and phenology over time (e.g., see [@chilson2019; @horton2020; @rosenberg2019]. In addition, there are applications for behavioral ecology describing flight speed, direction, orientation, and altitude. NEXRAD coverage does extend offshore in some portions of Atlantic coast, but the radar beam typically samples altitudes above most bird migration in this region. BOEM is currently funding [a study](https://www.boem.gov/sites/default/files/documents/environment/environmental-studies/GM-22-02_1.pdf) to create a database of terrestrial migrating birds moving to and from the offshore environment including through use of NEXRAD along the U.S. Atlantic Coast. Note that Canadian weather radars deployed in the maritime provinces could also provide data valuable for studies at the northern end of the RWSC Study Area.

X-band radars use smaller antennae and have a smaller spatial range.
They operate using a shorter wavelength, and hence have a higher target resolution.
These radars also scan the atmosphere more regularly, increasing temporal resolution.
Mobile X-band radar units can be deployed on coastal and island sites, boats, or offshore infrastructure to monitor for passage rates of commuting or migrating birds.
They cannot identify animals to species, but can provide information about wingbeat frequency and body size, which can inform classification, as well as information about flight height, direction, and speed.

Many ships are equipped with S-band or X-band radars (or both) to aid in navigation, with S-band systems providing longer-range data and better functioning in fog, and X-band radars, as noted above, providing greater precision.
These “marine” radars can also be used to detect birds, with precise applications and data dependent on the type of system.

The use of portable radars for avian research offshore is currently being explored through [a BOEM-funded study](https://www.boem.gov/sites/default/files/documents/environment/environmental-studies/GM-23-01.pdf).

**Lidar** (Light Detection and Ranging) systems work by a similar mechanism, but use a different frequency on the electromagnetic spectrum.
In this technology, a laser beam is emitted, which bounces back after it encounters an object.
Lidar systems are more precise than radar, but operate over a shorter range, and are obstructed by fog or rain [@bilik2023].
The use of this technology for measuring bird flight height is effective offshore and can be accurate to within 1 meter [@cook2018].
Cook et al. (2018) provides recommendations on use, but uncertainties remain regarding Lidar capabilities for wildlife monitoring, particularly for detection of small-bodied birds [@sloan2023].

### Acoustics

**Acoustic surveys** using acoustic detectors (a combination of microphones and recording devices) to record calls of birds are becoming increasingly common [@pérez-granados2021], although they remain more frequently used for bats.
This method of monitoring can provide information about migration phenology, species composition, acoustic soundscapes for communication, and, in some cases, numbers of passing individuals.
Acoustic surveys for birds in the offshore environment are most commonly used for night migrants [@hill2008], and typically use passive, stationary detectors configured to sample primarily in the audible frequency range (e.g. 1-12 kHz).
Passive surveys offshore utilize stationary detectors deployed on ocean buoys, meteorological towers, offshore wind turbines, other offshore infrastructure (such as electrical service platforms \[ESPs\], also commonly referred to as offshore substations \[OSSs\]).

Acoustic surveys are only effective when study animals are vocalizing.
Ambient noise can interfere with detection of vocalizing animals and limit the distance over which calls will be recorded, an important factor to consider in deploying acoustic detectors on operating turbines. 
Challenges also remain in differentiating among flight calls of different species [@bioacous2020; @priyadarshani2018].
However, software for the detection, classification, and analysis of field-collected audio files continues to be improved [@vandoren].
Some new software can address suboptimal signal-noise ratios and evaluate areas of masking interference to speed and to refine analyses [@vandoren2023].
The extent to which acoustic survey technologies can be counted upon to operate continuously in harsh offshore conditions also requires further evaluation.

### Banding, Tagging, and Tracking

**Capture-mark-recapture** studies can be used to assess population size, evaluate survival, and study migratory movements of long-ranging birds.
**Bird banding** is a very common practice for birds of all sizes, with banding information typically going to a central repository, the [Bird Banding Laboratory (BBL)](https://www.usgs.gov/labs/bird-banding-laboratory).
(Note that the BBL database cannot handle data on birds that are not fit with metal USGS bands, which includes most piping plovers on the Atlantic Coast. Those data are instead housed locally on project-level databases.)

There are a variety of different types of **tags** which can be attached to birds to gather information about their movements.
Birds can be outfitted with **geolocator tags**, which measure daylight versus time, allowing for estimates of latitude and longitude, approximating bird positions.
An advantage of these tags is that they are very lightweight.
However, they have an accuracy range of only ± 200 km, and the animal must be recaptured in order to retrieve the data.

GPS dataloggers receive information from a satellite system known as the Global Positioning System, which is maintained by the U.S. government [@smithsonianinstitute2023].
Wherever a GPS receiver has unobstructed line-of-sight to four or more GPS satellites, it can use the information transmitted by the satellites to calculate accurate time and location.
GPS dataloggers are set to record data at regular intervals (rather than continuously) to generate a dotted movement track.
In order to access the data, the animal must be recaptured and the tag recovered.
Alternatively, GPS receivers can be paired with a transmitter that sends the data to a particular server, which can be a satellite system (for global coverage) or cellular phone system (where cell tower coverage is expected to be available).
For these types of tags, the animal does not need to be recaptured; however, the use of a transmitter requires a larger battery, which means that they cannot be deployed on smaller bird species.
Geofencing is the practice of creating a specific study area defined by a virtual perimeter; this methodology can allow for the collection of a higher frequency of recorded GPS data locations within wind facility boundaries.

[**Satellite tags**](https://nationalzoo.si.edu/migratory-birds/what-satellite-telemetry) are also deployed on birds.
Platform Transmitting Terminals (PTT) tags send periodic messages to a global satellite system called Argos, which is dedicated to ecological and environmental research [@smithsonianinstitute2023].
Argos Service satellites pick up and store signals, relaying them in real-time back to earth, where data are processed and delivered to researchers.
As with GPS transmitters, battery size currently limits the size of bird on which these tags can be deployed.
Spatial uncertainty of Argos data is 250 m to \>1500 m, and flight height data cannot be recorded; thus, these data are less accurate than GPS data.

**VHF (Very High Frequency) and UHF (Ultra High Frequency) radiotags** transmit signals in the radio frequency range, which can be detected with a receiver.
These types of tags are regularly deployed on birds.
Historically, tags with different frequencies were deployed on animals within one research study to allow for easy identification of different individuals.
The animals were then tracked, often via manual telemetry with a hand-held receiver.
Manual tracking could be conducted on-foot, using a vehicle, boat, or aircraft.
Study animals could also be tracked via a receiver attached to a stationary tower with antennae pointed in multiple directions, which could be automated to detect signals periodically or rotated manually by a researcher to detect a signal with an associated bearing.
Manual telemetry is limited by the search effort available for finding and pinpointing the radio signal, and hence faces significant challenges in tracking animals that range over long distances.

In recent years, the development of the [Motus Wildlife Tracking System](http://www.motus.org) has allowed for much more widespread use of coordinated automated radiotelemetry for tracking of wide-ranging and/or migrating birds.
This system relies on coded radiotransmitters which all operate on one of two common frequencies, but which emit unique ID codes to identify different individuals.
Signals from the tags are received by a network of automated radiotelemetry stations consisting of antennas, a receiver, a power source, memory storage, and sometimes data transmission infrastructure. 
Telemetry stations can be deployed on land, on coastal locations, or on offshore infrastructure, including ocean buoys and offshore wind turbine platforms.
Advantages of this system include that tags are small and stations deployed by one research group can detect passage of animals by other researchers operating in the same network, allowing for development of a widespread network with more likelihood of detecting wide-ranging study animals.
This system also has the distinct advantage over manual telemetry that signals can be monitored for continuously.
Motus system technology has limitations, including limited range of some telemetry stations (typically 15 km) and, in most cases, an ability to determine only general proximity or bearing from the station rather than precise location.
Efforts to improve triangulation capabilities are underway (see Section 6).
Offshore wind developers are including deployment and maintenance of Motus stations, as well as tag deployment, as part of Avian Monitoring Plans developed for review by BOEM and USFWS.
Motus station deployment and research efforts in the U.S.
Atlantic are coordinated through the [Atlantic Offshore Motus Project](https://motus.org/groups/atlantic-offshore-wind/).

### Bird-Turbine Interaction & Collision Detection Systems

On turbine platforms, turbine nacelles, or other offshore infrastructure, **cameras** can be used to record bird presence and behavior in the vicinity of turbines, which can inform when and where animals are present in portions of the rotor-swept zone and document bird interactions with turbines, including perching, roosting, attraction, micro-avoidance, lack of response, or collisions.
Cameras differ in their mode of action, resolution, and the frequencies of electromagnetic radiation they use, from conventional cameras that operate in the visual range, to so-called “infrared” cameras that operate in the near infrared range, to so-called “thermal” cameras that operate in the far infrared range.
Continuously operating cameras provides unique information about bird behavior in the vicinity of wind turbines.
These systems can also be employed in conjunction with other sensors (e.g., acoustics, radar) to deliver additional information about behavior or collisions (see below).
However, many of these systems are expensive at present and often only deployed at one or a few turbines in a study area.
The field of view of a particular camera is often not sufficient to encompass the full rotor-swept zone, at least with sufficient granularity to identify birds throughout that zone.
The extent to which these technologies can be counted upon to operate continuously in the harsh offshore environment is currently being evaluated.

At onshore wind facilities, **carcass surveys** are commonly used to document mortality and estimate fatality rates for a variety of bird species that collide with wind turbines.
Offshore, carcasses of individuals can be expected to fall into the ocean in most instances and so **collision detection systems** are needed.
Collision detections systems may incorporate visual range, thermal, or infrared cameras as described above (e.g., see [@happ2021]), as well as acoustic detectors, radar systems, and/or accelerometers for impact detection.
Over a dozen multi-sensor systems for documenting collisions and other bird interactions with wind turbines are under evaluation or currently in use at wind facilities [@dirksen2017; @nrel2022], and at least three have been deployed on offshore turbines [@lagerveld2020; @markdesholm2003; @tjørnløv2023; @willmott2023].
Efforts are currently underway at land-based wind facilities to develop, improve, and validate collision monitoring technologies.
At present, validation activities are limited to the terrestrial environment, where results can be compared with carcass searches.

There are a number of technologies in various stages of development or deployment intended for **automated real-time identification of bird species or groups**.
In addition to monitoring uses, these can be integrated with active curtailment or deterrent systems.
Technologies that have been tested in the offshore environment include [Spoor](https://group.vattenfall.com/uk/newsroom/pressreleases/2023/vattenfall-launches-an-expanded-trial-of-spoor-ai-technology-at-aberdeen-bay-offshore-wind-farm) and [DT Bird](https://www.dtbird.com/).

Beach carcass surveys for the bodies of birds killed at offshore turbines have been proposed, but are only likely to be effective, if at all, in locations with very specific geographies and patterns of ocean currents.
Occasionally, birds that collide with turbines may fall to the turbine platform.
Birds may also collide with ships accessing wind energy facilities for construction or maintenance.
Carcasses can be collected from turbine platforms, boats, and offshore infrastructure; when identified and documented, they provide incidental information about species’ occurrence in the marine environment, possible offshore wind facility impacts, and effects of increased vessel traffic in these areas.

### Other Monitoring Methodologies

There are a range of **tissue sampling** methods from live-caught birds, or their feces, which provide a variety of information about individuals’ migratory status, diet, and health, as well as population-level genetic structure. 
These include collections of feathers, blood, skin, stomach contents, and fecal matter, to variously conduct stable isotope analysis, physiological analyses (e.g., for stress hormones), diet assays, genetic analyses, or others (e.g., see [@cook2012; @robuck2021; @steenweg2017].

In addition to direct sampling of individuals, collection of DNA from the ambient environment (**eDNA**) also has the potential to provide information about species present marine areas [@closek2019; @zhang2020].
This is a relatively new technology and the utility of this technique to address various research questions is not yet fully understood.

## Research Topics: Birds and Offshore Wind in the U.S. Atlantic 

Research questions about offshore wind development and wildlife are centered around two common themes.
First, there is a need to measure, estimate, model, or otherwise assess the scale of impacts of offshore wind development on birds, in order to determine which impacts are significant at an individual, subpopulation, or population scale.
Second, there is a need to understand how to address any impacts that may occur via effective mitigation.
In the context of this chapter, “mitigation” is used broadly, as defined by the Council on Environmental Quality (CEQ) National Environmental Policy Act (NEPA) regulations ([40 CFR § 1508.20](https://www.ecfr.gov/current/title-40/chapter-V/subchapter-A/part-1508)). 
Thus, mitigation in this context includes:

-   **Avoiding the impact** altogether by not taking a certain action or parts of an action.
    This could include strategies like siting wind facilities with setbacks from colonial breeding sites of birds of conservation concern or outside of areas with high densities of particular marine bird species.

-   **Minimizing impacts** by limiting the degree or magnitude of the action and its implementation.
    This could include strategies like implementing lighting regimes that minimize bird attraction to turbines.

-   **Rectifying the impact** by repairing, rehabilitating, or restoring the affected environment.
    This could include projects like stabilizing or revegetating areas affected where trenching occurred to allow for laying of a transmission cable.

-   **Reducing or eliminating the impact** over time by preservation and maintenance operations during the life of the action.

-   **Compensating for the impact** by replacing or providing substitute resources or environments.
    This could include off-site efforts like supporting predator control at a nesting site to increase populations of a breeding tern species that is affected by collision mortality.

The goal of mitigation measures could be to meet regulatory requirements to negate or offset any negative impacts of offshore wind development, or to meet voluntary goals of providing a net benefit to the species.

From the perspective of a regulator, conservationist, or offshore wind developer, the progress of research would ideally proceed from development of accurate and cost-effective technologies for wildlife monitoring, standardized systems for data collection and analysis, and understanding of baseline conditions, moving then to evaluation of impacts and mitigation strategies, and finally to widespread development of offshore wind in the context of implementation of effective mitigation measures.
However, given the rapid pace of offshore wind development [@u.s.departmentofenergy2023], this slow and measured progression is not a realistic timeline.
Rather, multiple areas of research will need to be advanced simultaneously.
In the meantime, regulators must necessarily rely on the best available science, both in identifying areas that should be avoided in siting of wind facilities (mitigation via avoidance) and in assessing potential risks to protected and vulnerable species.
Tools must continue to be developed to help inform these efforts.
While many conservationists prefer focusing on earlier steps in the mitigation hierarchy [@arlidge2018], the reality is that the impacts of offshore wind development will not be fully evaluated until many hundreds of turbines are installed.
This suggests that effective on-site and off-site mitigation measures will also need to be an early focus, because once turbines are in the water, they are unlikely to be removed or turned off completely.
On-site mitigation options may be employed, where feasible.
However, off-site mitigation to compensate for or voluntarily offset impacts may be the only viable option, in some cases, for addressing documented or probable impacts.

Research topics of interest for birds and offshore wind include:

-   **Creating a structure in which to collaboratively conduct and share scientific research and advances, through discussion, coordination, and planning.**

-   **Improving data collection and distribution methods.**  This includes standardization of data workflows, refinement of structures for data sharing, and technological advances.

-   **Understanding baseline conditions of bird populations and bird ecology offshore.** 

    -   This includes addressing questions about how distribution patterns, density, and movements vary by time of year, with meteorological conditions, across seasons (i.e., breeding, migration, nonbreeding seasons), by sex, age, and reproductive status, with interannual variation, and especially in the context of global climate change. 
        Understanding distribution and abundance during the breeding season is of particular interest for colonial nesters that may be tied to only a few historic breeding areas.
        Movement metrics of interest include speed, distance and longevity of flights, flight height, and starting points and destinations.

    -   This also includes assessing important variables relative to population dynamics (e.g., fecundity, survival, population structure) and interactions among bird species and with prey populations.

-   **Informing pre-construction risk assessments of potential impacts to birds.** This includes considering exposure of birds to offshore wind development, based on baseline distributions noted above.
    Collecting data to inform collision risk models and developing these models are also included.

-   **Assessing impacts of construction and operation of offshore wind facilities.** This includes assessing changes from baseline conditions (e.g., distribution patterns, movements, population dynamics and trajectories, ecological interactions) in the context of climate change and other environmental changes.
    It also includes documenting collision fatalities, where possible.

-   **Evaluating on-site mitigation strategies**.
    This could include mitigation activities effective during construction (e.g., noise reduction measures) or operation (e.g., painting turbine blades).

-   **Identifying and evaluating off-site mitigation strategies.** As noted above, due to the rapid pace of offshore wind development relative to the pace of research on impacts, off-site mitigation could represent an important aspect of offshore wind development, if significant impacts are found.
    These could be implemented to meet “no net loss” regulatory requirements or involve voluntary conservation offsets providing a net benefit to species.

Specific research questions are detailed in the [Atlantic Offshore Wind Environmental Research Recommendations database](https://tethys.pnnl.gov/atlantic-offshore-wind-environmental-research-recommendations), which summarizes data gaps and questions from a variety of peer-reviewed and technical report publications.

One recommendation of this plan is to reconcile broad research topics with specific research questions through the identification of focal species, major potential areas of offshore wind impact, and focal research questions by subregion and lease area (see Section 6).

## Regional-scale Ongoing, Pending, and Recommended Science Actions in the U.S. Atlantic

This section of the Science Plan discusses science actions recommended to further the scientific understanding of effects of offshore wind infrastructure on birds and to address mitigation strategies in the context of identified impacts.

This section is structured by the type of science action, including:

-   Data management

    -   Standardization of data collection, analysis, and reporting

    -   Historical data compilation

-   Data analysis & planning

    -   Model development and statistical frameworks

    -   Meta-analysis and literature review

    -   Optimizing research, monitoring, and mitigation

-   Technology advancement

-   Field data collection and analysis

Recent, current, and pending science activities are discussed throughout as necessary to provide a context for current recommendations.
These and other recent activities are tracked in the [RWSC Offshore Wind & Wildlife Research Database](https://database.rwsc.org/).

Other resources for learning about recent and on-going offshore wind-wildlife research include the [Tethys Knowledge Base](https://tethys.pnnl.gov/knowledge-base), a Pacific Northwest National Laboratory database, which houses publications, reports, and presentations relevant to offshore wind, and the [Tethys Offshore Wind metadata](https://tethys.pnnl.gov/offshore-wind-metadata), which compiles information on environmental monitoring conducted at offshore wind energy projects around the world.
The [New York State Energy Research and Development Authority Environmental Technical Working Group (NYSERDA E-TWG)](https://www.nyetwg.com/) hosts [State of the Science Workshops on Wildlife and Offshore Wind Energy](https://www.nyetwg.com/past-workshops), which provide an opportunity for researchers to present and discuss updates on the state of knowledge regarding wildlife and offshore wind energy development and to promote collaboration and regional coordination.
Both the [E-TWG](https://www.nyetwg.com/webinar-library) and [Tethys](https://tethys.pnnl.gov/environmental-webinars?content=467) have webinar libraries regarding environmental issues and offshore wind.

### Data Management: Data Collection, Processing, Housing, and Compilation

This section addresses data collection, processing, and housing for the types of data collected as part of studies to inform potential impacts of offshore wind development on bird species in the Northwest Atlantic.
Section 6.1.1 summarizes recommended data standards and recommended science actions relevant to each data type.
Section 6.1.2 provides detail on current and recent efforts related to recommended data standards and infrastructure.
Section 6.1.3 provides detail on current gaps in data infrastructure.

#### Data Standards & Recommended Science Actions

Understanding avian behavior around offshore wind turbines, at the scale of entire wind facilities, and regionally along the Atlantic Flyway, will require close coordination among researchers, state and federal agencies, and industry.
The Bird & Bat Subcommittee wishes to work with individuals and entities who collect data relevant to avian-offshore wind research to ensure that data are collected and stored in consistent formats that allow comparisons and pooling across individual projects in the RWSC Study Area.
This standardization is intended to support regional-scale assessments and the development and maintenance of regional data products and tools (e.g., marine bird distribution models, collision risk models).

In order to support these efforts, the Bird & Bat Subcommittee recommends:

-   Maintenance of an up-to-date resource list of recommended standard databases, data repositories, guidelines, and protocols for use by all data collectors. 
    The current recommended resources are detailed in the table below.

-   Development of standard language for inclusion in funding and contract documents to encourage or require the consistent use of recommended resources.

-   Establishment of an Avian Data Standards Working Group to address gaps in existing data infrastructure (detailed in the table below), including development of recommended protocols/standards where absent, recommendations for the structure/content of new databases, and identification of pilot study parameters where too little is currently known to provide specific methodological guidance.
    The order in which gaps are addressed will be prioritized by the Bird & Bat Subcommittee and working group members, taking care to avoid duplicating efforts by outside groups.

-   Establishment of data sharing frameworks to appropriately manage access to sensitive industry-collected datasets necessary for research (e.g., avian-turbine interaction, micro-avoidance, and collision data; turbine status and local environmental conditions; turbine specifications relevant to placement of monitoring equipment).

-   Compilation of new and historic data into recommended databases to inform scientific understanding of behavior, distribution, and population dynamics of birds of the U.S.
    Atlantic Coast.

-   Review of workflows to ensure processes are in place to facilitate transfer of data products from wildlife databases to appropriate regional data portals: Northeastern Regional Association of Coastal Ocean Observing Systems (NERACOOS), Mid-Atlantic Regional Association Coastal Ocean Observing System (MARACOOS), and Southeast Coastal Ocean Observing Regional Association (SECOORA)

**The following table summarizes the existing centralized or accepted repositories and standards that are recommended for use in avian data collection, identifies data types for which no or limited data management capacity (i.e., standard repositories and guidance) currently exists, and lists recommendations for expansion of data standards and/or historic data compilation.**

+--------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Methods and data types**                                               | **Database/Repository**                                                                                                             | **Guidance/Standards**                                                                                                                                                                                                                                    | **Recommendations**                                                                                                                                                                                                                          |
+--------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| At-sea surveys                                                           | [**Northwest Atlantic Seabird Catalog**](https://coastalscience.noaa.gov/project/statistical-modeling-marine-bird-distributions/)   | -   Follow [Guidance for Pre- and Post-Construction Monitoring to Detect Changes in Marine Bird Distributions and Habitat Use Related to Offshore Wind Development](https://www.nyetwg.com/avian-displacement-guidance)                                   | -   *Develop a public-facing interface for the Northwest Atlantic Seabird Catalog.*                                                                                                                                                          |
|                                                                          |                                                                                                                                     |                                                                                                                                                                                                                                                           |                                                                                                                                                                                                                                              |
| (aerial, stationary, boat-based; visual observation, photography, video) |                                                                                                                                     | -   Ensure consistency with [*BOEM Guidelines for Providing Avian Survey Information for Renewable Energy Development on the Outer Continental Shelf*](https://www.boem.gov/sites/default/files/documents/newsroom/Avian%20Survey%20Guidelines.pdf)       | -   *Identify funding to support continued ingestion of new survey data into the database as it is collected.*                                                                                                                               |
|                                                                          |                                                                                                                                     |                                                                                                                                                                                                                                                           |                                                                                                                                                                                                                                              |
|                                                                          |                                                                                                                                     | -   Utilize [SeaScribe](https://briwildlife.org/seascribe/) or [SeaLog](https://www.usgs.gov/software/sealog) for data collection\                                                                                                                        |                                                                                                                                                                                                                                              |
|                                                                          |                                                                                                                                     |     \                                                                                                                                                                                                                                                     |                                                                                                                                                                                                                                              |
+--------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Automated radio tagging/tracking studies                                 | [**Motus Wildlife Tracking System**](https://motus.org/about/)                                                                      | -   Utilize [Monitoring Protocols and Guidance for Automated Radio Telemetry Studies at Offshore Wind Farms](https://motus.org/groups/atlantic-offshore-wind) for study design and data collection                                                        | -   *Improve access to historical offshore bird Motus data through a systematic effort to identify relevant past projects and request public access to data if not already available*                                                        |
|                                                                          |                                                                                                                                     |                                                                                                                                                                                                                                                           |                                                                                                                                                                                                                                              |
|                                                                          |                                                                                                                                     | -   [Motus Wildlife Tracking System resources](https://motus.org/resources/) provide extensive additional documentation on data collection, upload, and analysis                                                                                          | -   *Develop guidance regarding deployment, metadata, and data storage of local meteorological data associated with telemetry receiver stations to inform timing of bird movements and behavior relative to local weather conditions.*       |
+--------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

+------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+
| Other tagging/tracking studies                       | [**Movebank**](https://www.movebank.org/)                                                                                                                                                         | -   Follow interim [USFWS Guidance for Coordination of Data from Avian Tracking Studies](https://rwscorg.sharepoint.com/:b:/s/BirdandBatSubcommittee/EWiyjaGje4tOsn7YjpJ13P8B8jQRQP9b2nUt9y4dRwpV6g?e=Ew3LOO)   | -   *Develop in-depth guidance for non-Motus tagging studies.*                                                                       |
|                                                      |                                                                                                                                                                                                   |                                                                                                                                                                                                                 |                                                                                                                                      |
| (e.g., satellite, GPS, geolocator tags)              |                                                                                                                                                                                                   | -   [Movebank User Manual](https://www.movebank.org/cms/movebank-content/manual) provides step-by-step guidance on adding, managing, sharing, and accessing tracking data                                       | -   *Systematically solicit and compile historical tracking data for birds in coastal and offshore environments into Movebank.*      |
|                                                      |                                                                                                                                                                                                   |                                                                                                                                                                                                                 |                                                                                                                                      |
|                                                      |                                                                                                                                                                                                   | -   Ensure shorebird tracking data are accessible to the [Shorebird Conservation Collective](https://nationalzoo.si.edu/migratory-birds/shorebird-collective)                                                   |                                                                                                                                      |
+------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+
| Bird banding, band identification and reporting      | [**USGS Bird Banding Laboratory**](https://www.usgs.gov/labs/bird-banding-laboratory)                                                                                                             | -   Follow Federal Bird Banding and Marking Permit requirements (as required by law)                                                                                                                            |                                                                                                                                      |
|                                                      |                                                                                                                                                                                                   |                                                                                                                                                                                                                 |                                                                                                                                      |
|                                                      |                                                                                                                                                                                                   | -   Identified bands can be reported at [www.reportband.gov](file:///Users/christianlaspada/Downloads/www.reportband.gov)                                                                                       |                                                                                                                                      |
+------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+
| Carcasses and tissue samples                         | [**Renewables-Wildlife Solutions Initiative**](https://www.usgs.gov/centers/forest-and-rangeland-ecosystem-science-center/science/renewables-wildlife-solutions)                                  | -   Report fatalities to [USFWS](https://ecos.fws.gov/imr/welcome)                                                                                                                                              | -   *Identify funding and develop additional capacity for carcass and tissue sample storage.*                                        |
|                                                      |                                                                                                                                                                                                   |                                                                                                                                                                                                                 |                                                                                                                                      |
|                                                      |                                                                                                                                                                                                   | -   Contact the [Renewables-Wildlife Solutions Initiative](https://www.usgs.gov/centers/forest-and-rangeland-ecosystem-science-center/science/renewables-wildlife-solutions) to submit samples                  |                                                                                                                                      |
|                                                      |                                                                                                                                                                                                   |                                                                                                                                                                                                                 |                                                                                                                                      |
|                                                      |                                                                                                                                                                                                   | -   *Note that RWSI has limited capacity but is currently accepting samples.*                                                                                                                                   |                                                                                                                                      |
+------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+
| Coastal waterbird population and distribution data   | **Atlantic Flyway Colonial Waterbird Database** is currently under development by the [Avian Knowledge Network](https://avianknowledge.net), through funding from the Atlantic Flyway Council     | -   Follow [Avian Knowledge Network data upload and management guidance](https://avianknowledge.net/index.php/upload-enter-manage-data/) for data submission to this database                                   | -   *Expand CWB database to include nesting shorebirds.*                                                                             |
|                                                      |                                                                                                                                                                                                   |                                                                                                                                                                                                                 |                                                                                                                                      |
|                                                      | [**International Shorebird Survey**](https://www.manomet.org/project/international-shorebird-survey/)allows for data entry of shorebird survey data collected using established protocol          | -   Use species- and study-appropriate protocols as applicable, e.g.:                                                                                                                                           | -   *Develop additional guidance for species not covered by current protocols.*                                                      |
|                                                      |                                                                                                                                                                                                   |                                                                                                                                                                                                                 |                                                                                                                                      |
|                                                      |                                                                                                                                                                                                   |     -   [International Shorebird Survey](https://www.manomet.org/project/international-shorebird-survey/) protocol                                                                                              | -   *Solicit additional survey data stored by states and other organizations.*                                                       |
|                                                      |                                                                                                                                                                                                   |                                                                                                                                                                                                                 |                                                                                                                                      |
|                                                      |                                                                                                                                                                                                   |     -   [IWMM protocols](https://iwmmprogram.org/protocols-data-forms/) for monitoring habitat conditions and waterbird use during the nonbreeding season                                                       | -   *Identify stable funding to ensure new data can be incorporated as collected.*                                                   |
|                                                      |                                                                                                                                                                                                   |                                                                                                                                                                                                                 |                                                                                                                                      |
|                                                      |                                                                                                                                                                                                   |     -   [USFWS framework](https://ecos.fws.gov/ServCat/DownloadFile/101125) for surveys for secretive marsh birds                                                                                               |                                                                                                                                      |
+------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+

+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Other observational survey data (e.g., from land-based surveys for transmission cable routes)                                                                                                                                                                                       | [**eBird**](https://ebird.org/home)                                                                                                                                        | -   Utilize [eBird Protocols](https://support.ebird.org/en/support/solutions/articles/48000950859-guide-to-ebirdprotocols) as appropriate                                                                                                                                   | -   *Develop detailed protocols for different types of onshore avian observational surveys associated with transmission ROW clearing and cable permitting processes.*     |
|                                                                                                                                                                                                                                                                                     |                                                                                                                                                                            |                                                                                                                                                                                                                                                                             |                                                                                                                                                                           |
| \*Note: This is not intended to include standardized survey data collected as part of regular annual surveys (such as the [Breeding Bird Survey](https://www.pwrc.usgs.gov/bbs/) or [Christmas Bird Count](https://www.audubon.org/conservation/science/christmas-bird-count)).     |                                                                                                                                                                            | -   Note: Utilize established survey protocols and data entry points for standardized annual surveys (such as the [Breeding Bird Survey](https://www.pwrc.usgs.gov/bbs/) or [Christmas Bird Count](https://www.audubon.org/conservation/science/christmas-bird-count)).     | -   *Update eBird mobile app to allow for more detailed recording and retention of quantifiable survey conditions and survey effort in eBird.*                            |
|                                                                                                                                                                                                                                                                                     |                                                                                                                                                                            |                                                                                                                                                                                                                                                                             |                                                                                                                                                                           |
|                                                                                                                                                                                                                                                                                     |                                                                                                                                                                            |                                                                                                                                                                                                                                                                             | -   *Update eBird platform to support incorporation of outside meteorological data into downloadable data or data products.*                                              |
|                                                                                                                                                                                                                                                                                     |                                                                                                                                                                            |                                                                                                                                                                                                                                                                             |                                                                                                                                                                           |
|                                                                                                                                                                                                                                                                                     |                                                                                                                                                                            |                                                                                                                                                                                                                                                                             | -   *Note this is a lower priority due to the plan’s focus on offshore avian studies.*                                                                                    |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Observed interactions with wind turbines, collisions, fatalities                                                                                                                                                                                                                    | [**Injury and Mortality Reporting database**](https://ecos.fws.gov/imr/welcome) tracks reports of dead and injured birds.                                                  | -   Report dead or injured birds to the [Injury and Mortality Reporting database](https://ecos.fws.gov/imr/welcome).                                                                                                                                                        | -   *Identify goals and pilot study recommendations for collision detection technologies.*                                                                                |
|                                                                                                                                                                                                                                                                                     |                                                                                                                                                                            |                                                                                                                                                                                                                                                                             |                                                                                                                                                                           |
| (e.g., via turbine-mounted cameras, impact detection systems)                                                                                                                                                                                                                       | No central repository exists for other types of bird-turbine interaction data or more detailed collision/fatality data and associated metadata– requires development       |                                                                                                                                                                                                                                                                             | -   *Develop a database and standard data collection protocols.*                                                                                                          |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

+-------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+-------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| Marine bird diet studies                                                                        | No central repository                                               | No standardized protocols                                   | -   *Develop a database and standard data collection protocols.*                                                                                     |
|                                                                                                 |                                                                     |                                                             |                                                                                                                                                      |
|                                                                                                 |                                                                     |                                                             | -   *Solicit additional diet data stored by individual states and other organizations.*                                                              |
+-------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+-------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| Passive acoustic monitoring                                                                     | No central repository                                               | No standardized protocols                                   | -   *Identify goals and pilot study recommendations for passive acoustic studies.*                                                                   |
|                                                                                                 |                                                                     |                                                             |                                                                                                                                                      |
|                                                                                                 |                                                                     |                                                             | -   *Develop a database and standard data collection protocols.*                                                                                     |
+-------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+-------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| Radar/lidar studies                                                                             | No central repository for data collected from small/mobile radars   | Standardized protocols not available for many radar types   | -   *Identify goals and pilot study recommendations for radar/lidar studies.*                                                                        |
|                                                                                                 |                                                                     |                                                             |                                                                                                                                                      |
|                                                                                                 |                                                                     |                                                             | -   *Develop a database and standard data collection protocols.*                                                                                     |
+-------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+-------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| Large raw file types (e.g., high-definition aerial photos, thermal video, raw acoustic files)   | No central repository                                               |                                                             | -   *Retention of large, raw file types could allow for future QA/QC and re-evaluation with updated analysis or automated identification tools.*     |
|                                                                                                 |                                                                     |                                                             |                                                                                                                                                      |
|                                                                                                 |                                                                     |                                                             | -   *Development of a data repository is recommended as a cross-taxa action.*                                                                        |
+-------------------------------------------------------------------------------------------------+---------------------------------------------------------------------+-------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+

#### Current and Recent Efforts

##### At-Sea Surveys

Historical offshore survey data in the Northwest Atlantic were compiled as part of the establishment of the [Northwest Atlantic Seabird Catalog](https://www.boem.gov/environment/environmental-studies/14-x07pdf-0).
This effort represented a collaboration of BOEM, USGS, USFWS, and NOAA, with many researchers and organizations contributing data. 
This enormous effort included development of the catalog in a format that allowed for flexibility to include and categorize different historic survey methodologies and practices.
The catalog is open to collecting new or historical data sources as they become available, although a concerted effort to collect additional historical data in this category is no longer necessary. 

The [Avian Displacement Guidance Committee](https://www.nyetwg.com/avian-displacement-guidance), a Working Group of the New York State Energy Research and Development Authority Environmental Technical Working Group (NYSERDA E-TWG), was organized to develop guidance for pre- and post-construction monitoring to detect macro- and meso-scale changes in avian distributions and habitat use in relation to offshore wind development. 
In its draft guidance, this Workgroup identified key displacement and attraction-related questions, highlighted appropriate methodologies to address those questions, and provided specific study design and analytical recommendations for boat-based and aerial surveys.
Final guidance is expected by the end of 2023.

##### Tracking via Automated Telemetry

Automated telemetry data collected via the [Motus Wildlife Tracking Network](https://motus.org/) are automatically stored in the Motus system.
Hence, historical data for birds are naturally stored alongside data collected from current and recent projects. 
Birds Canada staff have made efforts in recent years to solicit tag metadata associated with tag deployments from past projects where not previously recorded in the Motus system.

While Motus is well-established for use in terrestrial and coastal systems, it has only recently begun to expand into marine environments.
With funding from NYSERDA, collaborators from USFWS, BRI, BC, and the University of Rhode Island (URI) developed a series of [monitoring protocols, guidance, and tools](https://motus.org/groups/atlantic-offshore-wind/) to inform the deployment of automated radio telemetry technology in relation to offshore wind energy development in the U.S.
Atlantic. 
Final products, released to the public in 2023, include 1) a Guidance Document describing technical specifications for deploying and operating Motus stations on offshore structures, 2) metadata sheets, data sheets, and reference guides for use in the field, 3) a free, on-line Motus decision support tool known as “Informing the Design and Implementation of Offshore Motus Systems” (IDIOMS) that allows users to optimize site-specific Motus study designs at offshore wind energy facilities, 4) an Offshore Motus Data Framework, which establishes an Atlantic Offshore Wind Group within Motus and describes data workflows within Motus, and 5) a Monitoring Framework providing a comprehensive overview of using Motus to track wildlife offshore and to inform research, monitoring, and assessments of offshore wind energy projects in the Atlantic region of North America.

Development of the IDIOMS tool was informed by recent work on the optimization of Motus infrastructure conducted by Juliet Lamb of The Nature Conservancy.
This effort included analysis and modelling of Motus tower layout and bird sampling strategies resulting in recommendations for appropriate tower layout and sampling of breeding shorebirds and seabirds to maximize Motus detections [@lamb2023].

##### Tracking via other Tagging Systems

Use of geolocators, satellite tags, and VHF tags on birds in coastal and offshore environments is a common practice, currently and historically.
While some efforts have been made to organize tracking data in a central location, these efforts are by no means exhaustive.
Review and analysis of these data would benefit from a focused effort to pull recent and historic data into Movebank.
[Movebank](https://www.movebank.org/cms/movebank-main) is a free, online platform hosted by the Max Planck Institute of Animal Behavior that allows researchers and wildlife managers worldwide to manage, share, analyze and archive animal tracking and other animal-borne sensor data. 
The USFWS has developed basic guidance on metadata standards for non-Motus tagging efforts, but this is another area that could benefit from additional work to create more comprehensive guidance.

##### Bird Banding

As noted in Section 4, banding information and band identifications are typically housed in a central repository, the [Bird Banding Laboratory](https://www.usgs.gov/labs/bird-banding-laboratory) (BBL).
The BBL database includes most banding data, but cannot handle data on birds that are not fit with metal USGS bands, which includes most piping plovers on the Atlantic Coast.
Those data are instead housed locally on project-level databases.

The Bird & Bat Subcommittee is not aware of any recent data standardization projects by the BBL relevant to offshore wind and birds.

##### Other Observational Data

[eBird](https://ebird.org/about) data document bird distribution, abundance, habitat use, and trends through checklist data collected within a simple, scientific framework.
Birders enter when, where, and how they went birding, and then fill out a checklist of all the birds seen and heard.
[Specific protocols](https://support.ebird.org/en/support/solutions/articles/48000950859-guide-to-ebird-protocols) for some types of surveys are available.
Given the availability of other databases, this database is recommended primarily for land-based surveys currently not accommodated by the Northwest Atlantic Seabird Catalog or the Coastal Waterbird Database.

#### Current Gaps in Data Infrastructure

There are a number of identified gaps in infrastructure to support standardized data collection and workflows.
The major gaps identified for birds are as follows:

##### Coastal Waterbirds Data

Regular monitoring of marine birds, shorebirds, and long-legged wading birds breeding along the Atlantic Coast is relevant to offshore wind development for a number of reasons.These types of data provide important metrics, including demographics, survivorship, fecundity, nest success, and population health.
These data are useful in evaluating how offshore wind may be affecting populations.
For example, lower juvenile survival could be associated with reduced foraging near wind facilities.
These data are also needed to understand other longer-term trends or factors affecting populations, which may have nothing to do with wind development, but can help isolate the impacts of offshore wind through comparing regional to local data and recent to historic trends.

For colonial nesting seabirds (terns and skimmers, petrels and shearwaters, gulls, alcids, pelicans, cormorants, and anhingas) and long-legged wading birds (herons, egrets, ibises), in particular, breeding survey data can provide the locations of breeding colonies that are in close proximity to proposed or existing offshore wind facilities.
These surveys can also help assess risk to adults and fledged young that may spend time in, around or pass through wind farms to forage or when traveling to and from wintering grounds. 

Historically, many states individually collected breeding survey data for colonial nesting seabirds and long-legged wading birds, species groupings collectively referred to as colonial waterbirds (CWB).
There have been occasional regionally coordinated CWB surveys conducted by two or more states simultaneously.
However, historically, these data were stored in separate state-managed databases, since there was no central location for these data. 
Some states’ data were eventually collated into a database managed by USGS Patuxent.
This database was updated by collaborators from USGS, USFWS, and the University of Maine, who inventoried the data and [created]{.underline} an ArcGIS Shiny App to explore and summarize these data at multiple spatial scales.
The Maine Seabird Atlas, Seabird Colony Registry and Atlas for the Southeastern U.S. and other CWB survey data were also incorporated into the database at that time.
In 2020, the Atlantic Flyway Council began funding the development of an Atlantic Flyway CWB data management system as part of the Avian Knowledge Network.
This system is intended to securely house historic, contemporary, and future CWB breeding data collected by Atlantic Flyway states and provinces and provide mapping, analytical and other decision support tools to inform CWB management at multiple spatial scales.
Some protocols exist for surveying particular species or groups of coastal waterbirds, as summarized in Section 6.1.1.
However, in general, studies across multiple states do not use consistent and standardized protocols, in part due to difficulties in coordination and in part due to the wide variety of habitats and species assemblages occurring along the Atlantic Coast.

In recent years, the Atlantic Flyway Nongame Migratory Bird Technical Section led an effort to promote coordinated CWB breeding surveys within the Atlantic Flyway.
The first flyway-wide survey started in 2023 and will finish in 2024.
Because colonial waterbirds encompass many species that occupy a wide variety of habitat types, some of which are difficult to access, survey planners identified five focal species that states and provinces with limited capacity and/or funding constraints agreed to survey.
The focal species include Common Terns, Least Terns, Black Skimmers, Laughing Gulls and Double-crested Cormorants; all species are either of high conservation or management concern in most Atlantic Flyway states and provinces.
This pilot effort could serve as a template for future, regularly recurring coordinated surveys that cover increasing numbers of species, as states and provinces institutionalize CWB breeding surveys in their work plans.

##### Marine Bird Diet Data

Marine bird diet data provide important information associated with adult and fledgling survival, health, and forage fish availability. 
One potential impact of offshore wind could be to change foraging patterns as well as forage fish abundance, distribution, and species composition – potentially having important ramifications for feeding marine birds and shorebirds.
Collection of these historic data in a centralized database is a need that has been identified by other avian working groups; the data are relevant for many purposes, and not for an understanding of offshore wind impacts alone.

Marine bird diet data (terns and alcids) collected by NAS and USFWS in Maine are all in an ACCESS database, but this has not been publicly shared and does not currently include data from other states or other projects.
Recently, the Atlantic Marine Bird Cooperative (AMBC) forage fish and seabird colonies and adjacent waters working groups embarked on a coordinated seabird diet monitoring project along the Atlantic and Gulf coasts.
The initial focus will be on collecting fecal samples from Common Tern and Black Skimmer adults and chicks, using a consistent protocol. 
Maine Coastal Islands NWR staff also initiated development of seabird diet monitoring guidance (L. Welch and R. Boettcher, personal communication).
Other than these recent efforts, there are some older recommendations for reporting diet study results (e.g., [@barrett2007]), but the Bird & Bat Subcommittee is not aware of widely used marine bird diet data protocols.

##### Collision & Bird-Turbine Interaction Database

As discussed in Section 4, some incidental collision fatalities may be identified during visits to offshore turbine platforms.
Currently, there is no standard, cost-effective way to rigorously monitor for collisions offshore. 
However, unimodal and multi-modal systems to document bird interactions with wind turbines, including behavior, micro-avoidance, and collisions, are being developed and validated at land-based wind facilities and pilot-tested on offshore turbines.
Where fatalities are only documented in an incidental fashion, fatality data may be of limited value, but are nevertheless important, given our limited scientific understanding of potential offshore impacts.
In the future, as technologies allow for collection of data in a more scientific and rigorous fashion, collision, micro-avoidance, and other turbine interaction data will be critical for evaluating impacts of offshore wind and (if necessary) identifying effective mitigation strategies. 
The need for a designated database and availability of detailed data for scientific analysis will hence become crucial. 

There is some sensitivity regarding reporting of fatality and collision information, as well as sharing of videos and photographs of bird interactions with wind energy infrastructure.
Reporting of these data is related to regulatory requirements under federal law, and public reporting of collision data could result in negative publicity.
In addition, important covariates to use in analyses include potentially sensitive business information, like wind speed and the operational status of the turbine.
Some wind companies consider these items to be proprietary information, although practices differ among companies and are dependent on company policies, permitting and development stage, and the granularity/specificity of the data provided. 

There is no central database currently available for the collection of fatality information, or more generally for the disposition of video, photo, radar, acoustic, or impact detection data related to bird behavior, avoidance, and collisions associated with offshore wind infrastructure. 
In the terrestrial environment, there are two databases which could inform development of an offshore database, Nature Counts and AWWIC.
[The Nature Counts](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwicu-HG9KOCAxUGjokEHUgHBlcQFnoECBEQAQ&url=https%3A%2F%2Fwww.naturecounts.ca%2F&usg=AOvVaw3jXdmAAIWe0ZoJp-K-GKBJ&opi=89978449) database collects bird fatality information from Canadian land-based wind facilities.
The [American Wind Wildlife Information Center](https://rewi.org/about-us/our-work/awwic/) (AWWIC) collects post-construction fatality data from land-based wind facilities in the United States.
Database managers work with wind industry collaborators to compile both publicly available and privately contributed fatality data, including important covariates (e.g., effort, methodology, meteorological conditions), and to allow for the analysis of this data by Renewable Energy Wildlife Institute (REWI) staff, as well as other researchers.
Careful limitations on data sharing and requirements for sharing aggregated data ensure that no data from private sources could lead to identification of individual wind facilities.

One challenge associated with the AWWIC database is that it includes tailored non-disclosure agreements negotiated with each wind facility operator individually, and new data analyses and studies must often be negotiated with data contributors.
An offshore collision fatality database for birds should instead include standard protocols for how data are collected, entered, and reported, including which covariates are necessary for interpretation.
The database should also include clear data sharing standards to allow access for federal regulators and simplify sharing of data with outside researchers for analysis and synthesis, while addressing developer concerns regarding data security, confidentiality, and aggregation in reporting results publicly.

##### Bird Acoustic Database

Acoustic monitoring of birds is typically conducted for nocturnal migrants.
It can be valuable in the offshore environment, where there is little information available about smaller bird species, particularly those moving at night.
This methodology is of interest as a cost-efficient strategy to assess bird activities offshore [@normandeauassociatesinc.2014], and it is included as a part of some Avian Monitoring Plans.
There is currently no centralized database to house such data or clear guidance on deployment.

##### Radar and Lidar Data Results

While NEXRAD and other large radar data are archived in government databases, there is currently no centralized database to house radar or lidar data results from smaller-scale systems.
There are also no clear guidelines on appropriate systems for deployment offshore, deployment methodology, or specific study goals.
As discussed in Section 4, radar and lidar can provide information about bird passage rates and flight heights.

##### Tissue Sample Repository 

There is an identified need for a tissue repository to store tissue samples, including carcasses of birds recovered from offshore wind facilities or boat strikes.
These remnants are much less likely to be found at offshore facilities than at terrestrial facilities, since carcasses are most likely to fall into the ocean and not be recoverable and regular carcass searches are not likely to be proscribed.
However, carcasses of birds may occasionally be recovered on offshore wind facility infrastructure incidentally.
In addition, tissue samples may be collected from birds in offshore or coastal areas for various research purposes, including genetic, physiological, stable isotope, or disease dynamics studies.
If not destructively sampled for analysis as part of the initial study, these samples could be stored for later use and to benefit future analyses.

At present, there is one repository which accepts bird carcasses recovered at renewable energy facilities.
The [Renewables-Wildlife Solutions Initiative](https://www.usgs.gov/centers/forest-and-rangeland-ecosystem-science-center/science/renewables-wildlife-solutions) (RWSI), organized by Todd Katzner (USGS) and Mark Davis (University of Illinois), has established a successful system for collecting and tracking bird samples from wind facilities, including sample storage and an Access database.
The organizers are open to accepting samples and carcasses from offshore wind facilities.
However, this small-scale repository could easily be overwhelmed if all bird carcasses and tissue samples currently collected or stored by state agencies, federal agencies, wind developers, and environmental consultants were to suddenly begun to be shipped to these locations.

USGS researchers, working with colleagues, have mapped out a hierarchical structure for a database that could allow for the tracking of carcasses and tissue subsamples throughout the country.
There has also been discussion of logistical needs – for example, the establishment of regional collection centers to reduce transportation/shipping challenges for frozen samples.
As of 2023, this plan has not been implemented.
While development of a tissue sample repository would be of great value to renewable energy-wildlife research, it is likely of lower priority for offshore wind facilities where, as noted, collection of carcasses and tissue samples is likely to occur less frequently.

##### Raw File Data Repository

In addition to databases, there is a need for a data repository to store raw data with large file types – e.g., radar data, thermal video, digital aerial survey photos and videos, and acoustic files.
Derived data from these types of files should be made available in relational databases as relevant; however, the raw data should also be retained in a central location for quality control, re-analysis, and future re-evaluations with better tools.
For example, future machine learning advances may allow for faster and more effective automated identification of bird species.

### Data Analysis & Planning

Data analyses and summaries should 1) inform where new data collection is needed, 2) characterize avian distribution patterns, density, movements, behavior, and population dynamics, 3) assess whether offshore wind is causing any observed changes, 4) assess the impacts of those changes on bird populations, and/or 5) evaluate the efficacy of monitoring or mitigation strategies.

Section 6.2.1 summarizes recommended science actions. 
Section 6.2.2 provides context for recommended actions in the form of current and recent activities.
These sections are structured based on the broad research topics laid out in Section 5.
Note that improvements to data collection and distribution methods are also addressed in Sections 6.1 and 6.3.

#### Recommended Science Actions

In order to address current needs, the Bird & Bat Subcommittee recommends:

-   **Coordinating and planning for scientific research**

    -   Using best available information to build, maintain, and regularly update a shared exposure/risk vulnerability matrix for both marine and land-based bird species. 
        This matrix will be used to identify focal species by geography, lease area, potential impact of research interest, and research question.

    -   Review of available cumulative effects literature and adoption of a clear framework for assessing cumulative effects.

    -   Consultation with the Bird & Bat Subcommittee prior to conducting analyses of coastal and offshore avian data to ensure that the research leverages all available data and contributes to addressing key issues and data gaps.

    -   Collaborating among Subcommittees and with outside experts to ensure cross-taxa issues are being addressed. 
        Two examples:

        -   Working with the Habitat & Ecosystem Subcommittee and fish experts to ensure that collected data and data products include important bird habitat variables and prey species. 

        -   Working with the Marine Mammal Subcommittee to coordinate with and train Protected Species Observers/Marine Mammal Observers to monitor and report dead and injured birds found on vessels.

    -   Developing a user-friendly guidance document on different bird research methods, summarizing the costs and benefits of each in terms of types and quality of data collected, effort required, financial costs, and options available. 
        (One guide that could be built upon is available [here](https://tethys.pnnl.gov/publications/bat-bird-monitoring-guidance).)

-   **Informing pre-construction risk assessments**

    -   Identifying key metrics and summarizing relevant data (e.g., movement metrics, distribution and abundance, flight height, flight speed, micro-avoidance) to inform collision risk models.

-   **Understanding baseline conditions and assessing impacts**

    -   Regularly updating marine bird distribution models and maps based on at-sea observations.

    -   Analyzing existing tracking data from multiple sources to develop pre-construction baselines (e.g., movements, distributions, behavior) for focal species.

    -   Incorporating data from multiple methods (e.g., at-sea surveys, tracking, radar) and covariates (oceanographic, meteorological, prey distribution estimates) into integrated models.

    -   Identifying key metrics and summarizing relevant data (e.g., movement metrics, distribution and abundance, flight height, flight speed, micro-avoidance, meso-avoidance) to inform vulnerability assessments and collision risk models.

    -   Analyzing and summarizing available seabird diet data to inform potential effects of offshore wind energy on foraging.

    -   Summarizing available population demographic data to develop updated population models and assess potential population-level impacts for focal species.

    -   Developing regional-scale power analyses to inform regional-scale study designs.

-   **Identifying and evaluating mitigation strategies**

    -   Advanced planning, development, and assessment of off-site conservation measures to provide compensatory mitigation (“no net loss”) or support voluntary conservation efforts.

#### Current and Recent Efforts

##### Coordination and Planning for Scientific Research

**Summary of Research Priorities**.
The [NYSERDA E-TWG Regional Synthesis Workgroup](https://www.nyetwg.com/regional-synthesis-workgroup) was organized to inform and provide interim guidance for regional-scale research and monitoring of offshore wind energy and wildlife in the eastern United States.
With technical support from BRI, the group compiled [a database](https://tethys.pnnl.gov/atlantic-offshore-wind-environmental-research-recommendations) of research needs and data gaps from existing sources, including published, peer-reviewed synthesis papers, State of the Science Workgroups, federal and state agency efforts, and previous E-TWG Specialist Committees, etc..
The database was designed to synthesize existing data gaps and research needs so that researchers and funders can easily access, sort, and further prioritize topics.
The database specifies focal taxa, spatial scale, and other information relating to each priority research topic.
The Workgroup also drafted written guidance, including definitions of common terminology to support regional communications, general suggested criteria for prioritization of regional research topics, and general recommendations on study design and data transparency for regional-scale research efforts.

**Data Gaps Analysis**.
[Project WOW](https://offshorewind.env.duke.edu/), a Wildlife and Offshore Wind study led by Duke University, with collaborators, is performing a data gaps analysis to understand where sufficient data exist to generate meaningful estimates of likely impacts, and where they do not.
This analysis will be based on a quantitative scoring of literature, based on species names and taxa. 
For a preliminary summary of this analysis, see [Meeting 4 in the public RWSC files](https://rwscorg.sharepoint.com/:b:/s/BirdandBatSubcommittee/EfR6tZUhTTFDiKP_l-tSNPABmt9dRbouoFnsxkcxurIGJA?e=OBpxXh).

**Cumulative Effects Framework.** Croll et al. recently published a proposed framework for assessing and mitigating impacts of offshore wind development on marine birds [@croll2022].

**Motus Network Coordination.** The Motus network continues to expand through the work of Birds Canada, USFWS, and many other collaborators.
However, the system could benefit from a more coordinated and less piecemeal approach towards deployment of Motus stations, in an arrangement that maximizes detection probabilities for focal species.
In addition, centralized calibration and maintenance efforts, to ensure stations are functioning and to measure detection ranges systematically, would also be of benefit for scientific rigor and cost savings.
In summer 2020, USFWS organized initial meetings among stakeholders to discuss the value of coordinating and possibly centralizing calibration of Motus stations, as well as deployment of both Motus stations and VHF radiotags for automated telemetry in the offshore environment. 
Phase 1 of the project would include efforts by RWSC to develop a plan for coordination and centralization, incorporating the [*Offshore Motus Framework*](https://motus.org/groups/atlantic-offshore-wind/), highlighting subregions/sites and species of interest, proposing a design or framework for optimal or strategic tag deployment, listing key participants (tag project funders, species and land managers, etc.), and describing data standardization practices.
