# Bats {#sec-append-bats}

## Introduction

This chapter of the RWSC Science Plan addresses bat research and associated scientific needs in the context of offshore wind development.
The plan is intended to reflect the research and data collection needs of RWSC’s four Sectors with input from the science community.
The plan will provide a path forward to ensure appropriate data collection protocols and standards are in place to support scientific research; this document can also provide a framework that can aid RWSC participants in coordinating and aligning funding to carry out necessary scientific activities.

This plan benefits greatly from the contributions of RWSC Bird and Bat Subcommittee members; researchers, managers, and other practitioners who joined Subcommittee calls; and the many scientists who conducted research or developed reference materials cited throughout this plan.

Following this introduction, the first section of the chapter discusses the geographic extent of the area considered within this chapter, the species of bats which occur within this geographic range, and a summary of primary sources of information about species’ distributions.
The next section of this chapter discusses potential effects of offshore wind development on bat species.
The following section summarizes common field research methods for the study of bats, with a focus on the offshore environment. 
The subsequent section addresses the major research topics and questions relevant to bats in the context of offshore wind development.
The remainder of the chapter addresses recommended science actions of value to the four sectors that make up RWSC (state and federal agencies, eNGOs, and the offshore wind industry), in the context of recent, ongoing, and pending scientific activities relevant to recommended actions.

## Species

This chapter addresses bat (Class Mammalia, Order Chiroptera) species which could be at risk from offshore wind development occurring in the Northwest Atlantic within U.S. waters.
For the purposes of this plan, the geographic area of interest comprises the Atlantic Coast of the United States, extending from Maine’s northern border with Canada south to the Florida Keys, and from coastal areas extending 200 nm east into the ocean, including state waters (3 nm from shore) and federal waters of the Outer Continental Shelf (3-200 nm).
This area is referred to in this plan as the RWSC Study Area.
While the focus of this plan is offshore impacts of offshore wind development, potential onshore impacts of offshore wind on bat species are also possible.
For example, clearing of transmission line corridors could remove trees used by summer maternity colonies.
Therefore, bat species which primarily or solely occur in the onshore environment along the Atlantic Coast are nevertheless included within the scope of this plan, although they are not the focus of this chapter.

### Bat Species occurring in the Northwest Atlantic

There are 17 species of bat which commonly or occasionally occur within the 14 states of the U.S.
Atlantic Coast (**Table 1**).
They are all insectivorous species that belong to the family Vespertilionidae.
Three additional species, the velvety free-tailed bat (*Molossus molossus*), big free-tailed bat (*Nyctinomops macrotis*), and the Virginia big-eared bat (*Corynorhinus townsendii virginianus*), are either only rarely encountered in the RWSC Study Area or are only found inland and are not likely to interact with coastal or offshore activities related to offshore wind.

+-------------------------------------+------------------------------------+------------------------+--------------------------+---------------+----------+
| **Scientific Name**                 | **Common Name**                    | **Federal ESA Status** | **IUCN Red List Status** | **State ESA** | **SGCN** |
+-------------------------------------+------------------------------------+------------------------+--------------------------+---------------+----------+
| *Corynorhinus rafinesquii macrotis* | Rafinesque's eastern big-eared bat |                        | Least Concern            | 3             | 5        |
+-------------------------------------+------------------------------------+------------------------+--------------------------+---------------+----------+
| *Eptesicus fuscus*                  | big brown bat                      |                        | Least Concern            | 0             | 10       |
+-------------------------------------+------------------------------------+------------------------+--------------------------+---------------+----------+
| *Eumops floridanus*                 | Florida bonneted bat               | Endangered             | Vulnerable               | 1             | 1        |
+-------------------------------------+------------------------------------+------------------------+--------------------------+---------------+----------+
| *Lasionycteris noctivagans*         | silver-haired bat                  |                        | Least Concern            | 1             | 12       |
+-------------------------------------+------------------------------------+------------------------+--------------------------+---------------+----------+
| *Lasiurus borealis*                 | eastern red bat                    |                        | Least Concern            | 1             | 12       |
+-------------------------------------+------------------------------------+------------------------+--------------------------+---------------+----------+
| *Lasiurus cinereus*                 | hoary bat                          | In USFWS Workplan      | Least Concern            | 1             | 12       |
+-------------------------------------+------------------------------------+------------------------+--------------------------+---------------+----------+
| *Lasiurus intermedius*              | northern yellow bat                |                        | Least Concern            | 2             | 4        |
+-------------------------------------+------------------------------------+------------------------+--------------------------+---------------+----------+
| *Lasiurus seminolus*                | Seminole bat                       |                        | Least Concern            | 0             | 3        |
+-------------------------------------+------------------------------------+------------------------+--------------------------+---------------+----------+
| *Myotis austroriparius*             | southeastern myotis                |                        | Least Concern            | 2             | 6        |
+-------------------------------------+------------------------------------+------------------------+--------------------------+---------------+----------+
| *Myotis grisescens*                 | gray bat                           | Endangered             | Vulnerable               | 3             | 4        |
+-------------------------------------+------------------------------------+------------------------+--------------------------+---------------+----------+
| *Myotis leibii*                     | eastern small-footed bat           |                        | Endangered               | 8             | 13       |
+-------------------------------------+------------------------------------+------------------------+--------------------------+---------------+----------+
| *Myotis lucifugus*                  | little brown bat                   | Under Review           | Endangered               | 6             | 13       |
+-------------------------------------+------------------------------------+------------------------+--------------------------+---------------+----------+
| *Myotis septentrionalis*            | northern long-eared bat            | Endangered             | Near Threatened          | 10            | 13       |
+-------------------------------------+------------------------------------+------------------------+--------------------------+---------------+----------+
| *Myotis sodalis*                    | Indiana bat                        | Endangered             | Near Threatened          | 7             | 7        |
+-------------------------------------+------------------------------------+------------------------+--------------------------+---------------+----------+
| *Nycticeius humeralis*              | evening bat                        |                        | Least Concern            | 0             | 3        |
+-------------------------------------+------------------------------------+------------------------+--------------------------+---------------+----------+
| *Perimyotis subflavus*              | tri-colored bat                    | proposed Endangered\   | Vulnerable               | 4             | 14       |
|                                     |                                    | (Sept 2022)            |                          |               |          |
+-------------------------------------+------------------------------------+------------------------+--------------------------+---------------+----------+
| *Tadarida brasiliensis*             | Brazilian free-tailed bat          |                        | Least Concern            | 0             | 1        |
+-------------------------------------+------------------------------------+------------------------+--------------------------+---------------+----------+

: **Table 1.** Bats regularly occurring in the 14 states of the RWSC Study Area. The state ESA column indicates the number of Atlantic Coast states in which the species is listed as state endangered, threatened, or of special concern. The SGCN column indicates the number of Atlantic Coast states in which the species is listed as a Species of Greatest Conservation Need.

For more information about the species in Table 1, see *Bat Species Descriptions* \[forthcoming in 2024\].

#### Regulatory Status

Currently four bat species that regularly occur in the RWSC Study Area are listed as Endangered under the [federal Endangered Species Act (ESA)](https://ecos.fws.gov/ecp0/reports/ad-hoc-species-report?kingdom=V&kingdom=I&status=E&status=T&status=EmE&status=EmT&status=EXPE&status=EXPN&status=SAE&status=SAT&mapstatus=3&fcrithab=on&fstatus=on&fspecrule=on&finvpop=on&fgroup=on&header=Listed+Animals), one is [under review](https://ecos.fws.gov/ecp/species/9051), and one has [been proposed](https://ecos.fws.gov/ecp/species/10515) for listing as Endangered.
In addition, the hoary bat has been added to the USFWS National Domestic Listing Workplan to undergo a status review at the discretion of the Service in FY2027 [@usfws2023].
The ESA places strict limits on the import, export, sale, possession, transportation, or “take” of listed species, with “take” defined as “to harass, harm, pursue, hunt, shoot, wound, kill, trap, capture, or collect, or to attempt to engage in any such conduct.” [@unitedstates1983].
The ESA also allows for the designation of critical habitat for a species and prohibits the destruction of that habitat.

In addition to federal regulations, most states have a state Endangered Species List, which offers its own protections. 
Fourteen bat species are protected by state statutes in the 14 states of the RWSC Study Area. 
Individual State Wildlife Action Plans also identify [Species of Greatest Conservation Need (SGCN)](https://www1.usgs.gov/csas/swap/) which serve as foci for research and conservation efforts; all of the bat species that regularly occur along the Atlantic Coast are listed as SGCN in one or more states [@usgs2023].

Hoary bats, silver-haired bats, and eastern red bats were designated as Endangered in 2023 by Canada’s Committee on the Status of Endangered Wildlife in Canada (COSEWIC) due to land-based wind energy impacts on these species [@cosewic2023].

#### Focal Species 

At least six bat species have been detected visually or acoustically over the waters of the Northwest Atlantic [@solick2021].
The vast majority of detections identified to species were one of the three long-distance migratory tree bats (eastern red bat, hoary bat, silver-haired bat).
Tricolored bats, big brown bats, and *Myotis* species have also been detected, albeit more rarely [@solick2021].
Challenges in differentiating amongst species acoustically (e.g., see [@nocera2019]) means that it can be difficult to positively determine which *Myotis* spp.
are detected offshore.

While some scientific research methods will provide information about a variety of taxa (e.g., acoustic surveys), other research methods (e.g., tagging) provide species-specific data.
In the offshore environment, the three long-distance migrants are the focal species of greatest interest for tagging efforts due to the greater likelihood of their exposure to offshore wind farms, as described above, as well as anticipated higher collision risk, based on fatalities at land-based wind farms [@awwi2020].
Eastern red bats and hoary bats are of particular interest - eastern red bats because they are detected most frequently offshore, and hoary bats because they are the species considered at greatest risk from land-based wind development [@awwi2020; @friedenberg2021].
Land-based wind fatalities would suggest these species are most at risk during the late summer-fall migration season [@lloyd2023], and offshore acoustic data support the idea that migratory bats are most common offshore during this season [@stantec2016].
For *Perimyotis subflavus* and *Myotis* species of conservation concern (see Table 1), tagging of individuals occurring in coastal areas and on islands is also of interest, particularly during the late summer and early fall, when they may make longer-distance movements to hibernation sites, which could involve over-ocean travel.
Spring migratory movements from hibernation sites could also involve over-ocean travel, although it could be more difficult to target for tagging individuals headed for coastal and island summer territories if captured at inland hibernation sites.
Northern long-eared bats, little brown bats, and tricolored bats have been successfully captured at coastal and/or island locations [@hoff; @dowling2018; @zaradowling2017; @grider2016]; if other listed *Myotis* species are captured, they could also be considered potential focal species.
At present, there are not identified sites where other *Myotis* could be captured in numbers large enough to represent a meaningful sample size.

Other species could be affected if near-shore facilities are built in the future, or by tree clearing and construction where transmission cables come ashore.
In these circumstances, federally listed and state-listed species would be of greatest concern during the development process.

### Regional Coastal/Offshore Distribution Information

Patterns of bat distribution and abundance in the offshore environment are poorly understood.
Limited tagging/tracking efforts [@dowling2018; @true2023] (T. Peterson, personal communication) and a number of mobile and stationary acoustic surveys have been conducted, in addition to documentation of incidental visual observations during aerial and boat-based surveys for other taxa [@hatch2013].
Studies conducted through 2021 were summarized in a recent literature review [@solick2021], which provides a thorough compilation as well as links to the various studies included in the review.
For more recent studies (since 2021), see the [Tethys Knowledge Base](https://tethys.pnnl.gov/knowledge-base) and the [RWSC Offshore Wind & Wildlife Research Database](https://database.rwsc.org/).

[The North American Bat Monitoring Program (NABat)](https://sciencebase.usgs.gov/nabat/#/results) provides seasonal occupancy and abundance maps for a number of bat species across the U.S., modelled based on data collected by a host of federal researchers and other collaborators.
Because the data are sparse, these maps do not yet include the offshore environment.
However, the NABat grid system has been extended offshore, and the database is prepared to collect coastal and offshore detections of bat species, which can be incorporated into future analyses and mapping of species distributions [@cox2022].

Critical habitat for ESA-listed bat species, where designated, typically focuses on important hibernation sites or large summer maternity colonies.
These could be relevant to onshore locations of transmission infrastructure for interconnection between offshore facilities and the electricity grid.
Critical habitat designations for bats are available as part of USFWS species profiles, as follows:

-   Indiana bat: <https://ecos.fws.gov/ecp/species/5949>

-   Gray bat: <https://ecos.fws.gov/ecp/species/6329>

-   Northern long-eared bat: [https://ecos.fws.gov/ecp/species/9045](#0)

-   Tricolored bat: <https://ecos.fws.gov/ecp/species/10515>

-   Florida bonneted bat: <https://ecos.fws.gov/ecp/species/8630>

-   Hoary bat: <https://ecos.fws.gov/ecp/species/770>

-   Little brown bat: <https://ecos.fws.gov/ecp/species/9051>

## Potential Effects of Offshore Wind on Bats

Collision with operating wind turbines is expected to be the main potential impact of offshore wind development on bats [@nrel2022], although collision risk and fatality rates in the offshore environment are currently entirely unknown.
In the terrestrial environment, bat mortality at wind facilities is a common occurrence [@awwi2020], and these fatalities are estimated to represent a population-level, and even existential, threat to some migratory tree bat species [@frick2017; @friedenberg2021].
Analyses of onshore rates of fatality at land-based wind facilities has suggested that wind-associated mortality could also compound population-level impacts to bat populations already affected by white-nose syndrome (WNS) [@erickson2016].

Overall, in the absence of offshore infrastructure, bat activity is thought to be lower at isolated offshore sites compared to most coastal, island, and inland habitats [@solick2021; @stantec2016].
However, bats appear to be attracted to land-based wind turbines and other tall structures [@cryan2014; @guest2022; @jameson2014].
Researchers have hypothesized that the greater height of offshore wind turbines and their prominence in an otherwise flat seascape could increase attraction of bats to offshore wind facilities [@solick2021], potentially increasing collision risk or leading to greater exposure to harsh weather conditions offshore (see [@wilson2023]).
Historic records indicate that bats sometimes flocked around sailing ships [@pelletier2013], and more recent studies have documented bats roosting and foraging around offshore turbines in Europe [@ahlén2009].

Given bat attraction to turbines, offshore wind facilities are not expected to cause habitat displacement or impose barriers to habitat connectivity.
Offshore wind turbines in fact could offer potential roost and stopover sites or foraging locations for migrating bats [@ahlén2009; @brabant2020; @lagerveld2020], but due to collision risk, any energetic advantage conveyed by this increase in roosting habitat is likely more than offset by the potential negative impact of fatalities [@solick2021].

As noted above, the three migratory tree bats (hoary bat, eastern red bat, and silver-haired bat) have been found to be the most vulnerable to collisions at land-based wind facilities and are also the species that most commonly occur offshore.
Therefore, these species are considered at the greatest risk of negative impacts.
Little is known about the scale of potential impacts offshore on migratory tree bats or other bat species.

Potential positive effects of offshore wind development on bats are difficult to evaluate at present.
The expected effects of climate change on North American bats are largely unknown [@hammerson2017], and thus climate change mitigation effects of offshore wind development are difficult to assess.
Much of the literature regarding effects of climate change on bats comes from modelling studies rather than empirical evidence [@festa2023].
In the U.S., mitigation measures are typically designed to offset losses due to new infrastructure, rather than provide a net benefit to species.
However, through off-site mitigation, offshore wind facility operators could voluntarily choose to support conservation actions that could potentially provide a net benefit to bat species.
For rare *Myotis* species, off-site mitigation strategies include protection of hibernacula and summer maternity habitat [@usfws2022].
Effective methods for off-site mitigation for migratory tree bats have not been demonstrated.
One benefit of offshore wind development to bats could be the greater scientific interest and research focus on these under-studied organisms; this might lead to a better scientific understanding that ultimately better serves these species.

## Common Data Collection Methods and Approaches

A number of scientific methods are used for studying bats in the offshore environment, which are summarized below. 
This section is intended to provide a brief description of different study methods, rather than a detailed assessment of the pros/cons and current state of development of each technology/methodology.
For tracking of new technologies, see the Tethys [database of monitoring technologies](https://tethys.pnnl.gov/wind-energy-monitoring-mitigation-technologies-tool).

Note also that this brief review focuses on technologies or methods relevant to marine environments.
There are additional survey techniques and protocols used in the terrestrial environment.
Those are relevant to the study of terrestrial effects of offshore wind – such as effects of clearing transmission corridors to connect offshore wind with onshore grid infrastructure – but for the sake of brevity and a focus on novel offshore issues, they are not addressed here.

### Acoustic Surveys

Acoustic surveys can be conducted using acoustic detectors to record calls of bats \[@loeb2015\].
Surveys may be conducted using passive (stationary) methods or active methods.
Active surveys onshore are typically conducted using a vehicle; at sea, they are often boat-based (e.g., see [@sjollema2014]), although drones are beginning to be used experimentally [@workboatstaff2023].
Passive surveys offshore utilize stationary detectors deployed on ocean buoys, meteorological towers, offshore wind turbines, other offshore infrastructure (such as electrical service platforms or “ESPs”); use of coastal and island sites are also common for understanding timing and locations of bat movements in the coastal and marine environments (e.g., see [@peterson2014]).
Acoustic surveys for bats utilize detectors which operate in the ultrasonic range in which most echolocation calls fall.
Note that acoustic surveys are only effective when study animals are vocalizing, and ultrasound does not travel far through the atmosphere.
Ambient noise can also interfere with detection of vocalizing animals and limit the distance over which calls will be recorded.
Differentiating among species can also be difficult for certain taxa [@nocera2019].

### Tagging and Tracking

Tagging and tracking can be a useful way to understand bat movements and activity.
**VHF (Very High Frequency) and UHF (Ultra High Frequency) radiotags** transmit signals in the radio frequency range, which can be detected with a receiver.
These types of tags are regularly deployed on bats.
Historically, tags with different frequencies were deployed on animals within one research study to allow for easy identification of different individuals.
The animals were then tracked, often via manual telemetry with a hand-held receiver.
Manual tracking could be conducted on foot, or using a vehicle or aircraft.
Study animals could also be tracked via a receiver attached to a stationary tower with antennae pointed in multiple directions, which could be automated to detect signals periodically or rotated manually by a researcher to detect a signal with an associated bearing.
Manual telemetry is limited by the search effort available for finding and pinpointing the radio signal, and hence faces significant challenges in tracking animals that range over long distances.

In recent years, the development of the [Motus network](http://www.motus.org) has allowed for much more widespread use of coordinated automated radiotelemetry for tracking of wide-ranging and/or migrating bats.
This system relies on coded radio transmitters which all operate on one of two common frequencies, but which emit unique ID codes to identify different individuals.
Signals from the tags are received by a network of automated radiotelemetry stations consisting of antennas, a receiver, a power source, memory storage, and sometimes data transmission infrastructure.
Telemetry stations can be deployed on land, on coastal locations, or on offshore infrastructure, including ocean buoys and offshore wind turbine platforms.
Advantages of this system include that tags are small and stations deployed by one research group can detect passage of animals by other researchers operating in the same network, allowing for development of a widespread network with more likelihood of detecting wide-ranging study animals.
This system also has the distinct advantage over manual telemetry that signals can be monitored for continuously.
Motus system technology has limitations, including limited range of some telemetry stations (typically 15 km) and, in most cases, an ability to determine only general proximity or bearing from the station rather than precise location.
Efforts to improve triangulation capabilities are underway.
Offshore wind developers are including deployment and maintenance of Motus stations as part of wildlife monitoring plans developed for review by BOEM and USFWS.
While these stations are being deployed primarily to support avian studies, they can also benefit bats.
Motus stations in the U.S.
Atlantic are coordinated through the [Atlantic Offshore Motus Project](https://motus.org/groups/atlantic-offshore-wind/).

Tag battery life and retention on the bat can be limited, reducing the length of time that individual bats are successfully tracked via this system.

At present, other types of tags, including geolocators, GPS dataloggers, and satellite tags are not regularly deployed on bats in the RWSC Study Area.
Satellite tags are currently too heavy to be placed on the bat species that occur along the Atlantic Coast of the United States.
GPS dataloggers are only practicable for species that regularly return to the same roost, where the animal can be recaptured.
They have been used in studies of the Florida bonneted bat [@webb2018], one of the largest bats on the Atlantic Coast, but other species are not as large or not as predictable in roost location.
Geolocators require exposure to daylight to function, which is not necessarily available in bat roosts.

### Banding and PIT Tags

**Capture-mark-recapture** studies can be used to assess longevity and survival of bats.
While bird banding is a very common practice for birds of all sizes, bat banding is less common.
Banding of bats (on the forearm, rather than the leg) is carried out by some researchers, but there are concerns that this practice could result in injuries to the animal (e.g., see [@lobato-bailón2023]).
The USFWS has convened a working group to study this issue in bats and come up with recommendations.
PIT (passive integrated transponder) tags are also used on bats in some instances and have good retention rates (e.g., see [@vanharten2021]).
These tags are implanted into the animal using an injector.
These types of identification systems are most useful in situations where an animal is expected to return to a given site where it may be easily captured, such as maternity colonies or hibernacula.

### Bat-Turbine Interaction & Collision Detection Systems

On turbine platforms, turbine nacelles, or other offshore infrastructure, **cameras** can be used to record bat presence and behavior in the vicinity of turbines, which can inform when and where animals are present in portions of the rotor-swept zone and document bat interactions with turbines, including roosting, attraction, micro-avoidance, lack of response, or collisions.
Cameras differ in their mode of action, resolution, and the frequencies of electromagnetic radiation they use, from conventional cameras that operate in the visual range, to so-called “infrared” cameras that operate in the near infrared range, to so-called “thermal” cameras that operate in the far infrared range.
The information provided by continuously operating cameras is unique and of great value to bat-offshore wind research.
However, many of these systems are expensive at present and often only deployed at one or a few turbines in a study area.
The field of view of a particular camera is often not sufficient to encompass the full rotor-swept zone.
The extent to which these technologies can be counted upon to operate continuously in the harsh offshore environment is currently being evaluated.

At onshore wind facilities, **carcass surveys** are commonly used to document mortality and estimate fatality rates for a variety of bat species that collide with wind turbines.
Offshore, carcasses of individuals can be expected to fall into the ocean in most instances and so **collision detection systems** are needed.
Collision detection systems may incorporate visual range, thermal, or infrared cameras as described above [@happ2021a], as well as acoustic detectors, radar systems, and/or accelerometers for impact detection.
Over a dozen multi-sensor systems for documenting collisions and other bat interactions with wind turbines are under evaluation or currently in use at wind facilities [@dirksen2017; @nrel2022], and at least three have been deployed on offshore turbines [@lagerveld2020; @markdesholm2003; @tjørnløv2023; @willmott2023].
Efforts are currently underway at land-based wind facilities to develop, improve, and validate collision monitoring technologies.
At present, validation activities are limited to the terrestrial environment, where results can be compared with carcass searches.
The development of new and emerging technologies in this category can be tracked using the [Wind Energy Monitoring and Mitigation Technologies Tool](https://tethys.pnnl.gov/wind-energy-monitoring-mitigation-technologies-tool).

### Tissue Sampling

There are a range of **tissue sampling** methods from live-caught bats, or their feces, which provide a variety of information about individuals’ migratory status, diet, and health, as well as population-level genetic structure.
These can include collections of blood, hair, wing membrane, and fecal matter, to variously conduct stable isotope analysis, physiological analyses, diet assays, detection of *Pseudogymnoascus destructans* (the fungus responsible for WNS), genetic analyses, or others.

### Incidental Observations

**Incidental observations** can also provide useful information about species presence and behavior, particularly for bats, which are infrequently observed at sea.
These observations have in some cases been collected via literature review [@pelletier2013].
**At-sea aerial and boat-based surveys for seabirds** have in some cases recorded bat activity offshore on an incidental basis [@hatch2013].

## Research Themes: Bats and Offshore Wind in the U.S. Atlantic 

Research needs for offshore wind development and bats are centered around two common themes.
First, there is a need to measure, estimate, model, or otherwise assess the scale of impacts of offshore wind development on bats, in order to determine whether impacts are significant at a subpopulation or population scale.
Second, there is a need to understand how to address any impacts that may occur via effective mitigation.
In the context of this chapter, “mitigation” is used broadly, as defined by the Council on Environmental Quality (CEQ) National Environmental Policy Act (NEPA) regulations.
Thus, mitigation in this context includes:

-   **Avoiding the impact** altogether by not taking a certain action or parts of an action.
    This could include siting wind facilities in areas expected to have low bat activity [@usfws2012].
    However, post-construction mortality is not strongly correlated with pre-construction bat activity [@hein2013].
    If bat activity decreases with distance from the coast, siting turbines further from shore could be an avoidance strategy, but not enough is known at this time to determine where to site offshore wind facilities to reduce impacts to bats.

-   **Minimizing impacts**.
    This could include curtailing wind turbine operations during periods of high bat activity (e.g., low wind speed nights) so as to reduce the risk of collision fatalities, a practice determined to be effective at land-based wind facilities [@adams2021; @whitby2021].
    Minimizing the impacts on-site could also include use of deterrent technologies, if deemed effective.
    These technologies continue to be developed and evaluated at land-based wind facilities [@hein2021].
    In some studies, individual technologies have reduced overall bat fatalities (e.g., see [@hein2021; @romano2019; @schirmacher2020; @weaver2020]); however, no deterrent has shown consistent reductions in fatalities of eastern red bats, the most commonly detected species offshore [@solick2021].

-   **Rectifying the impact** by repairing, rehabilitating, or restoring the affected environment.
    For example, this could include placing artificial roosting habitats [@mering2014] or creating snags in areas where maternity roost trees were cut to make way for a transmission corridor.

-   **Reducing or eliminating the impact** over time by preservation and maintenance operations during the life of the action.

-   **Compensating for the impact** **off-site**.
    For example, this could include preserving foraging habitat, maternity roost sites, or hibernacula.
    As stated above, effective off-site compensatory mitigation techniques for migratory tree bat mortality have not been evaluated.

The goal of mitigation measures could be to meet regulatory requirements to negate or offset any negative impacts of offshore wind development, or to meet voluntary goals of providing a net benefit to the species.

From the perspective of a regulator, conservationist, or offshore wind developer, the progress of research would ideally proceed from development of accurate and cost-effective technologies for wildlife monitoring, standardized systems for data collection and analysis, and understanding of baseline conditions, moving then to evaluation of impacts and mitigation strategies, and finally to widespread development of offshore wind in the context of implementation of effective mitigation measures.
However, given the rapid pace of offshore wind development [@u.s.departmentofenergy2023a], this slow and measured progression is not a realistic timeline.
Rather, multiple areas of research will need to be advanced simultaneously.
In the meantime, regulators must necessarily rely on the best available science in assessing potential risks to protected and vulnerable species.
Tools must continue to be developed to help inform these efforts.
While many conservationists prefer focusing on earlier steps in the mitigation hierarchy [@arlidge2018], such as avoidance, the reality is that the impacts of offshore wind development will not be fully evaluated until many hundreds of turbines are installed.
This suggests that effective on-site and off-site mitigation measures will also need to be an early focus, because once turbines are in the water, they are unlikely to be removed or fully turned off.
On-site mitigation may be the most viable strategy for conserving migratory tree bats.

Given this context, important science and research topics related to bats and offshore wind development include the following:

-   **Developing structures and methods to effectively and collaboratively conduct and share scientific research**.
    This includes coordination, planning, collaboration, the standardization of data workflows, and development of improved data collection and dissemination methods.

-   **Understanding baseline conditions of bat occurrence, activity, and movements offshore.** This includes assessing species occurrence and relative activity of bats over different areas of the ocean, with particular attention towards whether relative bat activity declines over a gradient from coastal to offshore areas.
    This also includes documenting characteristics of offshore flights, including timing (time of year, time of night), relationships to meteorological conditions, flight speed, and differences across species, sexes, or ages.
    These types of data have the potential to inform mitigation efforts.
    Because of the rapid pace of wind development compared to the pace of data collection, and because it is possible that attraction will lead bats to visit offshore lease areas more frequently once turbines are installed, near-term siting decisions are unlikely to be made based on collection of baseline data.

-   **Determining if patterns of bat occurrence, activity, and movements change after construction of offshore wind facilities.** This includes continuing surveys of bat occurrence and activity post-construction to understand if patterns change and continuing to document characteristics of offshore flights.
    Post-construction studies of this kind may help elucidate whether, and to what degree, attraction to turbines is occurring, and whether siting could be an effective mitigation strategy for future wind projects.

-   **Assessing collision risk at offshore facilities.** Until validated and effective collision detection methods are widely available, proxies are necessary to assess collision risk.
    For bats, acoustic activity, particularly recorded at nacelle height in conjunction with information regarding turbine operational status, may be the best indicator of potential collision risk [@peterson2021].
    Assessing bat activity at turbine nacelle height relative to timing, meteorological conditions, turbine characteristics, turbine operational status, and species is an important research goal.
    (Tracking data may also provide information about movements of non-echolocating bats.) Turbine-mounted cameras and multi-sensor collision detection technologies may be able to provide actual measures of collision risk and fatalities.
    These data can help in understanding the relative risks to bat populations posed by collisions offshore as compared to fatalities at land-based wind facilities and other threats.

-   **Designing and evaluating on-site minimization strategies.** Assessments of the conditions associated with heightened collision risk (previous bullet) can inform design of efficient, “smart” curtailment strategies for bats, if these methods are deemed necessary to avoid population-level impacts to bats.
    If determined to be effective in the terrestrial environment, deterrents could also be tested offshore.

-   **Evaluating off-site compensatory mitigation strategies.** If on-site mitigation measures are deemed insufficient or are cost-prohibitive, off-site mitigation measures could be considered. 
    However, these measures would need to be evaluated carefully to determine if they are realistic and adequate to address negative impacts.

A database of specific research questions related to bats and offshore wind is available through the [U.S. Atlantic Offshore Wind Environmental Research Recommendations Database](https://tethys.pnnl.gov/atlantic-offshore-wind-environmental-research-recommendations)**.**

## Regional-scale Ongoing, Pending, and Recommended science actions in the U.S. Atlantic for Bats and Offshore wind

This section of the Science Plan discusses science actions recommended to further the scientific understanding of effects of offshore wind infrastructure on bats and to address mitigation strategies in the context of identified impacts.

This section is structured by the type of science action, including:

-   Data management

    -   Standardization of data collection, analysis, and reporting

    -   Historical data compilation

-   Data analysis

    -   Meta-analysis and literature review

    -   Model development and statistical frameworks

    -   Optimizing research, monitoring, and mitigation

-   Technology advancement

-   Field data collection and analysis

Recent, current, and pending science activities are discussed throughout as necessary to provide a context for current recommendations.
These and other recent activities are tracked in the [RWSC Offshore Wind & Wildlife Research Database](https://database.rwsc.org/).

Other resources for learning about recent and on-going offshore wind-wildlife research include the [Tethys Knowledge Base](https://tethys.pnnl.gov/knowledge-base), a Pacific Northwest National Laboratory database, which houses publications, reports, and presentations relevant to offshore wind, and the [Tethys Offshore Wind metadata](https://tethys.pnnl.gov/offshore-wind-metadata), which compiles information on environmental monitoring conducted at offshore wind energy projects around the world.
The New York State Energy Research and Development Authority Environmental Technical Working Group ([NYSERDA E-TWG](https://www.nyetwg.com/)) hosts [State of the Science Workshops on Wildlife and Offshore Wind Energy](https://www.nyetwg.com/past-workshops), which provide an opportunity for researchers to present and discuss updates on the state of knowledge regarding wildlife and offshore wind energy development and to promote collaboration and regional coordination.
Both the E-TWG (<https://www.nyetwg.com/webinar-library>) and Tethys (<https://tethys.pnnl.gov/environmental-webinars?content=467>) have webinar libraries regarding environmental issues and offshore wind.

### Data Management: Data Collection, Processing, Housing, and Compilation

This section addresses data collection, processing, and housing for the types of data collected as part of studies to inform potential impacts of offshore wind development on bat species in the Northwest Atlantic.
Section 6.1.1 summarizes recommended data standards and recommended science actions relevant to each data type.
Section 6.1.2 provides detail on current gaps in data infrastructure.
Section 6.1.3 provides detail on current and recent efforts related to recommended data standards and infrastructure.

#### Data Standards & Recommended Science Actions

Understanding bat activity around offshore wind facilities and regionally along the U.S.
Atlantic Coast will require close coordination among researchers, state and federal agencies, and industry.
The Bird & Bat Subcommittee wishes to work with individuals and entities who collect data relevant to bat-offshore wind research to ensure that data are collected and stored in consistent formats that allow comparisons and pooling across individual projects in the RWSC Study Area.
This standardization is intended to support regional-scale assessments, data products, and tools (e.g., NABat occupancy and abundance estimates; evaluations of collision risk relative to wind facility, temporal, and environmental characteristics).

In order to support these efforts, the Bird & Bat Subcommittee recommends:

-   Maintenance of an up-to-date resource list of recommended standard databases, data repositories, guidelines, and protocols for use by all data collectors. 
    The current recommended resources are detailed in the table below.

-   Development of standard language for inclusion in funding and contract documents to encourage or require the use of recommended resources.

-   Establishment of an Offshore Bat Working Group to address gaps in existing databases (detailed in the table below), including development of recommended protocols/standards where absent, suggestions for the structure/content of new databases, and identification of pilot study parameters where too little is currently known to provide specific methodological guidance.
    This Working Group has recently been established and, as a first step, will address methodological recommendations and pilot study parameters for passive acoustic detector deployment on offshore infrastructure.

-   Establishment of data sharing frameworks to appropriately manage access to sensitive industry-collected datasets necessary for research (e.g., acoustic data collected on offshore wind turbines, bat-turbine interactions, and collision data; associated turbine status and local meteorological conditions).

-   Identification, solicitation, and compilation of historic data into recommended databases to inform baseline understanding of bat distributions in coastal and offshore areas of the U.S.
    Atlantic Coast.
    In some cases, this may require re-formatting and QA/QC procedures to ensure species codes, units, and other metadata are entered consistently.

**The following table lists the existing centralized or accepted repositories and standards that are recommended for use in bat data collection, as well as identifying data types for which no or limited data management capacity (i.e., standard repositories and guidance) currently exists.**

+----------------------------------------------------------------------------------------------------------+----------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Methods and data types**                                                                               | **Database/Repository**                                        | **Guidance/Standards**                                                                                                                                                                                                                                                                                                                            | **Recommendations**                                                                                                                                                                                                                         |
+----------------------------------------------------------------------------------------------------------+----------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Acoustic data (passive or active), including both records of identified species and raw acoustic files   | North American Bat Monitoring Program (NABat)                  | -   Utilize [A Plan for the North American Bat Monitoring Program](https://www.fs.usda.gov/treesearch/pubs/48442) for survey protocols and field study guidance.                                                                                                                                                                                  | -   *Develop offshore-specific protocols for passive and active acoustics.*                                                                                                                                                                 |
|                                                                                                          |                                                                |                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                             |
| Bat observations                                                                                         |                                                                | -   Visit [NABat Resources](https://www.nabatmonitoring.org/resources) for detailed guidance on data preparation, processing, uploading, and QA/QC procedures.  NABat also provides a [grid-based offshore sampling frame](file:///Users/christianlaspada/Downloads/NABat%20also%20provides%20a%20grid-based,%20offshore%20sampling%20frame).     | -   *NABat has confirmed that it can incorporate contemporaneous local meteorological data and turbine operational status with bat acoustic detection data.*                                                                                |
|                                                                                                          |                                                                |                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                             |
| (colony and roost counts, capture records, incidental observations)                                      |                                                                | -   *Development of offshore-specific protocols for passive and active acoustics are recommended.*                                                                                                                                                                                                                                                | -   *Solicit historical acoustic data from coastal and offshore studies for incorporation into NABat.*                                                                                                                                      |
|                                                                                                          |                                                                |                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                             |
|                                                                                                          |                                                                | -   *NABat has confirmed that it can incorporate contemporaneous local meteorological data and turbine operational status with bat acoustic detection data.*                                                                                                                                                                                      | -   *Determine if Northwest Atlantic Seabird Catalog incidental observations of bats can be easily transferred to NABat.*                                                                                                                   |
+----------------------------------------------------------------------------------------------------------+----------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Automated VHF/UHF tagging/tracking studies                                                               | [**Motus Wildlife Tracking System**](https://motus.org/about/) | -   Utilize [Monitoring Protocols and Guidance for Automated Radio Telemetry Studies at Offshore Wind Farms](https://motus.org/groups/atlantic-offshore-wind) for study design and data collection                                                                                                                                                | -    *Improve access to historical offshore bat Motus data through a systematic effort to reach out to relevant past projects and request public access to data if not already available.*                                                  |
|                                                                                                          |                                                                |                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                             |
|                                                                                                          |                                                                | -   [Motus Wildlife Tracking System resources](https://motus.org/resources/) provide extensive additional documentation on data collection, upload, and analysis                                                                                                                                                                                  | -   *Develop guidance regarding deployment, metadata, and data storage of local meteorological data associated with telemetry receiver stations to inform timing of bat movements and behavior relative to local weather conditions.*       |
+----------------------------------------------------------------------------------------------------------+----------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| Other tagging/tracking studies                                                                  | [**Movebank**](https://www.movebank.org/)                                                                                                                          | -   Follow interim [USFWS Guidance for Coordination of Data from Avian Tracking Studies](https://rwscorg.sharepoint.com/:b:/s/BirdandBatSubcommittee/EWiyjaGje4tOsn7YjpJ13P8B8jQRQP9b2nUt9y4dRwpV6g?e=Ew3LOO)               |                                                                                                                                                      |
|                                                                                                 |                                                                                                                                                                    |                                                                                                                                                                                                                             |                                                                                                                                                      |
| (e.g., standard VHF, GPS dataloggers (if used))                                                 |                                                                                                                                                                    | -   [Movebank User Manual](https://www.movebank.org/cms/movebank-content/manual) provides step-by-step guidance on adding, managing, sharing, and accessing tracking data                                                   |                                                                                                                                                      |
+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| Carcasses and tissue samples                                                                    | [**Renewables-Wildlife Solutions Initiative**](https://www.usgs.gov/centers/forest-and-rangeland-ecosystem-science-center/science/renewables-wildlife-solutions)   | -   Report fatalities to [USFWS](https://ecos.fws.gov/imr/welcome)                                                                                                                                                          | -   *Identify funding and develop additional capacity for carcass and tissue sample storage.*                                                        |
|                                                                                                 |                                                                                                                                                                    |                                                                                                                                                                                                                             |                                                                                                                                                      |
|                                                                                                 |                                                                                                                                                                    | -   Contact the [Renewables-Wildlife Solutions Initiative](https://www.usgs.gov/centers/forest-and-rangeland-ecosystem-science-center/science/renewables-wildlife-solutions) (RWSI) to submit samples                       |                                                                                                                                                      |
|                                                                                                 |                                                                                                                                                                    |                                                                                                                                                                                                                             |                                                                                                                                                      |
|                                                                                                 |                                                                                                                                                                    | -   *Note that RWSI has limited capacity but is currently accepting samples.*                                                                                                                                               |                                                                                                                                                      |
+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| Observed interactions with wind turbines, collisions, fatalities                                | No central repository                                                                                                                                              | No identified standard protocols                                                                                                                                                                                            | -   *Identify goals and pilot study recommendations for collision detection technologies.*                                                           |
|                                                                                                 |                                                                                                                                                                    |                                                                                                                                                                                                                             |                                                                                                                                                      |
| (e.g., via turbine-mounted cameras, impact detection systems)                                   |                                                                                                                                                                    |                                                                                                                                                                                                                             | -   *Develop a database and standard data collection protocols.*                                                                                     |
+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| Radar/lidar studies                                                                             | No central repository                                                                                                                                              | No identified standard protocols                                                                                                                                                                                            | -   *Identify goals and pilot study recommendations for radar/lidar studies.*                                                                        |
|                                                                                                 |                                                                                                                                                                    |                                                                                                                                                                                                                             |                                                                                                                                                      |
|                                                                                                 |                                                                                                                                                                    |                                                                                                                                                                                                                             | -   *Develop a database and standard data collection protocols.*                                                                                     |
+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| Large raw file types (e.g., high-definition aerial photos, thermal video, raw acoustic files)   | No central repository                                                                                                                                              |                                                                                                                                                                                                                             | -   *Retention of large, raw file types could allow for future QA/QC and re-evaluation with updated analysis or automated identification tools.*     |
|                                                                                                 |                                                                                                                                                                    |                                                                                                                                                                                                                             |                                                                                                                                                      |
|                                                                                                 |                                                                                                                                                                    |                                                                                                                                                                                                                             | -   *Development of a data repository, with standard protocols and data-handling procedures, is recommended as a cross-taxa action.*                 |
+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+

#### Current Gaps in Database Infrastructure

There are a number of identified gaps in infrastructure to support standard data collection and workflows.
The major gaps identified for bats are as follows:

##### Collision & Bat-Turbine Interaction Database

As discussed in Section 4, some incidental collision fatalities may be identified during visits to offshore turbine platforms.
Currently, there is no standard, cost-effective way to rigorously monitor for collisions offshore.
However, unimodal and multi-modal systems to document bat interactions with wind turbines, including behavior, micro-avoidance, and collisions, are being developed and validated at land-based wind facilities and pilot-tested on offshore turbines.
Where fatalities are only documented in an incidental fashion, fatality data may be of limited value, but are nevertheless important, given our limited scientific understanding of potential offshore impacts.
As technologies allow for collection of data in a more scientific and rigorous fashion, collision, micro-avoidance, and other turbine interaction data will be critical for evaluating impacts of offshore wind and (if necessary) identifying effective mitigation strategies.
The need for a designated database and availability of detailed data for scientific analysis will hence become crucial.

There is some sensitivity regarding reporting of fatality and collision information, as well as sharing of videos and photographs of bat interactions with wind energy infrastructure.
Reporting of these data is related to regulatory requirements under federal law, and public reporting of collision data could result in negative publicity.
In addition, important covariates to use in analyses include potentially sensitive business information, like wind speed and the operational status of the turbine.
Some wind companies consider these items to be proprietary information, although practices differ among companies and are dependent on company policies, permitting and development stage, and the granularity/specificity of the data provided.

Basic fatality information is reported to the U.S.
Fish & Wildlife Service, but otherwise, no central scientific database is currently available for the collection of fatality information, or more generally for the disposition of video, photo, radar, acoustic, or impact detection data related to bat behavior, avoidance, and collisions associated with offshore wind infrastructure.
In the terrestrial environment, there are two databases which could inform development of an offshore database, Nature Counts and AWWIC.
[The Nature Counts](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwicu-HG9KOCAxUGjokEHUgHBlcQFnoECBEQAQ&url=https%3A%2F%2Fwww.naturecounts.ca%2F&usg=AOvVaw3jXdmAAIWe0ZoJp-K-GKBJ&opi=89978449) database collects bat fatality information from Canadian land-based wind facilities.
The [American Wind Wildlife Information Center](https://rewi.org/about-us/our-work/awwic/) (AWWIC) collects post-construction fatality data from U.S., land-based wind facilities.
Database managers work with wind industry collaborators to compile both publicly available and privately contributed fatality data, including important covariates (e.g., effort, methodology, meteorological conditions), and to allow for the analysis of these data by Renewable Energy Wildlife Institute (REWI) staff, as well as other researchers. 
Careful limitations on data sharing and requirements for sharing aggregated data ensure that no data from private sources could lead to identification of individual wind facilities.

One challenge associated with the AWWIC database is that it includes tailored non-disclosure agreements negotiated with each wind facility operator individually, and new data analyses and studies must often be negotiated with data contributors.
An offshore collision fatality database for bats should instead include standard protocols for how data are collected, entered, and reported, including which covariates are necessary for interpretation.
The database should also include clear data sharing standards to allow access for federal regulators and simplify sharing of data with outside researchers for analysis and synthesis, while addressing developer concerns regarding data security, confidentiality, and needs for data aggregation in reporting.

##### Tissue Sample Repository 

There is an identified need for a tissue repository to store tissue samples from bats, including carcasses of bats recovered from offshore wind facilities.
These remnants are much less likely to be found at offshore facilities than at land-based facilities, since carcasses are most likely to fall into the ocean and not be recoverable and regular carcass searches are not likely to be proscribed.
However, carcasses of bats may occasionally be recovered on offshore wind facility infrastructure incidentally.
In addition, tissue samples may be collected from bats in offshore or coastal areas for various research purposes, including genetic, physiological, stable isotope, or disease dynamics studies. 
If not destructively sampled for analysis as part of the initial study, these samples could be stored for later use and to benefit future analyses.

At present, there is one repository which accepts bat carcasses recovered at renewable energy facilities.
The [Renewables-Wildlife Solutions Initiative](https://www.usgs.gov/centers/forest-and-rangeland-ecosystem-science-center/science/renewables-wildlife-solutions) (RWSI), organized by Todd Katzner (USGS) and Mark Davis (University of Illinois), has established a successful system for collecting and tracking bat samples from wind facilities, including sample storage and an Access database.
The organizers are open to accepting samples and carcasses from offshore wind facilities.
However, this small-scale repository could easily be overwhelmed if all bat carcasses and tissue samples currently collected or stored by state agencies, federal agencies, wind developers, and environmental consultants were to suddenly begun to be shipped to these locations.

USGS researchers, working with colleagues, have mapped out a hierarchical structure for a database that could allow for the tracking of carcasses and tissue subsamples throughout the country.
There has also been discussion of logistical needs – for example, the establishment of regional collection centers to reduce transportation/shipping challenges for frozen samples.
As of 2023, this plan has not been implemented.
While development of a tissue sample repository would be of great value to renewable energy-wildlife research, it is likely of lower priority for offshore wind facilities where, as noted, collection of carcasses and tissue samples is likely to occur less frequently.

##### Raw File Data Repository

In addition to databases, there is a need for a data repository to store raw data with large file types – e.g., radar data, thermal video, and raw acoustic files.
Derived data from these types of files should be made available in relational databases as relevant; however, the raw data should also be retained in a central location for quality control, re-analysis, and future re-evaluations with better tools.
For example, future machine learning advances may allow for faster and more effective automated identification of bat species in acoustic files.

The NABat database currently accepts raw acoustic files (field-collected files that have not auto-classified or manually identified to species) in addition to processed data with temporally and spatially located species identifications, but if this platform were to accept large volumes of acoustic files, it would quickly be overwhelmed.

#### Current and Recent Efforts

**Motus.** Automated telemetry data collected via the Motus Wildlife Tracking Network is automatically stored in the Motus system.Hence, historical data for bats are naturally stored alongside data collected from current and recent projects.
Birds Canada staff have also made efforts in recent years to solicit tag metadata associated with tag deployment from past projects where not previously recorded in the Motus system.

**NABat.** As noted above, the NABat sampling grid has been extended offshore.
The NABat database can accept presence/absence bat acoustic data collected from offshore wind turbines, associated infrastructure, meteorological towers, and other offshore, island, or coastal locations (e.g., offshore weather buoys, lighthouses, tree-mounted units on islands).
The NABat database also allows for inclusion of bat acoustic data collected as part of boat-based surveys.
In addition, any bat observation data types may also be submitted to the database.

### Data Analysis & Planning

Data analyses and summaries should inform where new data collection is needed, characterize bat activity and distribution patterns in coastal and offshore environments, and/or address the efficacy of monitoring or mitigation strategies.

#### Recommended Science Actions

In order to address near-term needs, the Bird & Bat Subcommittee recommends:

-   As data are collected, analysis to evaluate collision risk and relate offshore bat activity and collision risk to meteorological conditions, turbine characteristics, and turbine operational status.
    (If mitigation is deemed necessary in the future, these analyses could be used to design and implement efficient operational mitigation measures, such as curtailment.)

-   Contributions of new and historical data to the NABat database to allow for the extension of seasonal occupancy and abundance maps/estimates offshore.

-   Development of a framework to evaluate population-scale risks of offshore collision mortality to bats, in a context of great uncertainty.
    Identification of the data needed to inform and validate models.

#### Current and Recent Efforts

**Offshore Bat Activity.** As referenced above, Donald Solick and Christian Newman at EPRI recently published a literature review [@solick2021] summarizing the state of knowledge regarding bat occurrences offshore, particularly with respect to offshore wind development.

**Data Gaps Analysis**.
[Project WOW](https://offshorewind.env.duke.edu/), a Wildlife and Offshore Wind study led by Duke University, with collaborators, is performing a data gaps analysis to understand where sufficient data exist to generate meaningful estimates of likely impacts, and where they do not.
This analysis will be based on a quantitative scoring of literature, based on species names and taxa.
For a preliminary summary of this analysis, see [Meeting 4 in the public RWSC files](https://rwscorg.sharepoint.com/:b:/s/BirdandBatSubcommittee/EfR6tZUhTTFDiKP_l-tSNPABmt9dRbouoFnsxkcxurIGJA?e=OBpxXh).

**Summary of Research Priorities**.
The [NYSERDA E-TWG Regional Synthesis Workgroup](https://www.nyetwg.com/regional-synthesis-workgroup) was organized to inform and provide interim guidance for regional-scale research and monitoring of offshore wind energy and wildlife in the eastern United States.
With technical support from BRI, the group compiled a [database](https://tethys.pnnl.gov/atlantic-offshore-wind-environmental-research-recommendations) of research needs and data gaps from existing sources, including published, peer-reviewed synthesis papers, State of the Science Workgroups, federal and state agency efforts, and previous E-TWG Specialist Committees, etc.
The database was designed to synthesize existing data gaps and research needs so that researchers and funders can easily access, sort, and further prioritize topics.
The database specifies focal taxa, spatial scale, and other information relating to each priority research topic.
The Workgroup also drafted written guidance, including definitions of common terminology to support regional communications, general suggested criteria for prioritization of regional research topics, and general recommendations on study design and data transparency for regional-scale research efforts.
