# Sea Turtles {#sec-append-st}

Note: Scientific and ecological terminology and agency/organization acronyms are used throughout this chapter.
A [List of Definitions and Acronyms](#Definitions_and_Acronyms) is included at the end of the chapter.

## Sea turtle species in the RWSC study area

All sea turtles in the U.S. are federally protected by the Endangered Species Act (ESA) and most states adopt the federal status for management purposes.
In the U.S., sea turtles in water (foraging, migrating, oceanic dispersal, mating, disentanglement and stranding response) are managed federally by NOAA Fisheries and on land (nesting, rehabilitation and captive display) by the U.S.
Fish and Wildlife Service.

Sea turtles have a unique life history.
They are generally long lived and, besides incubating eggs and emergent hatchlings, only adult females spend a brief period on beaches while nesting.
For all six species found in U.S. waters combined, sea turtles can be found in the northwest Atlantic from shallow coastal waters, including brackish and inshore bays, sounds and river mouths to offshore pelagic waters.
Collectively sea turtles may be the ESA listed species most commonly affected by offshore wind.
They range in size from \<10cm Kemp’s ridley hatchlings to \>2m adult leatherbacks.
In the oceanic dispersal stage, they feed in surface waters often associated with floating algae such as sargassum, as larger juveniles-adults, diets range from herbivorous adult green turtles to leatherbacks feeding primarily on gelatinous prey to Kemp’s ridley and loggerhead turtles that feed primarily on benthic crustaceans and mollusks.

In the U.S.
Atlantic, sea turtles are migratory in temperate and northern sub-tropical areas and may live in relatively static or seasonally shifting home ranges in sub-tropical and tropical waters depending on the species and habitat.

On the U.S.
Atlantic coast, loggerhead and green turtles regularly nest from Florida to North Carolina.
Loggerheads nesting in the U.S. belong to the NW Atlantic DPS, and greens belong to the N Atlantic DPS. Small numbers of loggerheads annually nest in southeastern Virginia and occasional nests of both species have been reported north of Virginia.
In the same region, leatherback turtles nest primarily in [Florida](https://myfwc.com/research/wildlife/sea-turtles/nesting/nesting-atlas/) and numbers have fluctuated at index beaches but have generally increased since the late 1980s.
Occasional Kemp’s ridley and hawksbill turtles nest on the U.S.
Atlantic coast, hawksbills in Florida and Kemp’s ridleys from FL to VA.
Extralimital nesting outside of known nesting areas have been documented for all turtle species.

There is no parental investment after a nest is laid and hatchlings emerge from nests, make their way to the water and swim frenetically until they reach offshore habitat where they spend several years to over a decade in an oceanic dispersal stage.
For northwest Atlantic green and loggerhead turtles, we believe this life stage is spent primarily in the Gulf Stream and Sargasso Sea.
Little is known about NW Atlantic leatherbacks in the oceanic dispersal stage.
Most Kemp’s ridleys nest in the Gulf of Mexico and some of these turtles exit the Gulf and are dispersed into the northwest Atlantic most likely via the Gulf Stream.

Healthy juvenile through adult life stage sea turtles are considered ‘surfacers’ instead of ‘divers’ meaning that most of their time is spent below the surface, and, with a couple of exceptions, they only come to the surface briefly to breathe [@kooyman1989].
One exception to this mostly subsurface lifestyle is basking behavior which has been exhibited by loggerhead turtles on the outer continental shelf, mostly in the spring months as they are migrating north to summer foraging areas [@hochscheid2010].
Post-hatchling turtles in the dispersal phase [@phillips2022] also appear to spend most of their time in the top several meters of the water column.

Movement from the oceanic dispersal life stage to the juvenile-adult neritic life stages occurs at different age and size for loggerhead, green, and Kemp’s ridley turtles.
Little is known about leatherback distribution from hatchling to sub-adult life stages.

Because their behavior and distribution varies among life stages, the Science Plan will address research priorities by species, life stage and subregion (Table 1).
Thus, for the remainder of this document, sea turtle life stages will be defined as:

[Egg/hatchling]{.underline} – for the conservation purposes of the RWSC, we are combining incubating egg in nests with hatchling emergence and swimming frenzy; beach phase including incubation, emergence & swim frenzy that results in arrival in offshore pelagic habitat.

[Juvenile dispersal]{.underline} – ‘lost years’ life stage, post-hatching dispersal where turtles are near the surface, in open water.
Off the U.S.
Atlantic coast these small turtles are thought to be distributed primarily in the Gulf Stream and Sargasso Sea.
Little is known about the dispersal life stage for leatherback turtles, and this life stage primarily occurs in the Gulf of Mexico for Kemp ridley turtles [@phillips2022].

[Juvenile-subadult]{.underline} (post dispersal)– foraging phase of sexually immature turtles (neritic habitat for Kemp’s ridley, green and loggerhead turtles in the NW Atlantic; pelagic and neritic for NW Atlantic leatherbacks), characterized in some species and subregions by north/south and/or inshore offshore seasonal migrations or seasonally shifting home ranges.

[Adult]{.underline} – sexually mature; loggerheads nest in the Central Atlantic and Southern Atlantic subregions, green and leatherback turtles almost exclusively in the Southern Atlantic, occasional nests of all species are found outside normal nesting areas.
Females of most populations have an inter-nesting period of \>1 year.
Non-breeding and post-breeding/nesting adults may behave seasonally much like juveniles and sub-adults.
Tracking data suggest foraging occurs outside of nesting areas in post-nesting females.

Table 1: Sea turtle species and life stage covered by this plan by subregion (UN=unknown, NA=not applicable, Winter=Jan-Mar, Spring=Apr-Jun, Summer=Jul-Sep, Fall=Oct-Dec).

Gulf of Maine

|               |                |                    |                        |                       |           |                     |                       |
|---------|---------|---------|---------|---------|---------|---------|---------|
|               |                | **Life stage(s)**  |                        |                       |           |                     |                       |
| **Species**   | **ESA Status** | **egg/ hatchling** | **juvenile dispersal** | **juvenile-subadult** | **adult** | **nesting females** | **Annual occurrence** |
| leatherback   | endangered     | NA                 | UN                     | ü                     | ü         | NA                  | common                |
| loggerhead    | threatened     | NA                 | NA                     | ü                     | ü         | NA                  | common                |
| Kemp's ridley | endangered     | NA                 | NA                     | ü                     | NA        | NA                  | rare                  |
| green         | threatened     | NA                 | NA                     | ü                     | NA        | NA                  | rare                  |

### Focal species and notable recent trends

Because there are only five sea turtle species that can be found off the United States Atlantic coast: 1) [loggerhead](https://www.fisheries.noaa.gov/species/loggerhead-turtle#seafood) (*Caretta caretta*), 2) [green](file:///C:/Users/Susan%20Barco/Desktop/RWSC/;%20https:/www.fisheries.noaa.gov/species/green-turtle#seafood) (*Chelonia mydas*), 3) [leatherback](https://www.fisheries.noaa.gov/species/leatherback-turtle#seafood) (*Dermochelys coriacea*), 4) [Kemp’s ridley](https://www.fisheries.noaa.gov/species/kemps-ridley-turtle#seafood) (*Lepidochelys kempii*), and 5) [hawksbill](https://www.fisheries.noaa.gov/species/hawksbill-turtle#seafood) (*Eretmochelys imbricata*), the first four species, which occur consistently in the RWSC study area, are considered focal species for this chapter.
The first three species regularly nest on U.S.
Atlantic coast beaches, and the other two occasionally nest on U.S.
Atlantic beaches.
Table 1 indicates that the sea turtle species, occurrence, and life stages in the RWSC study that will be considered in this plan by sub-region.
Of the five species that occur in the NW Atlantic, the plan will cover four of them, all but hawksbill.
Sea turtles occur from inshore bays and river mouths to pelagic waters and use habitats in different ways during their life stages.
Table 2 indicates the life stage and behavioral states of the species considered under the plan as well as the estimated inshore and offshore boundaries of the plan.

### RWSC Sub-regions and regional scale sea turtle distribution

RWSC is organized by subregion along the U.S.
Atlantic coast, roughly aligned with current offshore wind development planning areas.
RWSC subregions and map are described on page 2 of [Chapter 2: Science Plan Organization](https://rwscorg.sharepoint.com/:w:/s/SubcommitteeLeads/EbuoNED_rydAskBAl58fbroB746EAi0GASy-NzLEta8pvA?e=Qdqvo7).

In this document, region wide ongoing, pending and recommended field research is briefly described, discussed and organized into one of several research themes described on pages 2-4 of [Chapter 2: Science Plan Organization](https://rwscorg.sharepoint.com/:w:/s/SubcommitteeLeads/EbuoNED_rydAskBAl58fbroB746EAi0GASy-NzLEta8pvA?e=Qdqvo7).
Details of ongoing and pending research and long-term monitoring efforts informative to the questions regarding OSW are available in the searchable [RWSC Offshore Wind and Wildlife Research Database](https://database.rwsc.org/details?recordId=recNHdvRuyx5cCeyI), and links to queries for each research project are included in the tables describing projects in the chapter.
Following regionwide field research, is discussion of field research specific to each subregion.
Following subregion field data collection discussion, are on-going, pending and recommended non-field efforts by research theme and action.
Non-field data collection actions include: 1) outreach and platforms to provide data products/results to stakeholders; 2) coordination and planning; 3) standardizing data collection, analysis, and reporting; 4) study optimization; 5) historic data collection/compilation; 6) model development and statistical frameworks; 7) technology advancement; 8) manipulative experiments, and 9) meta-analysis and literature review and are further described in [Chapter 3: Science Plan Actions](https://rwscorg.sharepoint.com/:w:/s/SubcommitteeLeads/EY-LUU7PXBdMtvTJxFO2HEoBr087P2I7oa4Q7FJBFnCQHw?e=sghdfU).

#### Regional-scale distribution information

Consistent data to capture spatial and temporal distribution is provided via survey effort.
In addition, tag, sighting, stranding and bycatch data contribute to distribution information, especially in areas and times where survey effort is limited and under conditions where turtles are not likely to be detected.
While there has been a substantial amount of survey effort conducted to detect large sea turtles in the NW Atlantic, turtle distribution and behavior is variable both within and between seasons and is likely affected directly and indirectly by a combination of environmental factors.
As such, abundance estimates should be based on multiple years and seasons of data [@noaafisheries2020].
Currently, a thorough understanding of surface availability and abundance is lacking for all species in much of the NW Atlantic.
For some species and subregions, especially sub-adult loggerheads in shelf waters of USCA through SNE subregions, availability estimates are based on relatively large data sets, but still contain some data gaps [@hatch2022].
Importantly, most recent distance sampling aerial surveys (AMAPPS) have been conducted using parameters appropriate for detecting a variety of species.
The speed and altitude at which most of these surveys were conducted prevent detection of smaller turtles (\<40cm carapace length) [@noaafisheries2020; @palka2021], and all turtle detections decrease in sub-optimal conditions, especially with increasing sea state.
Regardless of the survey effort level, substantial data gaps on sea turtle distribution and abundance exist for all species, seasons and subregions.

Efforts to develop an index of abundance and distribution using satellite tag data for loggerhead turtles by month were conducted by Winton et al. [@winton2018].
Loggerheads used nearly all shelf waters from Long Island, NY south to near the tip of peninsular FL.
In winter months, loggerhead turtles were largely south of the Virginia-North Carolina border.
This analysis was possible due to a large tag dataset with similarly programmed tags for animals captured and tagged with broad temporal and spatial variation.
Similar efforts may yield better results for other species if undertaken as a coordinated effort.

The U.S. Navy recently completed a sea turtle surface density modeling project along the U.S.
Atlantic coast from shore to the EEZ which produced estimates for the NW Atlantic for juvenile-adult stage turtles large enough to be detected from a variety of platforms [@dimatteo2022], those surveys are available as [East Coast Turtle Density Models](https://seamap.env.duke.edu/models/NUWC/EC/) on OBIS SEAMAP. Estimates of sea turtle abundance are not yet available from AMAPPS surveys.
Tagging results of loggerhead and leatherback turtles from AMAPPS surveys are available in AMAPPS reports [@palka2021].

#### Biologically Important Areas for sea turtles within U.S. Waters

Biologically important areas in the United States for NW Atlantic sea turtle species/populations have not been determined.
State space modeling applied to telemetry studies suggest that inshore and coastal continental shelf habitat are important foraging areas for loggerhead [@braun-mcneill2008; @evans2019] and Kemp’s ridley [@bean2019] turtles in the Central Atlantic and New York Bight subregions.
Work is underway through AMAPPS research to establish similar areas of importance for leatherback turtles (C. Sasso *pers comm*).
Although all established Kemp’s ridley nesting areas are in the Gulf of Mexico, the coastal and inshore waters of the NW Atlantic appear to be important foraging areas for juvenile and subadult Kemp’s ridley turtles although the contribution of this region to the population remained unclear in the 2015 status review for the species [@noaa2015].
A new proposed critical habitat designation for N Atlantic green turtles was released in July 2023 [@noaafisheries2023].
It is expected that findings will discuss the northward expansion of the species as well as increases in nesting on Southern Atlantic beaches since the previous review in 2015 [@seminoff2015].

Better understanding of biologically important in-water sea turtle habitat is needed for all species in US Atlantic waters.

## Potential effects of offshore wind on sea turtles

The subcommittee recognizes that there may be positive, negative and/or mixed impacts of offshore wind development and operation on sea turtles.
These effects may directly affect individual animals or indirectly affect them through changes to the environment, prey/predator distribution and/or changes in human activities.
Animals and populations may be impacted by multiple, cumulative, effects, some positive and some negative.

As ectothermic, mostly migratory populations in U.S.
Atlantic waters, some sea turtle population’s foraging, breeding, nesting, and migratory ranges overlap the areas proposed for offshore wind development in the Atlantic Ocean.
In addition, sea turtle species are exposed to multiple and cumulative stressors throughout their life cycles, including climate and non-climate threats [@fuentes2013; @fuentes2020].
The cumulative effect of these and other stressors are likely to create biologically significant population level responses.

There have been no studies describing the effects of construction and operation of windfarms on sea turtles, largely because most research has come from European and U.K.
waters, where sea turtles do not commonly occur.
Discussion of potential impacts of offshore wind on each sea turtle species are, therefore, based on data from other species groups or other potential stressors.
The subcommittee is concerned that this lack of knowledge for sea turtle species, which have a very different life history, compared to other species groups, plays into sea turtle risk assessments and adds potential for more unexpected results, compared to other wildlife impacted by OSW.
Without risk assessment specific to sea turtles, unidentified impacts cannot be assessed or mitigated with enhanced monitoring and adaptive management.
The subcommittee recommended exploring the use of cumulative impact assessment whereby multiple threats to sea turtles were quantified allowing for effective mitigation and restoration recommendations following the Gulf of Mexico Deep Water Horizon Oil Spill.
Love et al. [@love2017] categorized, quantified, and assessed the threats to (stressors) sea turtles to identify the most effective restoration actions for the recovery of sea turtle populations in the Gulf of Mexico.
The authors were able to quantify poor and missing information in their assessment through use of proxy and modeled data.
A similar approach to identifying sea turtle threats and quantifying the potential impact of OSW may be helpful in determining the most effective methods for assessing and addressing threats in U.S.
Atlantic waters.

OSW, like other human activities in the marine environment, will have effects on sea turtles.
Positive effects will most likely be related to reef effects of physical structures supporting turbines.
Structures are expected to attract invertebrate fouling organisms and reef/wreck fishes, which will likely attract small schooling fishes [@glarou2020].
Sea turtles have been documented around underwater structures and are likely attracted to them [@broadbent12020; @reimer2023].
These structures will also attract anglers and some commercial fishers such as pot/trap fishers which may increase the likelihood of interactions with active and discarded gear.
The most probable direct negative effects of offshore wind construction and operation are serious injury and mortality from increased vessel interaction and increase in fishery interaction because of attraction to turbines due to reef effects.
It is likely that there will be direct, indirect and/or temporary negative effects related to noise, EMF, as well as changes in prey distribution, oceanographic parameters, fishing and shipping distribution.
Other oceanographic and substrate impacts are not well understood, and impacts are yet to be determined.

Since little is known about effects of OSW on sea turtles, the subcommittee must look to studies on large marine vertebrates for comparison.
In European waters, researchers have documented avoidance and displacement effects, primarily of harbor porpoises (*Phocoena phocoena*).
These effects occurred at ranges of 10-26 km from the whole footprint of offshore windfarms during construction [@benhemmalegall2021; @brandt2018; @dähne2013a; @graham2019; @graham2023].
All of these studies indicate that the distance and duration of avoidance is related to received noise, which is further influenced by source level, sound propagation conditions (environmental parameters, substrate type, etc.), hearing range of the studied species, distance to the noise source, duration of exposure, level and type of mitigation, and presence of other noise sources like construction vessels.

For harbor and grey seals, tagging data around wind energy sites in Europe showed behavior consistent with foraging after construction was completed [@russell2014; @russell2016].
Pinnipeds appeared to either habituate quickly or to take advantage of wind farm physical structures as a foraging opportunity, whereas small dolphins and porpoises showed high variability in displacement and recovery response to wind farm construction and operations.
Considerable research is still needed to understand sea turtle hearing sensitivity and behavioral responses to noise.
Effects of noise associated with OSW construction and operation may be more similar to pinnipeds than cetaceans, which, as a species group, are more highly auditory and vocal in nature than sea turtles.
To date, however, there is not a complete understanding of the ranges of sea turtle hearing or their physiological and behavioral responses to underwater noise such as pile driving associated with turbine construction or that associated with turbine operation.

Kraus et al. [@kraus2019] summarized the potential short-term and long-term effects of offshore wind development on marine mammals and sea turtles in Massachusetts and Rhode Island Wind Energy Areas.
The list below is also relevant to the entire Atlantic coast.
Any specific concerns related to sea turtle species in each subregion will be further described in the following sections of this chapter.

**Potential short-term effects of offshore wind construction activities** [@kraus2019]

Potential short-term effects include reaction to noise from pile driving, vessel operating noise, and impacts of an increased presence of vessels.
These stressors could influence:

-   Displacement from wind energy areas

-   Disruption to critical behaviors such as feeding, socializing, or nesting 

-   Elevation of stress hormone levels

-   Changes in vertical distribution, density, or patch structure of prey

**Potential long-term effects of offshore wind operation** [@kraus2019]

Potential long-term effects include wind turbine presence, and increased vessel activity to/from and near turbine fields.
These stressors could influence:

-   Exclusion from or attraction to wind energy areas

-   Changes to feeding opportunities

-   Enhancements to marine productivity due to artificial reef effect around wind turbine foundations

The Sea Turtle Subcommittee also discussed potential impacts to sea turtles across the entire RWSC region.
The Kraus et al. [@kraus2019] report addressed MA and Rhode Island, and thus only listed potential impacts in the GOM and SNE subregions which are limited to seasonal foraging habitat for neritic hard-shelled and leatherback turtles.
Loggerhead, green and leatherback turtles have mating and nesting habitat in the USCA and USSEA subregions in addition to foraging and migratory habitat.

Below is an additional list of potential effects of concern identified by the subcommittee

-   Increased vessel interactions, lethal and non-lethal

-   Acoustic disturbance

-   EMF effects from underwater cables linking turbines and distributing electricity to shore

    -   Prey distribution – Some evidence of attraction to EMF [@albert2020]

    -   Navigation disturbance in foraging and migratory areas

    -   Nesting disturbance (south of Chesapeake Bay)

    -   Hatchling dispersal disturbance (south of Chesapeake Bay)

-   Other

    -   Changes in habitat from structure effects on water column stratification, frontal field, current velocity/direction, thermocline, halocline

    -   Reef effects

    -   Temporal and/or spatial changes in turtle and/or prey distribution due to warm water effluent from underwater DC substations

    -   Changes in entanglement/ingestion risk because of changes in distribution of fishing gear and aquaculture structures (especially increased fixed gear in lease areas)

    -   Interaction with floating/surface components and/or rotor intakes that could trap sargassum in off shelf planning areas

## Methods and approaches

To address questions about sea turtles and the potential concerns with respect to offshore wind development, the Science Plan describes commonly used methods and approaches for data collection and research in [Chapter 3: Science Plan Actions](https://rwscorg.sharepoint.com/:w:/s/SubcommitteeLeads/EY-LUU7PXBdMtvTJxFO2HEoBr087P2I7oa4Q7FJBFnCQHw?e=4GKIYe).
The following categories of methods are used throughout this chapter, but the Subcommittee recognizes that different tools, technologies, and/or procedures could be implemented with respect to each.

### Aerial and vessel-based line transect observational surveys

Large scale abundance data for sea turtles is generally collected using distance sampling surveys conducted from aerial, shipboard, and, in future, unmanned platforms such as drones.

In order to accurately estimate turtle abundance and/or density, aerial and vessel surface turtle counts are corrected for bias including perception bias and availability bias.
Perception bias is the likelihood that observers will detect a turtle at the surface.
Unlike small cetaceans such as dolphins and porpoises, turtles do not travel in groups and are relatively cryptic at the surface with no visible blow (exhalation) to cue observers.
Thus, it is likely that a proportion of turtles that are at the surface are missed by observers and the proportion that are missed is correlated with increasing sea state, turbidity and glare.
Availability bias incorporates the likelihood that an animal will be at the surface and *available* to be detected compared with the likelihood it will be subsurface and unable to be detected (*unavailable*).
It is imperative to understand the relationship between number of turtles detected at the surface, those that are available to be detected, and the proportion of the population that is below the surface and unavailable to be detected.
Again, compared to cetaceans which often travel in groups, detection of one individual in a group cues the observer to focus on a particular area increasing the likelihood of detection.
A single diving turtle may only be perceived as a surface disturbance and not be identified to the species level.

Unlike cetaceans, sea turtles surface time is highly variable by species, season, habitat, behavioral state, and other co-variates such as depth and water temperature.
Because they are ectothermic, surface time is variable for sea turtles and complicates abundance estimation for these marine vertebrates over other species [@hatch2022].
Surface time is estimated using tagged individuals, and, for sea turtles, should ideally be assessed at the time and location that surveys are being conducted.
Minimally, tag data used to determine availability should include multiple years and individuals of all species being detected and include a range of animal sizes in all survey strata and seasons.
Poor understanding of both perception and availability bias increases uncertainty in abundance estimates.

Because sea turtle abundance may be low and CV high for some species in some seasons of the RWSC study area, ability to detect changes in abundance and assigning causality to detected changes may be difficult.
In a tech memo summarizing a workshop on estimating loggerhead turtle abundance in the NW Atlantic, NOAA estimated that ten years of survey data may be needed to develop robust loggerhead turtle abundance estimates in the NW Atlantic and that current protocols are unable to detect turtles less than 40cm carapace length [@noaafisheries2020].

On page 15 of NOAA Tech Memo NMFS-OPR-67, authors list several next steps that are important elements in developing robust estimates for NW Atlantic loggerheads [@noaafisheries2020]:

-   Define management needs relative to the ability of aerial surveys to detect changes in abundance across appropriate timeline(s).
    Define desired level of confidence in those abundance estimates.

-   Establish the optimal survey altitude for sea turtles by conducting additional experiments at altitudes between 500–1,000ft to examine/understand the size of turtles that can be seen and turtle behavior relative to the survey platform.

-   Conduct additional field testing to determine detectability of a range of turtle sizes under varying water clarity and sea state conditions.

-   Explore the pros and cons of high resolution aerial photogrammetry and use of automatic pattern recognition, considering likely improvements in the next 5-10 years.
    Establish whether calibration or ground-truthing is needed for aerial photogrammetry using side-by-side flights with both photogrammetry and observers.

-   Ensure relevant aspects of sea turtle life history (e.g., seasonal migrations, behavioral state) are considered appropriately in the development of the survey design.

-   Design and conduct an experiment to assess variability of abundance estimates through repeat aerial surveys.

-   Explore whether existing satellite telemetry data are sufficient to assess the effects of sea state on surfacing behavior.

-   Refine measures of surface availability

    -   Take stock of satellite telemetry data and identify data gaps relative to location, life stage, and behavioral state (foraging, migrating, interesting intervals).

    -   Design appropriate satellite telemetry experiment(s) to fill identified data gaps.
        o Assess the value of repeated counts to inform surface availability; compare to satellite telemetry approach; integrate methods to improve surface availability estimation.

-   Mine data from all relevant existing aerial surveys to inform a new survey design, including block identification if appropriate.
    Develop simulations to refine survey design.

-   Coordinate survey design and implementation with other ongoing efforts to maximize efficiency and reduce duplication/overlap.

-   Develop funding estimates and consider potential funding sources, including leveraging existing funding.
    Develop a plan for and approach to seek funds.

\[Note that loggerheads are the most abundant sea turtle species in the NW Atlantic, perhaps by an order of magnitude over other species, making the complexity of developing robust abundance estimates for other species greater than for loggerheads.\]

The subcommittee believes that few of the suggestions made at the workshop in 2016 have been fully accomplished and believes that most are needed for loggerheads as well as other turtle species.
Providing funding and effort to better understand which turtles are being detected under what conditions, small turtle occurrence for green and Kemp’s ridley turtles estimates, and developing robust surface time estimates for all sea turtle species, in all subregions and seasons is critical for developing baseline abundance of sea turtle species.

Without this basic knowledge, assessing and mitigating impacts to sea turtles from a variety of sources, including offshore wind, will be extremely difficult.

### Tagging

For the purposes of this document, tagging refers to active tagging where tags transmit or archive data related to the tagged animal’s location, physiology and/or behavior.
This is in contrast to passive tags such as flipper (Inconel) and subdermal (PIT) tags which are applied to an animal and must later be detected on that animal during subsequent observations.
Tagging individual sea turtles includes the use of satellite and acoustic telemetry and may be paired with animal born and/or autonomous underwater cameras.
The size of some turtles restricts the use of larger and heavier tags which limits battery life and additional instrumentation such as time depth recorders (TDRs) and GPS chips.
To take advantage of the long battery life of tags used in acoustic telemetry, tags are often inserted internally into the target animals.
Currently this methodology is not an accepted permit activity for research on wild turtles and has been experimentally allowed on stranded, rehabilitated and released turtles.
The results of a recent pilot project conducted by the New England Aquarium may further the use of this method for sea turtle research [@innis2023].

### eDNA

Environmental DNA (eDNA) is DNA released from an organism into the environment via feces, mucus, shed skin, hair, etc.
It is detected in air, water, and substrate samples and requires assays from the organisms to be detected.
eDNA is useful for determining presence of a species, population, or individual, but its utility as an index of abundance is unclear.
Several organizations are developing eDNA assays for sea turtles and are ground truthing use of this technology in providing an index of abundance.
Pilot studies at several sites are pending.

### Long-term monitoring - Stranding response, nest surveys, sightings databases, and observed takes (dredge & fishery)

Sea turtles only come ashore to nest, at the time of hatching, and when stranded (sick, injured, or dead).
Nesting sea turtles in the U.S. are monitored annually on many beaches from Virginia through the U.S.
Gulf coast, and several index beaches are established to provide long term indices of nesting turtle presence which are correlated with abundance.
Nesting trends from index beaches which have been consistently monitored over decades are the primary data available for long-term population trend analysis for sea turtles in the U.S.
Atlantic.
An index of abundance has been established from long term nest monitoring data at specific sites in the Southern Atlantic subregion and in areas where turtles are resident or have relatively small seasonally shifting home ranges through capture/recapture studies.

Although many caveats exist with use of stranding data, the U.S.
Sea Turtle Stranding and Salvage Network may be another source of distribution and phenological trend information.

In addition, where survey data have few detections, citizen science sightings databases can add information on sea turtle presence.
There is at least one curated long-term sightings database curated by Mass Audubon that can provide information about individual sightings of species that are small and are not easily detected with most survey methodologies.

Finally, dredge and fishery observers record takes associated with permitted and authorized activities in many regions.
Observers follow established protocols and receive substantial training.
Though relatively rare, observed takes may also provide information on turtle presence in areas where abundance data are low.
This is particularly true of offshore areas where distribution data may be poor for some species.

Analyses of long-term data sets may provide the basis for future hypotheses regarding baseline population and distribution trends for sea turtle species, but these data sets have not always been consistently collected or reviewed and experience of data collectors for some monitoring data sets varies widely.

## Sea turtle research topics

The RWSC Sea Turtle Subcommittee recognizes that impacts to sea turtles associated with OSW have not been studied since much of the previous work has been done in European waters where sea turtles are not commonly observed.
The subcommittee also recognizes that impacts to sea turtles individually and at population levels are likely to be indirect, cumulative, synergetic and difficult assign to a single cause.
Disentangling the effects on sea turtles of climate change from any potential effects from offshore wind development will be a major challenge.

RWSC has established several Research Themes for the study of impacts to wildlife by OSW that build on work conducted by previous groups, on other wildlife species.
In subsequent sections, many of the detailed questions, hypotheses, and potential approaches that correspond to these Research Themes are described for regional-scale studies and for each subregion (Gulf of Maine-GOM; Southern New England-SNE; New York/New Jersey Bight-NYB; US Central Atlantic-USCA; US Southeast Atlantic-USSEA).

### Regional Field data collection and analysis

Ongoing and pending regional field data collection and analysis projects are listed in the RWSC Research Database.
Below are recommendations for regional field data collection and analysis for sea turtles.

-   NMFS Long-term protected species, fisheries, and ecosystem surveys form the backbone of the scientific monitoring system needed for the management of wildlife, fisheries, habitats, and ecosystems.
    In order to understand potential changes in wildlife and habitats from offshore wind energy development, it is critical that long-term standardized surveys provide timely, accurate, and precise data on wildlife, habitats, and ecosystems.
    The need to fully implement the NMFS and BOEM Survey Mitigation Strategy [@hare2022] and review the strategy to directly affect sea turtle survey needs is critical to putting site and regional level studies in the context of population trends and ecosystem conditions.
    The Strategy calls for the development of a Northeast Survey Mitigation Program. 
    This largely unfunded strategy should be fully funded and be a significant priority for the region as well as for the Atlantic waters of the Southeast region.

-   Increase level of regional-scale sea turtle species data collection including surveys designed to detect all sizes of sea turtles and at sea tagging through AMAPPS, BOEM, and US Navy projects

-   Employ recommendations by NMFS to enhance AMAPPS sea turtle abundance estimates listed in [@noaafisheries2020], especially detection studies of all sea turtle species and sizes under a variety of conditions

-   Enhance and expand abundance estimation, surface density estimates and habitat modeling using all appropriate forms of turtle occurrence data, including, but not limited to, verified sightings, strandings, bycatch data and prey distribution to determine biologically important areas for each sea turtle species in each RWSC subregion

### Regional Non-field research by type of action

#### Recommended coordination and planning

-   Specifically request that emphasis on sea turtles be included in the Federal Survey Mitigation Strategy as they are all ESA species likely to be impacted by OSW development and possibly by operation once construction is complete

-   Explore the possibility of quantifying cumulative stressors on sea turtles similar to assessments conducted following the Deep Water Horizon Oil Spill [@love2017] to better understand potential impacts of OSW compared with other threats sea turtles face in the NW Atlantic.

-   Coordinate and initiate collaborations with additional partners to facilitate data and information sharing, including the Sea Turtle Stranding and Salvage Network, organizations conducting sea turtle nest monitoring, sea turtle rescue organizations operating under USFWS permits and authorization as well as satellite, acoustic and other tag data

-   Develop collaborations with fish scientists and other acoustic telemetry users to implement a long-term archival acoustic detection network in the NW Atlantic Ocean, following sea turtle optimization analysis to guide future detector and tag deployments

-   Work with the sea turtle research and rescue community to determine whether development of a cache of tags suitable for sea turtles (acoustic and satellite; possibly through RWSC) would assist organizations that have needs for a small/unpredictable number of tags for deployment

-   Work with the sea turtle research and rescue community to determine whether the use of a data portal (similar to a combination of seaturtle.org & Movebank) would facilitate collaborative tagging studies, especially for determining baseline behavioral metrics and surface time estimates

-   Work with USFWS & the GARS stranding network to apply for regionwide rehab turtle tagging permit in support of OSW research

-   Work with NMFS & USFWS to encourage acceptance of internal acoustic tagging with SOP

#### Recommended historical data collection/compilation

-   Compile inventory of satellite/GPS tags deployed on sea turtles since 2010 (?) for future collaborative studies.
    Include tag type, deploy location, species, size, turtle source (wild/rehab/bycaught), days at large and general location

-   Compile historic sea turtle acoustic tag IDs from NW Atlantic for detection database searches and collaborative MS

-   Compile historic sea turtle nesting data by species, date, subregion and lat/lon for data portals

#### Recommended standardizing data collection, analysis, and reporting

-   Compile and disseminate acoustic tag/receiver deployment, detection study SOP, data archiving and analysis, data portal use for sea turtle research and rehab organizations

-   Sat tag data programming/processing for availability calculations (target audience – stranding networks)

-   Develop, test, and ground truth aerial survey detection parameters, methods, and protocols for all sea turtle species, size ranges in varying conditions (sea state, turbidity, etc.)

-   Develop and test eDNA assays/surveys/sampling regimes for use developing indices of occurrence/abundance, including testing the effect of carcasses in the environment on eDNA detection

#### Recommended study optimization

-   Review AMAPPS sea turtle survey effort (especially spring and fall) to determine effort gaps where turtles were unlikely to be detected/present due to conditions (sea state) and/or temperature

-   Conduct power analysis and experimental design development focusing on using multiple methods to detect changes to abundance, distribution, and behavior on one or more sea turtle species in each subregion

-   Develop an experimental design to obtain a better understanding of post hatchling dispersal stage habitat use in the NW Atlantic for all RWSC sea turtle species

-   Develop an understanding of sea turtle hearing and reaction to OSW noises by species and life stage including behavioral and physiological impact of noise created by OSW construction and operation

-   Determine the best methodology for assessing whether construction and operation activities displace or attract sea turtles

-   Create research design for development of abundance models similar to (or equivalent with) Winton et al. [@winton2018] and availability analyses similar to Hatch et al. 2020 for other species.
    Include review of existing sat tag data, including historic data, for species other than loggerhead turtles for possible inclusion in future analyses

#### Recommended model development and statistical frameworks

-   Use existing and newly acquired sea turtle behavioral data to describe sea turtle surfacing behavior in time-area strata with sufficient data and identify other time-area strata for further data collection

-   Investigate sea turtle carcass drift coastwide to understand the likelihood of detecting sea turtle mortality that occurs in offshore waters

-   Incorporate better understanding of uncertainty in abundance and distribution estimates similar to MM density model work (e.g. detectability in higher sea states, depth of detection, effect of size on detectability, error associated with poor understanding of availability)

-   Develop or update existing vessel and sea turtle/marine mammal co-occurrence models with vessels of various type and size associated with turbine construction and operation

#### Recommended technology advancement

-   Develop and test safe long term external attachment and/or internal insertion methods for acoustic tags on sea turtles

-   Develop and test smaller tags with depth sensors capable of surface time calculations for availability bias calculations in small juvenile turtles

-   Develop and test longer term (non-archival) tags and/or tag attachment techniques with low drag for capture/release in difficult (offshore) environments

-   Develop and test remote tag attachment techniques for in water work, especially for hard-shelled turtles

#### Recommended meta-analysis and literature review

-   Synthesize current and historic sea turtle nesting data, by species for Atlantic coast nesting beaches for trends analyses, permit applications, and mitigation.
    Make nesting data available to developers and researchers and store in a combined searchable format for future use.
    Provide assistance to states, municipalities, and NGOs who collect these data with upload/conversion to collective database.

#### Recommended outreach and platforms to provide data products and results to stakeholders

-   Synthesize sea turtle nesting data, by species for Atlantic coast nesting beaches for trends and store in a combined searchable format for future analyses \[also listed under meta-analysis\]

-   Facilitate collaborative tag analysis with stranding networks and field researchers 

The following sections describe sea turtle data gaps followed by research needs with respect to sea turtles in each specific RWSC subregion of the US Atlantic Ocean.
In some cases, needs are specific to a single subregion, other data/research needs apply to more than one subregion.

### Gulf of Maine (GOM) data gaps, recommended research, and data collection activities for sea turtles

#### Focal species and habitats of interest in the GOM

The Gulf of Maine subregion is seasonal foraging habitat for all sea turtle species covered by the Plan but, with the exception Cape Cod Bay, might be considered marginal habitat for Kemp’s ridley and green turtles.
Wild caught loggerhead and leatherback turtles have been tracked in and out of the Gulf of Maine, including, but not exclusive of Cape Cod Bay [@dodge2014; @palka2021], and individuals of both species have been bycaught in the Atlantic Canadian longline fishery, suggesting seasonal distribution in the region[@james2006; @james2007; @paul2010].
Suitable leatherback turtle habitat off Nova Scotia has been identified using both leatherback and Mola sightings along with environmental correlates in modeling analyses [@a.mosnier2018].
Jellyfish distribution has also been used to predict leatherback distribution [@nordstrom2020].

Most individuals are juveniles (Kemp’s ridley, green, loggerhead) and subadults (loggerhead), but adult leatherbacks can also be found in the subregion [@dodge2014].

Better understanding of the importance of Cape Cod Bay for juvenile Kemp’s ridley and green turtles is needed as it appears to be the primary area of the subregion in which these two species occur.
For smaller individuals, primarily Kemp’s ridley and green turtles, there is a paucity of sightings in historic aerial and shipboard abundance surveys [@dimatteo2022; @palka2021] and relatively few opportunistic citizen science sightings reported to the [Sea Turtle Sighting Hotline for New England Boaters](https://seaturtlesightings.org/).
A query of historic strandings of hard shelled turtles (loggerhead, Kemp’s ridey, green) from Cape Cod Bay north through Maine from April-early November (outside of cold stun season) resulted in a total of 50 strandings from 2013-2022, an average of five per year.
All strandings occurred in MA, and 25 were loggerhead, 23 Kemp’s ridley, one green turtle and one possible hybrid.
Low sightings combined with relatively few green turtles in the stranding record outside of the late fall cold stun season (STSSN *unpublished data received* 2 May 2023) raise questions about the role of the GOM subregion in the ecology of this species.
Paucity of detections from survey, sighting and stranding data is not sufficient to hypothesize that the GOM subregion is not important habitat for Kemp’s ridley turtles because these small juvenile turtles are difficult to detect from planes and vessels.
Though stranding numbers were low overall, the similarity of loggerhead and Kemp’s ridley strandings in addition to very high numbers of cold stunned Kemp’s ridleys in late fall call into question whether Kemp’s ridleys are present in Cape Cod Bay in similar numbers as loggerheads.

Assuming that cold stunned sea turtle numbers in Cape Cod Bay are representative of cheloniid habitat-use, this region could constitute important seasonal habitat for Kemp's ridleys, followed by loggerheads, with less importance for green sea turtles.
There is concern, however, what type of ecological impact the area may have on the Kemp’s ridley population given the high numbers of cold stunned turtles that are reported each year.
Few if any of the hundreds of turtles would survive cold stunning without human intervention.
Global climate change is likely to result in increasing numbers of hard-shelled turtles in this region, thus regular reassessment of turtle occurrence in the GOM will be necessary.

Because baseline data for sea turtles in the GOM is relatively sparse and most turtle species, with the exception of leatherbacks, are not present in high enough densities to detect changes in abundance with any confidence, determining and studying impacts on a subregion-wide and/or population level are unlikely to be successful.
The subcommittee suggests that small, focused studies on individual animal movement and behavior that are site specific may be most effective strategies for assessing impacts in the GOM.

#### Potential effects of concern specific to the GOM subregion

In addition to the potential regionwide effects discussed in [section 1.3 of this chapter](#Potential_Effects_of_OSW), there may be different effects due to turbine designs needed for the deeper waters in this subregion.
Because of depth in the federal portion of GOM, turbines used to develop wind energy areas in this subregion will be floating units [@musial2016].
It is currently unclear whether this technology will have different impacts from turbines attached to the bottom.
Use of this technology may provide opportunities for comparison studies with nearby installations in the Southern New England subregion.
Rafts of debris and algae associated with a different surface footprint and floating turbine movement may impact turtles and their non-benthic prey in different ways than static, bottom anchored turbines.
If floating designs incorporate subsurface rotors to maintain stability and position, small turtles and near surface (gelatinous) prey may be impacted in ways that they will not be impacted by static turbines.

#### Recommended field data collection and analysis needs in the GOM subregion

-   Continue regional-scale protected species data collection through AMAPPS survey and tagging studies or similar programs – emphasize GOM?
    Especially tagging

-   Supplement AMAPPS data with methods that detect smaller species and juveniles, especially in Cape Cod Bay

-   Determine ecological role of Cape Cod Bay for juvenile Kemp’s ridley turtles through additional tagging and modeling that incorporated sighting and stranding data

-   Explore potential impacts to sea turtles and gelatinous prey when they co-occur with floating turbines

### Southern New England (SNE) data gaps, recommended research, and data collection activities for sea turtles

#### Focal species and habitats of interest in the SNE subregion

The Southern New England subregion is seasonal foraging habitat for all sea turtle species covered by the Plan.
Leatherback and loggerhead turtles have been detected on distance sampling surveys conducted as part of the regional AMAPPS program as well as on smaller scale survey efforts used in addition to AMAPPS survey by a Navy abundance estimation effort [@dimatteo2022; @palka2021].
Capture, tag, release (loggerhead and leatherback), remote tagging (leatherback), and disentanglement (leatherback, loggerhead and Kemp’s ridley) have been conducted in the SNE subregion [@dodge2014; @hatch2022; @karal.dodge2022; @palka2021].
Few Kemp’s ridley and green turtles were detected in the SNE subregion on AMAPPS surveys, but there were some unidentified hard-shelled turtles detected that may have been these species [@palka2021].
Opportunistic sightings of Kemp’s ridley turtles are rare but consistently occur each year in summer and early fall in the Sea Turtle Sightings Database but sightings of green turtles are less consistent, and the subcommittee believes this subregion may also currently be a marginal habitat for green turtles (Sea Turtle Sighting Hotline for New England Boaters *unpublished data* *received* 23 May 2023).

#### Potential effects of concern specific to the SNE subregion

The potential effects of offshore wind development are similar in this subregion as are discussed in [section 1.3 of this chapter](#Potential_Effects_of_OSW).
The imminent development of the Vineyard and South Fork Wind projects makes the SNE subregion of particular interest to the subcommittee, since we do not have data or published research from other wind developments in sea turtle habitat.
Both projects had estimated foundation construction start dates in late spring 2023.
Development in the SNE will pose the first opportunity to study sea turtle behavior during construction and operation of NW Atlantic wind turbines.
It is unclear whether baseline abundance data for loggerhead and leatherback turtles in the SNE subregion will be sufficient to detect changes in abundance and/or distribution at the regional level using distance sampling techniques.
Thus, smaller scale studies with a phase gradient experimental approach, focused on the development area and areas increasingly distant from the development [@ellisj.i.1997], as well as vessel corridors could be the focus of study in this subregion.
Sea turtles should be included as a significant part of vessel co-occurrence and reef development studies.
Turbine construction activities are designed to avoid times when critically endangered right whales were historically in the area (Jan-April), but these limitations will not avoid the times of highest sea turtle occurrence.

#### Recommended field data collection and analysis in the SNE subregion

-   Design, plan, fund and conduct, long-term, small-scale studies specifically designed to determine effects on sea turtle species using multiple methodologies in the vicinity of wind projects currently under development in the SNE, NY/NJB and USCA regions.
    Tailor studies to take advantage of each subregion’s development timeline and unique sea turtle occurrence.
    Build on knowledge from each study to optimize results for future studies.

### New York/New Jersey Bight (NY/NJB) data gaps, recommended research, and data collection activities for sea turtles
