# Bats {#sec-bats}

*Authors: [Bird & Bat Subcommittee](append-rosters.qmd#bb)*

*For more detail on any of these topics, read* @sec-append-bats.

Scientific understanding of bat activity and behavior in the offshore environment is relatively limited at present.
At least six species of bat are known to occur offshore, including the long-distance migratory tree bats (hoary bat, silver-haired bat, eastern red bat), as well as Myotis species of conservation concern [@solick2021].
These species are most often detected in the offshore environment during the fall migration season [@solick2021].
Overall, in the absence of offshore wind facilities, bat activity is thought to be lower at isolated offshore sites compared to most coastal, island, and inland habitats [@peterson2021; @solick2021].

Collisions with operating wind turbines are expected to be the main potential impact of offshore wind development on bats [@seer2022], although collision risk and fatality rates in the offshore environment are currently entirely unknown.
In the terrestrial environment, bat mortality at wind facilities is a common occurrence [@awwi2020], and these fatalities are estimated to represent a population-level, and even existential, threat to some bat species [@frick2017; @friedenberg2021].
Bats appear to be attracted to land-based wind turbines and other tall structures [@cryan2014; @guest2022; @jameson2014].
Researchers have hypothesized that the greater height of offshore wind turbines and their prominence in an otherwise flat seascape could increase attraction of bats to offshore wind facilities [@solick2021], potentially increasing collision risk or leading to greater exposure to harsh weather conditions offshore [@wilson2023].

Whether there is a need for on-site or off-site mitigation for impacts to bats at offshore facilities is not yet known, although researchers have highlighted the value of considering mitigation for bats early in the offshore wind development and monitoring process [@solick2021; @true2023], both for conservation and regulatory reasons.
Operational curtailment during environmental conditions when bat activity is expected to be high (e.g., low wind speed nights) has proven effective at terrestrial wind facilities [@adams2021; @whitby2021].
Deterrent technologies continue to be developed and evaluated [@hein2021].
In some studies, individual technologies have reduced overall bat fatalities [@hein2021; @romano2019; @weaver2020]; however, no deterrent has shown consistent reductions in fatalities of eastern red bats, the most commonly detected species offshore [@solick2021].

The following subsections address near-term recommendations for data management, field data collection, and data analysis actions to help characterize bat activity and movements in the offshore environment, assess collision risk, and further the development of new or improved technologies for monitoring and mitigation.
These recommendations are based primarily on Bird & Bat Subcommittee discussions, the [2020 State of the Science Workshop on Wildlife and Offshore Wind Energy Bat Workgroup Report](https://www.nyetwg.com/_files/ugd/78f0c4_fe36c3c091724b14a884851859966ad1.pdf), and the [NYSERDA E-TWG Synthesis of Regional Research Recommendations](https://www.nyetwg.com/regional-synthesis-workgroup), with an eye towards past, current, and planned science activities relevant to offshore wind development and bats, as catalogued in the [Offshore Wind & Wildlife Research Database](https://database.rwsc.org/) (recent, current, and planned studies), the [Tethys Knowledge Base](https://tethys.pnnl.gov/knowledge-base) (publications, reports, and presentations relevant to offshore wind) and [Tethys Offshore Wind metadata](https://tethys.pnnl.gov/offshore-wind-metadata) (information on environmental monitoring conducted at offshore wind energy projects around the world).

Individuals and entities are strongly encouraged to consult with the Bird & Bat Subcommittee prior to collecting bat data along the U.S.
Atlantic Coast or conducting novel data analyses relevant to offshore wind interactions to ensure that planned research does not duplicate existing efforts and is consistent with recommended tools and approaches.
Any individual or entity may join public Bird & Bat Subcommittee meetings or ask to present materials at these meetings via the RWSC website.

## Data Management

Understanding bat activity around offshore wind facilities and regionally along the U.S.
Atlantic Coast will require close coordination among researchers, state and federal agencies, and industry.
The Bird & Bat Subcommittee wishes to work with individuals and entities who collect data relevant to bat-offshore wind research to ensure that data are collected and stored in consistent formats that allow comparisons and pooling across individual projects in the RWSC Study Area.
This standardization is intended to support regional-scale assessments, data products, and tools (e.g., NABat occupancy and abundance estimates; evaluations of collision risk relative to wind facility, temporal, and environmental characteristics).

To support these efforts, the Bird & Bat Subcommittee recommends:

-   Maintenance of an up-to-date resource list of recommended standard databases, data repositories, guidelines, and protocols for use by all data collectors.
    The current recommended resources are detailed in the table below.

-   Development of standard language for inclusion in funding and contract documents to encourage or require the use of recommended resources.

-   Establishment of an Offshore Bat Working Group to address gaps in existing databases (detailed in the table below), including development of recommended protocols/standards where absent, suggestions for the structure/content of new databases, and identification of pilot study parameters where too little is currently known to provide specific methodological guidance.
    This Working Group has recently been established and, as a first step, will address methodological recommendations and pilot study parameters for passive acoustic detector deployment on offshore infrastructure.

-   Establishment of data sharing frameworks to appropriately manage access to sensitive industry-collected datasets necessary for research (e.g., acoustic data collected on offshore wind turbines, bat-turbine interactions, and collision data; associated turbine status and local meteorological conditions).

-   Identification, solicitation, and compilation of historic data into recommended databases to inform baseline understanding of bat distributions in coastal and offshore areas of the U.S.
    Atlantic Coast.
    In some cases, this may require re-formatting and QA/QC procedures to ensure species codes, units, and other metadata are entered consistently.

The following table lists the existing centralized or accepted repositories and standards that are recommended for use in bat data collection, as well as identifying data types for which no or limited data management capacity (i.e., standard repositories and guidance) currently exists.

Table 3.
Recommended repositories and standards for bat data collection.

+----------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Method(s) and data type(s)**                                                                                             | **Repository**                                                                                                                                                   | **Existing Guidance/Standards**                                                                                                                                                                                                                                                                                                                                                                                             |
+----------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Acoustic data (passive or active); Bat observations (colony and roost counts, capture records, incidental observations)    | [**North American Bat Monitoring Program (NABat)**](https://sciencebase.usgs.gov/nabat/)                                                                         | -   Use [A Plan for the North American Bat Monitoring Program](https://www.fs.usda.gov/treesearch/pubs/48442) for survey protocols and field study guidance.                                                                                                                                                                                                                                                                |
|                                                                                                                            |                                                                                                                                                                  |                                                                                                                                                                                                                                                                                                                                                                                                                             |
|                                                                                                                            |                                                                                                                                                                  | -   Visit [NABat Resources](https://www.nabatmonitoring.org/resources) for detailed guidance on data preparation, processing, uploading, and QA/QC procedures. NABat also provides a [grid-based offshore sampling frame](https://rwscorg-my.sharepoint.com/personal/admin_rwsc_org/Documents/FINAL%20Science%20Plan%20Chapters%20November%202023/NABat%20also%20provides%20a%20grid-based,%20offshore%20sampling%20frame). |
|                                                                                                                            |                                                                                                                                                                  |                                                                                                                                                                                                                                                                                                                                                                                                                             |
|                                                                                                                            |                                                                                                                                                                  | -   *Development of offshore-specific protocols for passive and active acoustics are recommended.*                                                                                                                                                                                                                                                                                                                          |
|                                                                                                                            |                                                                                                                                                                  |                                                                                                                                                                                                                                                                                                                                                                                                                             |
|                                                                                                                            |                                                                                                                                                                  | -   *NABat has confirmed that it can incorporate contemporaneous local meteorological data and turbine operational status with bat acoustic detection data.*                                                                                                                                                                                                                                                                |
+----------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Automated VHF tagging/tracking studies                                                                                     | [**Motus Wildlife Tracking System**](https://motus.org/about/)                                                                                                   | -   Use [Monitoring Protocols and Guidance for Automated Radio Telemetry Studies at Offshore Wind Farms](https://motus.org/groups/atlantic-offshore-wind) for study design and data collection                                                                                                                                                                                                                              |
|                                                                                                                            |                                                                                                                                                                  |                                                                                                                                                                                                                                                                                                                                                                                                                             |
|                                                                                                                            |                                                                                                                                                                  | -   [Motus Wildlife Tracking System resources](https://motus.org/resources/) provide extensive additional documentation on data collection, upload, and analysis                                                                                                                                                                                                                                                            |
+----------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Other tagging/tracking studies                                                                                             | [**Movebank**](https://www.movebank.org/cms/movebank-main)                                                                                                       | -   [Movebank User Manual](https://www.movebank.org/cms/movebank-content/manual) provides step-by-step guidance on adding, managing, sharing, and accessing tracking data                                                                                                                                                                                                                                                   |
+----------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Carcasses and tissue samples                                                                                               | [**Renewables-Wildlife Solutions Initiative**](https://www.usgs.gov/centers/forest-and-rangeland-ecosystem-science-center/science/renewables-wildlife-solutions) | -   Contact the [Renewables-Wildlife Solutions Initiative](https://www.usgs.gov/centers/forest-and-rangeland-ecosystem-science-center/science/renewables-wildlife-solutions) to submit samples                                                                                                                                                                                                                              |
|                                                                                                                            |                                                                                                                                                                  |                                                                                                                                                                                                                                                                                                                                                                                                                             |
|                                                                                                                            |                                                                                                                                                                  | -   *Note that these repositories have limited capacity but are currently accepting samples.*                                                                                                                                                                                                                                                                                                                               |
+----------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Observed interactions with wind turbines, collisions, fatalities (e.g., via turbine-mounted cameras, multi-sensor systems) | No central repository -- requires development                                                                                                                    | *Development of a database and standard protocols is recommended as an action.*                                                                                                                                                                                                                                                                                                                                             |
+----------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Large raw file types (e.g., high-definition aerial photos, thermal video, raw acoustic files)                              | No central repository -- requires development                                                                                                                    | -   *Retention of large, raw file types could allow for future QA/QC and re-evaluation with updated analysis or automated identification tools.*                                                                                                                                                                                                                                                                            |
|                                                                                                                            |                                                                                                                                                                  |                                                                                                                                                                                                                                                                                                                                                                                                                             |
|                                                                                                                            |                                                                                                                                                                  | -   *Development of a data repository, with standard protocols and data-handling procedures, is recommended as a cross-taxa action.*                                                                                                                                                                                                                                                                                        |
+----------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## Data Collection

In coastal and marine environments, several field research methods can inform our scientific understanding of bat interactions with offshore wind facilities (for common methodologies, see [@seer2022]. As part of Construction and Operations Plans (COPs), offshore wind developers are developing and submitting avian and bat monitoring plans.
Of relevance to bats, current available draft monitoring plans typically include deploying passive acoustic detectors on turbines or other offshore wind facility infrastructure, deploying active acoustic detectors on work vessels accessing the facility, and deploying and maintaining Motus receiver stations for a specified number of years post-construction.
State agencies, federal agencies, and research organizations regularly deploy acoustic detectors in coastal environments.
Motus or standard VHF tags have also been deployed on bats utilizing habitat in coastal areas [@dowling2018; @peterson2021; @true2023].

As part of addressing near and long-term goals, the Bird & Bat Subcommittee recommends the following field research, data interpretation, and technology advancement activities:

-   **Data collection to characterize bat activity and collision risk in the rotor-swept zone of offshore wind turbines.**

    -   Using passive acoustic detectors mounted on turbine platforms, towers, and nacelles to document bat activity year-round.

    -   Deploying multi-modal systems on turbines to assess bat interactions with wind turbine infrastructure (including micro-avoidance and collision risk).
        Combinations of acoustic detectors, radar systems, impact detection sensors, and/or visual, thermal, and infrared cameras are recommended to document bat behavior around wind turbines, detect impacts, and, in some cases, provide species-specific identification.

    -   Recording contemporaneous turbine operational status and local meteorological data to inform patterns of bat activity, behavior, and collision risk relative to turbine operation and environmental conditions.

-   **Use of acoustics to better understand onshore-to-offshore gradients of bat activity pre- and post-construction.** Leveraging existing platforms (e.g., vessels which already make regular trips through offshore waters, offshore buoys, other offshore infrastructure) and coastal and island sites will aid in this effort.

-   **Use of Motus tagging/tracking systems to characterize patterns of bat movement offshore** (Acoustic studies alone may fail to fully capture bat activity if bats regularly refrain from  echolocation while flying over the ocean [@corcoran2021; @corcoran2018].

    -   Deploying Motus tags on migratory tree bats (hoary bats, eastern red bats, silver-haired bats) to evaluate patterns of movement during the spring and late summer-fall migration seasons.

    -   Deploying Motus tags on *Perimyotis* and *Myotis* species of conservation concern in coastal areas and on islands in late summer to evaluate dispersal from maternity colonies to swarming or overwintering sites.

    -   Coordinating deployment of Motus stations to streamline calibration and optimize placement (see @sec-birds).

-   Development, testing, and advancement of new, emerging, or under-utilized technologies for monitoring and mitigation.

    -   **Testing and validating bat collision detection systems** (recognizing that initial validation may need to focus on land-based wind facilities, where carcass counts are possible).

    -   **Improving access to remote wildlife monitoring data and integrating wildlife monitoring equipment** on wind turbine platforms or other offshore infrastructure.
        This could include identifying workflows to allow for the transmission of wildlife monitoring data using existing wind facility fiber-optic networks.

    -   **Designing and improving auto-classification of acoustic data to identify species or taxa.**

    -   **Improving tagging technologies and attachment methods** to allow for lighter tags and longer-term tracking.

    -   **If mitigation is deemed necessary, testing and validating the efficacy of on-site mitigation strategies** (e.g., feathering, curtailment, deterrents).
        As noted above, validation of mitigation in the offshore environment will be difficult, and the development of effective bat collision detection systems, validated at land-based wind facilities, would be necessary for validation of mitigation measures in the offshore environment.
        Alternatively, efficacy would need to be estimated based on land-based proxies and the best available science.

## Data Analysis

Data analyses and summaries should inform where new data collection is needed, characterize bat activity and distribution patterns in coastal and offshore environments, and/or address the efficacy of monitoring or mitigation strategies.

To address near-term needs, the Bird & Bat Subcommittee recommends:

-   As data are collected, analysis to evaluate collision risk and relate offshore bat activity and collision risk to meteorological conditions, turbine characteristics, and turbine operational status.
    If mitigation is deemed necessary in the future, these analyses could be used to design and implement efficient operational mitigation measures, such as curtailment.

-   Contributions of new and historical data to the NABat database to allow for the extension of seasonal occupancy and abundance maps/estimates offshore.

-   Development of a framework to evaluate population-scale risks of offshore collision mortality to bats, in a context of great uncertainty.
    Identification of the data needed to inform and validate models.
