# Birds {#sec-birds}

*Authors: [Bird & Bat Subcommittee](append-rosters.qmd#bb)*

*For more detail on any of these topics, read* @sec-append-birds.

Over 400 bird species regularly occur along the U.S.
Atlantic Coast, representing a variety of life histories and interactions with the offshore environment.
A number of these species can be expected to experience impacts from offshore wind development, including collision fatalities, displacement, attraction, barrier effects associated with avoidance, and effects on abiotic habitat features and prey populations [@nrel2022]; indirect effects of offshore wind energy development, like climate change mitigation, can also be expected.
To identify, quantify, monitor, and mitigate interactions between birds and offshore wind facilities, a wide variety of data management, data analysis, and field data collection activities will be necessary over the coming decades.
The following subsections address near-term recommendations for science actions in these categories.
These recommendations are based primarily on Bird & Bat Subcommittee discussions, the [2020 State of the Science Workshop on Wildlife and Offshore Wind Energy Bird Workgroup Report](https://www.nyetwg.com/_files/ugd/78f0c4_1bb7d0c9d38a4417b54f40c66248562a.pdf), and the [NYSERDA E-TWG Synthesis of Regional Research Recommendations](https://tethys.pnnl.gov/atlantic-offshore-wind-environmental-research-recommendations), with an eye towards past, current, and planned science activities relevant to offshore wind development and birds, as catalogued in the [Offshore Wind & Wildlife Research Database](https://database.rwsc.org/) (recent, current, and planned studies), the [Tethys Knowledge Base](https://tethys.pnnl.gov/knowledge-base) (publications, reports, and presentations relevant to offshore wind) and [Tethys Offshore Wind metadata](https://tethys.pnnl.gov/offshore-wind-metadata) (information on environmental monitoring conducted at offshore wind energy projects around the world).

Individuals and entities are strongly encouraged to consult with the Bird & Bat Subcommittee prior to collecting avian data along the U.S.
Atlantic Coast or conducting novel data analyses relevant to offshore wind interactions to ensure that planned research does not duplicate existing efforts and is consistent with recommended tools and approaches.
Any individual or entity may join public Bird & Bat Subcommittee meetings or ask to present materials at these meetings via the RWSC website.

## Data Management

Understanding avian interactions with offshore wind infrastructure -- from the scale of individual wind turbines and facilities to the scale of the entire Atlantic Flyway -- will require close coordination among researchers, state and federal agencies, and industry.
The Bird & Bat Subcommittee aims to work with individuals and entities who collect data relevant to avian offshore wind research to ensure that data are collected and stored in consistent formats that allow for comparisons among and pooling across individual projects in the RWSC study area. 
This standardization is intended to support regional-scale assessments and the development and maintenance of regional data products and tools.

In support of these efforts, the Bird & Bat Subcommittee recommends:

-   Maintenance of an up-to-date resource list of recommended standard databases, data repositories, guidelines, and protocols for use by all data collectors.
    The current recommended resources are detailed in the table below.

-   Development of standard language for inclusion in funding and contract documents to encourage or require the consistent use of recommended resources.

-   Establishment of an Avian Data Standards Working Group to address gaps in existing data infrastructure (detailed in the table below), including development of recommended protocols/standards where absent, recommendations for the structure/content of new databases, and identification of pilot study parameters where too little is currently known to provide specific methodological guidance.
    The order in which gaps are addressed will be prioritized by the Bird & Bat Subcommittee and working group members, taking care to avoid duplicating efforts by outside groups.

-   Establishment of data sharing frameworks to appropriately manage access to sensitive industry-collected datasets necessary for research (e.g., avian-turbine interaction, micro-avoidance, and collision data; turbine status and local environmental conditions; turbine specifications relevant to placement of monitoring equipment).

-   Compilation of new and historic data into recommended databases to inform scientific understanding of behavior, distribution, and population dynamics of birds of the U.S.
    Atlantic Coast.

The following table lists the existing centralized and accepted repositories and standards that are recommended for use in avian data collection, as well as identifying data types for which no or limited data management capacity (i.e., standard repositories and guidance) currently exists.

Table 2.
Recommended repositories and standards for avian data collection.

+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Method(s) and data type(s)**                                                                                                                                                                                                                                                  | **Database/Repository**                                                                                                                                                                   | **Guidance/Standards**                                                                                                                                                                                                                                                                                       |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| At-sea surveys (aerial, stationary, boat-based; visual observation, photography, video)                                                                                                                                                                                         | [**Northwest Atlantic Seabird Catalog**](https://www.boem.gov/environment/environmental-studies/14-x07pdf-0)                                                                              | -   Follow [Guidance for Pre- and Post-Construction Monitoring to Detect Changes in Marine Bird Distributions and Habitat Use Related to Offshore Wind Development](https://www.nyetwg.com/avian-displacement-guidance)                                                                                      |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           |                                                                                                                                                                                                                                                                                                              |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           | -   Ensure compliance with [BOEM Avian Survey Guidelines](https://www.boem.gov/Avian-Survey-Guidelines/)                                                                                                                                                                                                     |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           |                                                                                                                                                                                                                                                                                                              |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           | -   Use [SeaScribe](https://briwildlife.org/seascribe/) or [SeaLog](https://www.usgs.gov/software/sealog) for data collection                                                                                                                                                                                |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           |                                                                                                                                                                                                                                                                                                              |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           | -   *Development of a public-facing interface for the Northwest Atlantic Seabird Catalog is recommended as an action.*\                                                                                                                                                                                      |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           |     \                                                                                                                                                                                                                                                                                                        |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Automated VHF tagging/tracking studies                                                                                                                                                                                                                                          | [**Motus Wildlife Tracking System**](https://motus.org/about/)                                                                                                                            | -   Use [Monitoring Protocols and Guidance for Automated Radio Telemetry Studies at Offshore Wind Farms](https://motus.org/groups/atlantic-offshore-wind) for study design and data collection                                                                                                               |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           |                                                                                                                                                                                                                                                                                                              |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           | -   [Motus Wildlife Tracking System resources](https://motus.org/resources/) provide extensive additional documentation on data collection, upload, and analysis                                                                                                                                             |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Other tagging/tracking studies                                                                                                                                                                                                                                                  | [**Movebank**](https://www.movebank.org/)                                                                                                                                                 | -   Follow interim [USFWS Guidance for Coordination of Data from Avian Tracking Studies](https://rwscorg.sharepoint.com/:b:/s/BirdandBatSubcommittee/EWiyjaGje4tOsn7YjpJ13P8B8jQRQP9b2nUt9y4dRwpV6g?e=Ew3LOO)                                                                                                |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           |                                                                                                                                                                                                                                                                                                              |
| (e.g., PTT, GPS, geolocator tags)                                                                                                                                                                                                                                               |                                                                                                                                                                                           | -   [Movebank User Manual](https://www.movebank.org/cms/movebank-content/manual) provides step-by-step guidance on adding, managing, sharing, and accessing tracking data                                                                                                                                    |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           |                                                                                                                                                                                                                                                                                                              |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           | -   Ensure shorebird tracking data are accessible to the [Shorebird Conservation Collective](https://nationalzoo.si.edu/migratory-birds/shorebird-collective)                                                                                                                                                |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           |                                                                                                                                                                                                                                                                                                              |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           | -   *Development of more in-depth guidance is recommended as an action*                                                                                                                                                                                                                                      |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Bird banding, band identification and reporting                                                                                                                                                                                                                                 | [**USGS Bird Banding Laboratory**](https://www.usgs.gov/labs/bird-banding-laboratory)                                                                                                     | -   Follow Federal Bird Banding and Marking Permit requirements (as required by law)                                                                                                                                                                                                                         |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           |                                                                                                                                                                                                                                                                                                              |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           | -   Identified bands can be reported at [www.reportband.gov](file:///Users/christianlaspada/Downloads/www.reportband.gov)                                                                                                                                                                                    |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Carcasses and tissue samples                                                                                                                                                                                                                                                    | [**Renewables-Wildlife Solutions Initiative**](https://www.usgs.gov/centers/forest-and-rangeland-ecosystem-science-center/science/renewables-wildlife-solutions)                          | -   Contact the [Renewables-Wildlife Solutions Initiative](https://www.usgs.gov/centers/forest-and-rangeland-ecosystem-science-center/science/renewables-wildlife-solutions) to submit samples                                                                                                               |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           |                                                                                                                                                                                                                                                                                                              |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           | -   *Note that these repositories have limited capacity but are currently accepting samples.*                                                                                                                                                                                                                |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Colony and shorebird population and distribution data                                                                                                                                                                                                                           | **Atlantic Flyway Colonial Waterbird Database** is currently under development by the [Avian Knowledge Network](https://avianknowledge.net)                                               | -   Follow [Avian Knowledge Network data upload and management guidance](https://avianknowledge.net/index.php/upload-enter-manage-data/) for data submission to this database.                                                                                                                               |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           |                                                                                                                                                                                                                                                                                                              |
|                                                                                                                                                                                                                                                                                 | [**International Shorebird Survey**](https://www.manomet.org/project/international-shorebird-survey/) allows for data entry of shorebird survey data collected using established protocol | -   Use species- and study-appropriate protocols as applicable, e.g.,                                                                                                                                                                                                                                        |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           |                                                                                                                                                                                                                                                                                                              |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           |     -   [International Shorebird Survey](https://www.manomet.org/project/international-shorebird-survey/) protocol                                                                                                                                                                                           |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           |                                                                                                                                                                                                                                                                                                              |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           |     -   [IWMM protocols](https://iwmmprogram.org/protocols-data-forms/) for monitoring habitat conditions and waterbird use during the nonbreeding season                                                                                                                                                    |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           |                                                                                                                                                                                                                                                                                                              |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           |     -   [USFWS framework](https://ecos.fws.gov/ServCat/DownloadFile/101125) for surveys for secretive marsh birds                                                                                                                                                                                            |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           |                                                                                                                                                                                                                                                                                                              |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           | -   *Development/standardization of additional guidance is recommended as an action.*                                                                                                                                                                                                                        |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Other observational survey data (e.g., from land-based surveys for transmission cable routes)                                                                                                                                                                                   | [**eBird**](https://ebird.org/home)                                                                                                                                                       | -   Use [eBird Protocols](https://support.ebird.org/en/support/solutions/articles/48000950859-guide-to-ebirdprotocols) or other [accepted standards and practices](https://rcngrants.org/content/development-avian-indicators-and-measures-monitoring-threats-and-effectiveness-conservation) as appropriate |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           |                                                                                                                                                                                                                                                                                                              |
| \*Note: This is not intended to include standardized survey data collected as part of regular annual surveys (such as the [Breeding Bird Survey](https://www.pwrc.usgs.gov/bbs/) or [Christmas Bird Count](https://www.audubon.org/conservation/science/christmas-bird-count)). |                                                                                                                                                                                           | -   Note: Use establishedsurvey protocols and data entry points for standardized annual surveys (such as the [Breeding Bird Survey](https://www.pwrc.usgs.gov/bbs/) or [Christmas Bird Count](https://www.audubon.org/conservation/science/christmas-bird-count)).                                           |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           |                                                                                                                                                                                                                                                                                                              |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           | -   *Development/standardization of additional guidance regarding land-based observations may be needed but is a lower priority in the context of offshore wind development.*                                                                                                                                |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Observed interactions with wind turbines, collisions, fatalities (e.g., via turbine-mounted cameras, impact detection systems)                                                                                                                                                  | [**Injury and Mortality Reporting database**](https://ecos.fws.gov/imr/welcome) tracks reports of dead and injured birds.                                                                 | -   Report dead or injured birds to the [Injury and Mortality Reporting database](https://ecos.fws.gov/imr/welcome).                                                                                                                                                                                         |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           |                                                                                                                                                                                                                                                                                                              |
|                                                                                                                                                                                                                                                                                 | No central repository exists for other types of bird-turbine interaction data or more detailed collision/fatality data and associated metadata-- requires development                     | -   *Development of a database and standard protocols is recommended as an action.*                                                                                                                                                                                                                          |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Seabird diet data                                                                                                                                                                                                                                                               | No central repository -- requires development                                                                                                                                             | *Development of a database and standard protocols is recommended as an action.*                                                                                                                                                                                                                              |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Passive acoustic monitoring                                                                                                                                                                                                                                                     | No central repository -- requires development                                                                                                                                             | *Development of a database and standard protocols is recommended as an action.*                                                                                                                                                                                                                              |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Radar/lidar studies                                                                                                                                                                                                                                                             | No central repository -- requires development                                                                                                                                             | *Development of a database with the flexibility to accommodate multiple technologies, study designs, and data outputs is recommended as an action.*                                                                                                                                                          |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Large raw file types (e.g., high definition aerial photos, thermal video, raw acoustic files)                                                                                                                                                                                   | No central repository -- requires development                                                                                                                                             | -   *Retention of large, raw file types could allow for future QA/QC and re-evaluation with updated analysis or automated identification tools.*                                                                                                                                                             |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           |                                                                                                                                                                                                                                                                                                              |
|                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                           | -   *Development of a data repository is recommended as a cross-taxa action.*                                                                                                                                                                                                                                |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## Data Collection

In coastal and marine environments, a wide variety of field research methods can inform scientific understanding of avian interactions with offshore wind facilities (for common methods and recent advances, see [@courbis2023; @orjip2022; @nrel2022]. As part of Construction and Operations Plans (COPs), offshore wind developers are developing and submitting avian monitoring plans.
Current available draft monitoring plans typically include deploying Motus and/or satellite tags on birds of conservation concern for a specified number of years post-construction, deploying and maintaining Motus receiver stations for a specified number of years, deploying passive acoustic or multi-sensor detectors on turbines or other offshore wind facility infrastructure, and conducting boat-based or aerial surveys.
State agencies, federal agencies, and conservation and research organizations regularly deploy tags, deploy and maintain Motus stations, and conduct surveys of nesting birds within the RWSC Study Region.
Standardized boat-based and aerial surveys are also conducted with state and federal funding.

As part of addressing near and long-term goals, and in the context of ongoing work, the Bird & Bat Subcommittee recommends the following field research, data interpretation, and technology advancement activities:

-   **Using appropriate methods to further characterize movements, distributions, and abundance of wide-ranging bird species offshore, before and after construction.**

    -   **The Bird & Bat Subcommittee will convene regularly to coordinate tagging/tracking efforts for species of interest** in the context of offshore wind along the U.S.
        Atlantic Coast.
        Activities will include identifying general focal locations and focal species for tag deployment, exploring the potential to centralize tag deployment efforts, and coordinating deployment, calibration, and maintenance of Motus receiver network infrastructure.

    -   **Coordinating and conducting regular digital aerial surveys that cover multiple lease areas and appropriate buffer zones** using a standardized methodology.
        As wind energy areas are leased and developed, aerial surveys covering individual lease areas plus appropriate buffers (see [draft guidance](https://www.nyetwg.com/avian-displacement-guidance)) can be expected to survey portions of adjacent lease areas, so coordination could provide cost-efficiencies, as well as supporting standardized data products.

    -   **Deploying passive acoustics and multi-modal systems at offshore wind facilities and on other offshore infrastructure** to monitor for nocturnal migrants.

-   **Continuing standardized breeding bird surveys along coastlines and on islands** to understand population dynamics, assess species distributions, and inform population models (see [Data Analysis](#birds_dataanalysis)).

-   **Expanding seabird diet and foraging studies** to inform understanding of offshore wind facility effects.
    Conducting laboratory analyses of previously stored samples, as needed.

-   **Deploying multi-modal systems on turbines to assess bird interactions with wind turbine infrastructure** (including micro-avoidance and collision risk).
    Combinations of acoustic detectors, radar systems, impact detection sensors, and/or visual, thermal, and infrared cameras are recommended to document bird behavior around wind turbines, detect impacts, and, to the extent possible, provide species-specific identification.

-   In addition to the methods detailed above, **deployment of radar or lidar systems** to document bird passage rates and flight heights is also recommended.

-   **Developing, testing, and advancing new, emerging, or under-utilized technologies for monitoring and mitigation.**

    -   **Testing and validating bird collision detection systems** (recognizing that initial validation may need to focus on land-based wind facilities, where carcass counts are possible).

    -   **Testing and validating the efficacy of on-site mitigation strategies** (e.g., lighting, painted blades), including evaluation in both land-based and offshore environments.

    -   **Testing and validating the efficacy of off-site mitigation strategies or voluntary conservation offsets.** (This is expected to take place only after the planning for and identification of appropriate options as described under [Data Analysis](#birds_dataanalysis).)

    -   **Improving remote access to wildlife monitoring equipment** on wind turbine platforms or other offshore infrastructure.
        This could include identifying workflows to allow for the transmission of wildlife monitoring data using existing wind facility fiber-optic networks.

    -   **Scoping and designing standardized spaces on offshore wind infrastructure to support wildlife monitoring equipment,** including physical access, electrical power, data transfer capabilities, etc.
        This will require cross-sector and cross-taxa coordination.

    -   **Designing and improving automated methods to efficiently derive data from raw data files**, such as deriving species identification and counts from digital aerial photographs, species identification within acoustic recordings, or tracking movement paths on radar and video recordings.

    -   **Developing and improving tagging technologies** to allow for lighter tags, longer-term tracking, measurement of additional parameters, or more precise measurement (e.g., of flight height).

## Data Analysis {#birds_dataanalysis}

Data analyses and summaries should 1) inform where new data collection is needed, 2) characterize avian distribution patterns, density, movements, behavior, and population dynamics, 3) assess whether offshore wind is causing any observed changes, 4) assess the impacts of those changes on bird populations, and/or 5) evaluate the efficacy of monitoring or mitigation strategies.

To address current needs, the Bird & Bat Subcommittee recommends:

-   Compilation and synthesis of best available information to build, maintain, and regularly update a shared exposure/risk vulnerability matrix for both marine and land-based bird species.
    This matrix will be used to identify focal species by geography, lease area, and potential impact of research interest.

-   Continued development and updating of models of bird density, movements, behavior, and population dynamics in coastal and marine ecosystems, including:

    -   Regularly updating marine bird distribution models and maps based on at-sea observations.

    -   Analyzing existing tracking data from multiple sources to develop pre-construction baselines (e.g., movements, distributions, behavior) for focal species.

    -   Incorporating data from multiple methods (e.g., at-sea surveys, tracking, radar) and covariates (oceanographic, meteorological, prey distribution estimates) into integrated models.

    -   Identifying key metrics and summarizing relevant data (e.g., movement metrics, distribution and abundance, flight height, flight speed, micro-avoidance, meso-avoidance) to inform vulnerability assessments and collision risk models.

    -   Analyzing and summarizing available seabird diet data to inform potential effects of offshore wind energy on foraging.

    -   Summarizing available population demographic data to develop updated population models and assess potential population-level impacts for focal species.

    -   Developing regional-scale power analyses to inform regional-scale study designs.

-   Advanced planning, development, and assessment of off-site conservation measures to provide compensatory mitigation ("no net loss") or support voluntary conservation efforts.

-   Review of available cumulative effects literature and adoption of a clear framework for assessing cumulative effects.

-   Consultation with the Bird & Bat Subcommittee prior to conducting analyses of coastal and offshore avian data to ensure that the research leverages all available data and contributes to addressing key issues and data gaps.

-   Collaboration among Subcommittees and with outside experts to ensure cross-taxa issues are being addressed.
    For example:

    -   Supporting information sharing and consistency in offshore study recommendations across Subcommittees, where possible.

    -   Working with the Habitat & Ecosystem Subcommittee and fish experts to ensure that collected data and data products include important bird habitat variables and prey species.

    -   Working with the Marine Mammal Subcommittee to coordinate with and train Protected Species Observers/Marine Mammal Observers to monitor and report dead and injured birds found on vessels.
