# Executive Summary {#sec-executive-summary .unnumbered}

Four sectors (U.S. federal agencies, Atlantic coast states, offshore wind companies, and environmental nonprofits) formed the [Regional Wildlife Science Collaborative for Offshore Wind](https://rwsc.org/) (RWSC) and collectively developed this Science Plan to inform ongoing offshore wind, wildlife, and habitat[^executive-summary-1] data collection and research in U.S.
Atlantic waters, to identify gaps and needs for research and data collection, and to describe a framework for collaboration to address those needs[^executive-summary-2]
.

This framework for collaboration represents critical progress in facilitating the [states' policies and the federal administration's goals](https://www.energy.gov/eere/wind/articles/offshore-wind-market-report-2023-edition) to procure and ensure development and operation of offshore wind power in a manner that seeks to avoid, minimize, and mitigate impacts to wildlife and the environment while promoting ocean co-use.
Furthermore, the collaborative actions described below help fulfill the [U.S. Ocean Climate Action Plan's](https://www.noaa.gov/sites/default/files/2023-03/Ocean-Climate-Action-Plan_Final.pdf) direction to federal agencies to integrate and coordinate across the federal government to advance offshore wind by increasing scientific research and improving data sharing and access.

This Executive Summary provides an overview of the Science Plan's research recommendations and describes how RWSC will facilitate Science Plan implementation and track progress.

## **Summary of Research Recommendations**

To develop the Science Plan, the RWSC Steering Committee convened six expert Subcommittees — Marine Mammal, Bird & Bat, Sea Turtle, Habitat & Ecosystem, Protected Fish Species, and Technology.
Contributors spanned the federal agencies, states, offshore wind companies, environmental nonprofits, academic and research institutions, and other private entities.
RWSC received comments and input from these groups and the public that greatly improved this Plan (see [Science Plan Review & Revision Process](review.qmd)).

This section consolidates the detailed recommendations to the RWSC Steering Committee made by each Subcommittee in the Science Plan to address data gaps and needs.
Each Subcommittee's chapter provides more information about the geographies where certain activities should occur, ecological and logistical considerations for implementing recommendations, and the entities who are leading existing work.
The Sector Caucuses expect that for the RWSC to implement these recommendations, many different science entities may take on roles to fund, guide, or otherwise support the work needed to address the recommendations based upon the entity's expertise, capacity, available resources, and existing data collection, research, and data management portfolio.

::: column-body
The recommendations are as follows:

1.  **Leverage the existing data management infrastructure within the federal government and private sector.** **Encourage agencies and entities responsible for managing and funding existing repositories coordinate via the RWSC to understand and anticipate the needed capacity and functionality given the volume and variety of offshore wind and wildlife data being collected.**

2.  **Seek to apply consistent data collection, QA/QC, data management, data storage, and data sharing guidance for all offshore wind and wildlife studies, as developed or recommended by each Subcommittee.**

3.  **Work with offshore wind companies, agencies, contractors/vendors, and researchers to encourage specific collaboratives, data sharing agreements, and tools that facilitate appropriate access to key datasets for use in decision-making and research.**

4.  **Seek to fund data collection and research tailored to the mix of species present and the need for baseline data**[^executive-summary-3] **in each subregion, according to each chapter in the Science Plan.**

    -   Encourage new data collection activities to align with the objectives of the NOAA Fisheries and BOEM Federal Survey Mitigation Strategy, if applicable.

    -   Continue to assess the need for and conduct as necessary baseline data collection for relevant species and improve collection for species that are relatively data-poor, including sea turtles, bats, and protected fish species.
        Monitor species' movement in, and use of, wind energy areas and adjacent areas consistently in U.S.
        Atlantic waters.

    -   Baseline data collection should continue in areas where leasing and construction is planned.
        The focus for currently leased and progressing areas in Southern New England and New York/New Jersey Bight should be to conduct project-level monitoring studies using consistent methods and approaches to characterize potential impacts from construction and operation.

    -   Encourage consistent methods and approaches for data collection, data analysis, and data management efforts to support regional scale assessments and the development and maintenance of regional data products and tools.

5.  **Encourage using RWSC to coordinate research planning, data collection, data analysis, and data management for the following types of offshore wind-related wildlife surveys and sensor networks throughout the study area funded by multiple entities that benefit from regional collaboration:**

    -   Long-term archival passive acoustic monitoring for marine mammal monitoring and soundscape characterization.

    -   Conduct tagging and visual surveys of marine mammals and sea turtles to provide the most complete information and context about marine mammal and sea turtle distribution, habitat use, and behavior.

    -   Acoustic telemetry receiver network and tagging efforts for sea turtles and protected fish species.

    -   Performance evaluation of new technologies for mitigation and long-term monitoring of protected species.

    -   Motus (radio telemetry) receiver network and tagging efforts for birds and bats.

    -   Repeated, regular, high-definition aerial photography surveys that cover multiple contiguous and proximate lease areas and characterize multiple taxa.

    -   Seafloor habitat data collection and compilation, including sensitive hard bottom and coral habitats.

    -   Deployment of multi-sensor oceanographic and ecological buoys in areas of high biodiversity and/or habitat value.

6.  **Optimize the design of surveys and sensor networks to detect broad scale phenomena such as species displacement, changes in abundance, and/or changes in behavior and health using power analyses or other statistical tools.**

7.  **Continue to update existing Atlantic coast-wide species distribution models (marine mammals, seabirds, sea turtles) and develop new models with the latest at-sea observations, movement data, and environmental data every 2-3 years.** **Produce and maintain a standardized set of regional seafloor habitat and oceanographic data products for use as covariates in species distribution modeling and other analyses.**

8.  **As per the National Academies of Sciences recommendations, conduct oceanographic observations and modeling to differentiate changes to hydrodynamics from climate change and offshore wind development at turbine, windfarm, and broader scales.**

9.  **Expand on and link existing studies of prey species, including plankton, across the Atlantic to establish a broader ecosystem wide observing system that can detect patterns, trends, and trophic linkages.**

10. **For studies of potential impacts, consider following existing guidance and best practices for study design and analysis as compiled by the Subcommittees for consistency and leverage the opportunity to combine individual studies into broader regional scale analyses.**

11. **Advance technologies to improve wildlife detection and impact mitigation and ensure consistent technology performance evaluation.**
:::

## **Implementing the Science Plan -- a Framework for Collaboration**

To ensure that the data collection and research efforts recommended in the Science Plan are Findable, Accessible, Interoperable, and Reusable (FAIR)[^executive-summary-4], the four Sectors have recommended a voluntary framework for collaboration through the RWSC.
This framework has three primary goals:

1.  Promote coordination of regional offshore wind related wildlife research with the RWSC, regardless of funding source, recipient(s), or funding structure.

2.  Ensure that data collection and research methods and products (i) meet the needs of decision-makers, (ii) are scientifically sound, (iii) standardized, and (iv) made available for use as soon as feasible or appropriate to inform and improve decision-making.

3.  Communicate the findings and results of individual and collaborative research.

RWSC welcomes and encourages participation from all entities and individuals in implementing this Science Plan, especially via expert Subcommittee meetings[^executive-summary-5].
To assist in the implementation of the Science Plan, the RWSC will maintain the [Offshore Wind & Wildlife Research Database](https://database.rwsc.org/) and continue to provide tools and forums for research planning, discussions, and collaboration among all participants.
All are encouraged to participate in implementing the Science Plan by:

-   **Maintaining situational awareness of data collection and research activities to identify opportunities for collaboration, consistency, and efficiency.** This can be accomplished in part by participating regularly in RWSC Sector Caucus and expert Subcommittee meetings and by encouraging relevant grantees, contractors, and researchers to share project information with the RWSC.
    Several RWSC participants have noted the value of Subcommittee meetings as forums for sharing research plans, discussing emerging issues, and working together across sectors to advance Science Plan objectives.
    The Subcommittees will continue to meet regularly to share information on the latest study results, ongoing and planned research and data collection, and to periodically review data management infrastructure needs and workflows.
    Entities will be able to coordinate as needed with the relevant RWSC Subcommittee(s) prior to new data collection (to ensure consistency and reduce duplication) and analysis (to facilitate access to the available data) and share details about where and when activities take place to avoid conflicts.
    The RWSC will facilitate this objective via the [Offshore Wind & Wildlife Research Database](https://database.rwsc.org/), web mapping tools, and a data catalog (in development).

-   **Collaboratively implementing and encouraging the use of best practices for data collection, QA/QC, data management, and storage as specified in this Science Plan.** Each Subcommittee has recommended practices for each relevant data type or data collection method in the Science Plan.
    To encourage uptake and consistent use of these practices, the RWSC will provide suggested language, agreed to by the Sector Caucuses, around data management for participants to use in their own requests for proposals and agreements.

-   **Participating in annual discussions of research priorities.** The RWSC provides a forum to identify data and research needs based on current data gaps, new research results, emerging decision-making needs, and available funding.
    To facilitate an adaptive approach to prioritizing the recommendations in the Science Plan, RWSC will convene the sectors each year to review and discuss research priorities.
    Discussions will be informed by the expert Subcommittees' work, collaborative workshops, and agreed upon prioritization criteria.

-   **Aligning funds and developing collaborative funding plans.** Through annual research prioritization discussions, the RWSC will provide opportunities for participants to voluntarily align their existing research funds to address Science Plan objectives when it makes sense to do so.
    The RWSC also provides a mechanism for pooling funds to accomplish shared priorities when practical, administering funds, and managing research projects that accomplish Science Plan goals.

RWSC also envisions and welcomes uses of this Science Plan for purposes other than their direct coordination on offshore wind and wildlife data collection and research in U.S.
Atlantic waters:

-   The Science Plan and its development process can be used as an example for regional offshore wind science entities in other geographies.

-   The greater scientific community can use this plan to shape their own research objectives and inform their funding decisions related to offshore wind and wildlife efforts.

-   The RWSC Science Plan can be used to support multi-sector collaborations to advance career workforce development programs for ecological and biological monitoring roles.
    The Science Plan serves as a guide to identify the scientific disciplines, the types of roles and the skills (including the educational requirements) necessary to address the research questions[^executive-summary-6].

RWSC will reassess the Science Plan and framework for collaboration every five years to ensure its continued utility and relevance in light of new information and changes in the rapidly evolving offshore wind industry.
The RWSC will track progress on Science Plan recommendations annually.

[^executive-summary-1]: For the coordination of offshore wind and fisheries research activities, see the Responsible Offshore Science Alliance, https://www.rosascience.org.

[^executive-summary-2]: Neither the RWSC nor any of its Subcommittees are established or utilized by a Federal agency for the purpose of obtaining advice or recommendations on issues or policies for any agency.

[^executive-summary-3]: “Baseline data” in the Science Plan generally refers to data describing ecological conditions prior to offshore wind development activities, and should not be considered a regulatory definition.
    Use of a baseline or benchmark for purposes of comparing conditions before and after a disturbance or change is an essential part of any environmental analysis within a research project.

[^executive-summary-4]: Wilkinson, M.D., et al., 2016.
    The FAIR Guiding Principles for scientific data management and stewardship.
    Scientific Data 3, 160018.
    <https://doi.org/10.1038/sdata.2016.18>.

[^executive-summary-5]: Subcommittee meeting information is posted publicly and open to all interested participants: https://rwsc.org/events.

[^executive-summary-6]: [STEM Workforce Development and the RWSC Integrated Science Plan](https://rwscorg-my.sharepoint.com/:b:/g/personal/admin_rwsc_org/EcjvcnLLW9VOiBDJB2493iIBeNSbskh3xtaIHs1WW28L2A?e=CSVeEY)
