# Welcome {.unnumbered}

This is the website for the **Integrated Science Plan for Offshore Wind, Wildlife, and Habitat in U.S. Atlantic Waters**.

The RWSC Steering Committee, state and federal government agencies, offshore wind companies, environmental nonprofits, and RWSC's host entities---the Northeast Regional Ocean Council and Mid-Atlantic Regional Council on the Ocean with the Coastal States Stewardship Foundation---collaboratively developed the Science Plan to inform future data collection and research.

-   RWSC is serving as a coordination hub for offshore wind research to increase collaboration, limit redundancy, suggest common data standards, and increase data sharing and transparency.

-   The Science Plan describes data and research needs for the larger community, whether funded by the RWSC or not.

-   The Science Plan provides a framework for the RWSC Steering Committee when making decisions on what projects to fund via the RWSC.

## Format

The Science Plan is written in plain text documents using RMarkdown.
All of the text and code to generate the website is stored in the [Science Plan GitHub Repository](https://github.com/RWSCollab/science-plan).
The Science Plan's website is built by GitHub Actions, which runs code every time RWSC makes a change.
This ensures that content is up-to-date and versions are tracked.
The current version information and preferred citation is below.

This approach was inspired by and leverages the resources made by the [Openscapes](https://openscapes.org/) initiative and the [Openscapes Approach Guide](https://openscapes.github.io/approach-guide/) that was built with [Quarto](https://quarto.org/).

## Providing Feedback

The best way to provide feedback on the Science Plan is to [contact RWSC directly](https://rwsc.org/contact) and join [upcoming Subcommittee meetings](https://rwsc.org/events).

To provide feedback specific to this Science Plan website, and if you have a GitHub account, you can [submit an issue](https://github.com/RWSCollab/science-plan/issues/new/choose) (e.g., typo fixes, citation updates and additions).

## Citation

RWSC (Regional Wildlife Science Collaborative for Offshore Wind).
2024.
Integrated Science Plan for Offshore Wind, Wildlife, and Habitat in U.S.
Atlantic Waters.
Version 1.0.
https://rwsc.org/science-plan.
Accessed MM-DD-YYYY.

## Acknowledgements {.unnumbered}

The Science Plan was developed by the RWSC Steering Committee based on recommendations from the RWSC Subcommittees and a variety of other experts.

## License {.unnumbered}

This website is free to use, and is licensed under the [Creative Commons Attribution-NonCommercial-NoDerivs 3.0 License](http://creativecommons.org/licenses/by-nc-nd/3.0/us/).
