---
bibliography: references.bib
---

# Marine Mammals {#sec-marine-mammals}

*Authors: [Marine Mammal Subcommittee](append-rosters.qmd#mm)*

*For more detail on any of these topics, read the [Marine Mammals Appendix](append-mm.qmd).*

This chapter builds on the research topics and questions related to marine mammals and offshore wind proposed by several groups over the last decade that should be addressed by a regional collaborative [@njrmi2021; @kershaw; @kraus2019; @regionalsynthesisworkgroupoftheenvironmentaltechnicalworkinggroup; @southall2021].
The RWSC Marine Mammal Subcommittee considered these previous bodies of work in developing the following recommendations.
In doing so, they have also highlighted these concepts:

-   Future work will be aligned and coordinated with research needs and actions described in the NOAA Fisheries and BOEM Draft North Atlantic Right Whale Offshore Wind Strategy [@noaafisheries2022] and the NOAA Fisheries and BOEM Federal Survey Mitigation Strategy [@hare2022].

-   Disentangling the impacts to marine mammals from climate change from any potential effects from offshore wind development will be a major challenge.
    Attempts to establish a "baseline" representative of the past several decades must acknowledge that the environment changed rapidly over that time and continues to change rapidly.
    In addition, climate change increases the uncertainty surrounding marine mammal behavior, distribution, and demography, which can abruptly and unexpectedly increase the risks associated with offshore wind development if marine mammals begin to use new areas and habitats or existing habitat more frequently or during different times of year.

-   A key contribution of the RWSC Science Plan is the ability to look across all the various data collection activities and identify opportunities for synthesis.

-   Assigning causality to observed changes may not be possible in all studies.

## Data Management

Understanding marine mammal movement and behavior near offshore wind developments will require close coordination among researchers, state and federal agencies, and industry.
The Marine Mammal Subcommittee will work with individuals and entities who conduct research to ensure that data are collected and stored in consistent formats that allow comparisons and pooling across individual projects in the RWSC study area.
This standardization is intended to support regional-scale assessments and the development and maintenance of regional data products and tools (e.g., marine mammal density models).

To support these efforts, the Marine Mammal Subcommittee recommends:

-   Maintenance of an up-to-date resource list of recommended repositories, data and metadata standards, guidance, and protocols for use by all data collectors.
    The current recommended resources are detailed in the table below.

-   Development of standard language for inclusion in requests for proposals and funding agreements to encourage or require the use of recommended resources.

-   Establishment of data sharing workflows, including formal agreements if necessary, to appropriately manage access to sensitive industry-collected datasets necessary for research (e.g., acoustic data, Protected Species Observer data).

-   Collaboratively establish recommended timelines for marine mammal detection data upload and dissemination, especially through public platforms and apps, e.g., WhaleAlert, WhaleMap.

The following table lists the repositories and standards that are recommended for use in marine mammal data collection and identifies data types for which no or limited data management capacity (i.e., standard repositories and guidance) currently exists.

Table 1.
Recommended repositories and standards for marine mammal data collection.

+--------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Method(s) and data type(s)**                                                                                                                   | **Repository**                                                                                                                                                                                                                                                                                                                     | **Existing Standards**                                                                                                                                                                                                                                                                                                                                                    |
+--------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Raw passive acoustic data and passive acoustic data products (ambient noise metrics, species detections)                                         | [**NOAA NCEI Passive Acoustic Data Archive**](https://www.ncei.noaa.gov/products/passive-acoustic-data)                                                                                                                                                                                                                            | Use [RWSC Data Management and Storage Best Practices for Long-term and Archival Passive Acoustic Monitoring Data](https://rwscollab.github.io/pam-data-mgmt/)                                                                                                                                                                                                             |
|                                                                                                                                                  |                                                                                                                                                                                                                                                                                                                                    |                                                                                                                                                                                                                                                                                                                                                                           |
|                                                                                                                                                  | [**NOAA Passive Acoustics Reporting System**](https://www.fisheries.noaa.gov/resource/document/passive-acoustic-reporting-system-templates)                                                                                                                                                                                        | -   Detection data, metadata, GPS data, and ambient noise data should be provided via the [formatted spreadsheets](#0) to the Northeast Passive Acoustic Reporting System via [nmfs.nec.pacmdata\@noaa.gov](#0) within 90 days of the retrieval of the recorder or data collection. The data will be displayed on the Passive Acoustic Cetacean Map and shared with RWSC. |
|                                                                                                                                                  |                                                                                                                                                                                                                                                                                                                                    |                                                                                                                                                                                                                                                                                                                                                                           |
|                                                                                                                                                  |                                                                                                                                                                                                                                                                                                                                    | -   Use [PassivePacker](https://www.ncei.noaa.gov/products/passivepacker) to submit raw acoustic data and metadata to NCEI.                                                                                                                                                                                                                                               |
+--------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Real-time marine mammal sightings (including live, dead, or distressed whales)                                                                   | [**Whale Alert**](https://www.whalealert.org/)                                                                                                                                                                                                                                                                                     | <https://www.whalealert.org>. The report should include time, location, and number of animals.                                                                                                                                                                                                                                                                            |
+--------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Observational surveys; line-transect data; telemetry data; acoustic monitoring; photo identification; oceanographic data products; model outputs | [**OBIS-SEAMAP**](https://seamap.env.duke.edu/)(Ocean Biogeographic Information System -- Spatial Ecological Analysis of Megavertebrate Populations)                                                                                                                                                                               | [OBIS-SEAMAP minimum data fields and acceptable formats,](https://seamap.env.duke.edu/content/provider_faq) Duke Marine Geospatial Ecology Lab                                                                                                                                                                                                                            |
+--------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Tagging data, oceanographic data                                                                                                                 | [**Ocean Tracking Network**](https://oceantrackingnetwork.org/) **(**OTN) Data Centre                                                                                                                                                                                                                                              | [OTN Data Policy](https://members.oceantrack.org/data/policies/otn-data-policy)                                                                                                                                                                                                                                                                                           |
|                                                                                                                                                  |                                                                                                                                                                                                                                                                                                                                    |                                                                                                                                                                                                                                                                                                                                                                           |
|                                                                                                                                                  |                                                                                                                                                                                                                                                                                                                                    | [OTN Data Templates](https://members.oceantrack.org/data/data-collection)                                                                                                                                                                                                                                                                                                 |
+--------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Satellite tagging data                                                                                                                           | [**Animal Telemetry Network**](https://ioos.noaa.gov/project/atn/) (ATN)                                                                                                                                                                                                                                                           | [Animal Telemetry Network DAC Data Management Policy Guidance](https://cdn.ioos.noaa.gov/media/2022/03/ATN-DAC-Data-Management-Policy-Guidance_v.202201.pdf): includes data [submission requirements](https://atn.ioos.us/help/submit-data/) and instructions for submitting project-level metadata and deployment records.                                               |
+--------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Observational data; Photography                                                                                                                  | [**North Atlantic Right Whale Consortium**](https://www.narwc.org/) (NARWC)                                                                                                                                                                                                                                                        | Use NARWC [data and metadata submission guidelines](https://www.narwc.org/photo-and-data-submission.html)                                                                                                                                                                                                                                                                 |
+--------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Tissue samples                                                                                                                                   | [**National Marine Mammal Tissue Bank**](https://www.fisheries.noaa.gov/national/marine-mammal-protection/national-marine-mammal-tissue-bank) (NIST maintains the NMMTB as part of the [NIST Biorepository](https://www.nist.gov/programs-projects/nist-biorepository) (formerly known as the Marine Environmental Specimen Bank)) | [National Marine Mammal Tissue Bank Sample Collection Form](https://media.fisheries.noaa.gov/2022-07/NMMTB%20Field%20DataSheet-OMB%20Form%20-%20expires%2006-30-2024_0.pdf)                                                                                                                                                                                               |
|                                                                                                                                                  |                                                                                                                                                                                                                                                                                                                                    |                                                                                                                                                                                                                                                                                                                                                                           |
|                                                                                                                                                  |                                                                                                                                                                                                                                                                                                                                    | [National Marine Mammal Tissue Bank Request Form](https://media.fisheries.noaa.gov/2022-07/NMMTB%20Tissue%20Request%20Form_OMB%20Form_expires%2006-30-2024_0.pdf)                                                                                                                                                                                                         |
|                                                                                                                                                  |                                                                                                                                                                                                                                                                                                                                    |                                                                                                                                                                                                                                                                                                                                                                           |
|                                                                                                                                                  |                                                                                                                                                                                                                                                                                                                                    | [National Marine Mammal Tissue Bank Specimen Access Policy](https://media.fisheries.noaa.gov/2022-07/NMMTB_Tissue%20Access%20Policy_OMB%20Form_expires%2006-30-2024.pdf)                                                                                                                                                                                                  |
+--------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Marine mammal strandings and entanglements                                                                                                       | [**Marine Mammal Health and Stranding Response Program**](https://www.fisheries.noaa.gov/national/marine-life-distress/marine-mammal-health-and-stranding-response-program)                                                                                                                                                        | [Report a stranded marine mammal](https://www.fisheries.noaa.gov/report)                                                                                                                                                                                                                                                                                                  |
|                                                                                                                                                  |                                                                                                                                                                                                                                                                                                                                    |                                                                                                                                                                                                                                                                                                                                                                           |
|                                                                                                                                                  |                                                                                                                                                                                                                                                                                                                                    | [Report an entangled marine mammal](https://www.fisheries.noaa.gov/national/marine-life-distress/report-entangled-marine-mammal)                                                                                                                                                                                                                                          |
+--------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Calanus abundance observations                                                                                                                   | **Gulf of Maine MBON -- [NERACOOS ERDDAP](https://www.neracoos.org/erddap/search/index.html?page=1&itemsPerPage=1000&searchFor=wbts)**                                                                                                                                                                                             | Access is public via ERDDAP                                                                                                                                                                                                                                                                                                                                               |
+--------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Protected Species Observer (PSO) data                                                                                                            | Under development: NOAA and BOEM **Master Protected Species Observer Sightings Database**                                                                                                                                                                                                                                          | Under development                                                                                                                                                                                                                                                                                                                                                         |
+--------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| High-definition aerial imagery                                                                                                                   | None; records of observations from photos go to OBIS-SEAMAP                                                                                                                                                                                                                                                                        | None -- needs development                                                                                                                                                                                                                                                                                                                                                 |
+--------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| eDNA                                                                                                                                             | None -- needs development                                                                                                                                                                                                                                                                                                          | None -- needs development                                                                                                                                                                                                                                                                                                                                                 |
+--------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## Data Collection

Several entities are requiring, funding, and/or advocating for marine mammal research and data collection activities with respect to offshore wind.
Ongoing and planned activities, including marine mammal monitoring that is being required by agencies, are captured in the [Offshore Wind & Wildlife Research Database](https://database.rwsc.org/).

Individuals and entities should consult with the Marine Mammal Subcommittee prior to collecting marine mammal data with respect to offshore wind to ensure that any new data collection does not duplicate existing efforts and is consistent with the tools and approaches already in use.
Any individual or entity may join public Marine Mammal Subcommittee meetings by obtaining meeting links on the RWSC website.

A combination of methods (visual, acoustic, tagging) is recommended to provide the most complete information and context to marine mammal observations, given the strengths and limitations of each method alone (see the [Marine Mammal Appendix](append-mm.qmd) for more information):

-   (Cross taxa) Leveraging BOEM's and NOAA's ongoing efforts, ensure that the required Protected Species Observer data collected by offshore wind companies during construction and operations via Pile Driving Monitoring Plans and Vessel Strike Avoidance Plans (and any other mitigation plans) follows a consistent reporting approach and is eventually submitted to a Master Protected Species Observer Sightings Database for use in marine mammal analyses and research.

-   Ensure that other marine mammal and environmental data collection required by the agencies during installation (e.g., sound fields, visual monitoring, PAM, thermal/infrared camera systems) are collected using consistent methods such that data can be used in other analyses and research including broader scale analyses of potential impacts across many projects.

-   (Cross-taxa) Continue regional scale protected species and habitat data collection activities through the [Atlantic Marine Assessment Program for Protected Species](https://www.fisheries.noaa.gov/new-england-mid-atlantic/population-assessments/atlantic-marine-assessment-program-protected) (AMAPPS), [Ecosystem Monitoring Survey](https://www.fisheries.noaa.gov/feature-story/monitoring-northeast-shelf-ecosystem); [NOAA Fisheries North Atlantic Right Whale Aerial Surveys](https://www.fisheries.noaa.gov/resource/document/north-atlantic-right-whale-sighting-survey-reports), NOAA Fisheries Marine Mammal and Sea Turtle Aerial Surveys, NOAA Fisheries Marine Mammal, Sea Turtle, and Seabird ship-based surveys; NOAA Fisheries Seal aerial abundance surveys.
    Advance the NOAA Fisheries and BOEM Survey Mitigation Strategy [@hare2022] to ensure that site-specific and regional scale studies are put in the context of population trends and ecosystem conditions.

-   (Cross-taxa) Coordinate regular high-definition aerial surveys that cover multiple lease areas using the same tools and methods.
    This effort should leverage the considerable amount of high-definition aerial photography data collected during site assessment by multiple offshore wind developers, and the [Southern New England megafauna aerial surveys](https://www.masscec.com/resources/marine-mammal-and-sea-turtle-surveys) that have occurred consistently since 2011.

-   Continue to support the adaptive design and implementation of a regional [long-term archival passive acoustic monitoring network in the Atlantic Ocean](https://rwsc.org/pam) and guide future research including:

    -   Characterize baseline ambient sound and sound/noise during all phases of development, leveraging the regional passive acoustic monitoring network.

    -   Expand passive acoustic monitoring outside of wind energy areas, especially along the shelf break, including using gliders and real-time systems.

    -   To the extent practicable, ensure alignment between archival and real-time deployments.
        Ensure that whale detections from real-time systems can be folded into analyses and data products that also leverage archival detections.

    -   Incorporate collection of oceanographic data and prey fields into the regional-scale PAM network.

    -   Improve estimates of acoustic detection rates and cue rates of baleen whales during non-construction conditions.

    -   Improve dose-response curves by obtaining in-situ behavioral data at offshore wind construction sites on baleen whale responses to pile driving noise.
        This would require collecting a range of data types including PAM and visual observations (aerial or ship-based).

    -   Couple aerial/visual monitoring with acoustic monitoring to address the issues above and better link the resulting observational datasets.

    -   Co-deploy acoustic telemetry receivers to build out a telemetry receiver network, and other sensors as practicable.

-   Collect marine mammal behavioral and health data through tagging and visual observations to determine how individuals interact with wind farm structures and whether changes to foraging, socializing, or reproduction are occurring.

-   In collaboration with NOAA Fisheries, continue and expand stranding data collection and analysis with respect to strandings and mortality data time series analysis for the U.S.
    Atlantic Ocean.

-   Monitor entanglement with subsea structure of floating offshore wind structures and monitor secondary entanglement where derelict fishing gear/marine debris may attach to subsurface offshore wind structures.

-   Advance oceanographic and biological data collection and use in marine mammal research.

    -   Coordinate with the North East Regional Association of Coastal and Ocean Observing Systems (NERACOOS), Mid-Atlantic Regional Association of Coastal Ocean Observing Systems (MARACOOS), and Southeastern Coastal Ocean Observing Regional Association (SECOORA).

    -   Leverage existing ocean observing platforms or add new ocean observing assets for marine mammal monitoring.

    -   Work with the Habitat & Ecosystem Subcommittee to ensure that key oceanographic and habitat data are collected and available as data products for use in marine mammal studies and as model covariates.

    -   Work with the Habitat & Ecosystem Subcommittee to determine whether offshore wind structures alter hydrodynamics, stratification, and mixing, and/or prey distribution and abundance.

    -   Continue to collect data across the region that allows analysis and synthesis of prey fields.
        Develop a coordinated regional scale zooplankton monitoring and mapping effort that builds off of and links existing surveys and studies including programs monitoring dimethyl sulfide, EcoMon, Continuous Plankton Recorder, the Gulf of Maine MBON, BOEM-funded Zooplankton Ecology study, Canadian AZMP, Center for Coastal Studies, Northeast U.S. Shelf LTER, and projects conducted by Stony Brook University and Rutgers University to establish a broader ecosystem observing system, synthesize patterns, and identify trends and linkages across trophic levels.

There is a need to advance technologies that improve marine mammal detection during all phases of offshore wind development, and to ensure that the performance of new technologies is evaluated consistently (see the [Technology Chapter](technology.qmd)):

-   Develop, evaluate performance, and apply existing and emerging technologies that enhance marine mammal detection, including thermal cameras, infrared cameras, passive acoustics systems, and systems that integrate multiple methods for use during construction and operational monitoring and mitigation.
    Test "smart" mitigation methods triggered by marine mammal presence as determined by these systems.

-   Advance quieting technologies meant to mitigate construction noise (piledriving, vessel traffic) and operational noise (vessel traffic, operational vibratory sound).

-   Develop and deploy safe long-duration satellite tagging telemetry technology for tracking high-resolution movements of marine mammals in and around offshore wind structures.

-   Improve analysis of monitoring data through artificial intelligence, automated acoustic, and image processing, and near real-time data availability.

-   (Cross taxa) Develop and test eDNA assays/surveys/sampling regimes to understand efficacy of use developing indices of occurrence/abundance, including testing the effect of carcasses in the environment on eDNA detection.

The **Gulf of Maine** has long represented important feeding grounds for baleen whales from late fall to early spring [@noaacetsound2015].
A resident population of Harbor porpoise is present in the coastal/nearshore areas of the Gulf of Maine from July to September [@noaacetsound2015].
Almost all of the Gulf of Maine subregion is critical habitat (Northeastern U.S. foraging area) for North Atlantic right whales.
Given that offshore wind development areas are still being identified in this subregion, baseline data collection should seek to characterize fine scale spatial and temporal habitat use.
Studies of impacts specific to floating offshore wind (e.g., secondary entanglement), including modeling, should be coordinated through the Subcommittee.
Cape Cod Bay, as a historical whale aggregation location, could serve as a sentinel site or control site to monitor potential population-level impacts to whales.

In **Southern New England**, known whale foraging hotspots (e.g., Nantucket Shoals) should be monitored using multiple methods to understand potential changes in behavior and habitat use.
Studies of hydrodynamics and physical oceanography at the turbine- and wind farm-scales should seek to disentangle climate change drivers from offshore wind development and understand any changes that may impact whale prey [@acp2023; @nasem2023].

Whale and dolphin sightings in the **New York/New Jersey Bight** have increased recently and includes increases in juvenile humpback whales in coastal waters, likely due to an increase in their menhaden prey.
These whales may be particularly vulnerable to vessel strike due to their behavior and high density and speed of vessels in nearshore waters of this region [@stepanuk2021].
Studies of whale-prey relationships and potential displacement from offshore wind areas in this region should be tailored to this context and capture rapidly changing ecosystem conditions and existing human uses in this area.

The **U.S. Central Atlantic** includes small resident populations of bottlenose dolphins, and large whales occur here and in the **U.S. Southeast Atlantic** at relatively lower densities than the other subregions.
Data collection strategies and studies should be designed with the lower expected densities in mind.
Both regions are important migratory routes, and the U.S.
Southeast Atlantic contains critical habitat for North Atlantic right whale calving.
More information is needed about the ways that reproductively active female right whales respond (or do not respond) to physical structures, noise, and vessels in their environment before wind projects are implemented in the Southeast right whale calving habitat.
Characterizations of marine mammal distribution, abundance, and movement should continue in these subregions using multiple methods as offshore wind planning and development advances.

## Data Analysis

Data analyses should inform where new data collection is needed, characterize oceanographic and habitat drivers of marine mammal distribution, abundance, and behavior, seek to assess whether offshore wind is causing any observed changes, and evaluate the efficacy of monitoring and mitigation strategies.
The Subcommittee is especially interested in studies that seek to distinguish between climate change-driven shifts in marine mammal distribution, abundance, and behavior and changes that may be driven by offshore wind construction and operation.
Related changes of interest include:

-   Whether construction activities displace or attract marine mammals

-   Whether offshore wind structures displace or attract marine mammals

-   Whether marine mammal feeding is altered due to changes to hydrodynamics or prey distribution/abundances caused by offshore wind structures

Individuals and entities should consult with the Marine Mammal Subcommittee prior to conducting analyses of marine mammal data with respect to offshore wind to ensure that the study leverages all of the available data and contributes to addressing the key recommendations described below to the extent possible:

-   **Leverage extensive existing and long-term data sources.** These include but are not limited to AMAPPS, NOAA Fisheries North Atlantic Right Whale Aerial Surveys, Southern New England Aerial Megafauna Surveys, long-term/archival PAM, as well as shorter-duration observational studies (aerial, boat-based, tagging) as foundational elements of any analysis.

-   **Conduct a synthetic baseline assessment of marine mammals over the past several decades to characterize pre-development levels of spatial and temporal variability in marine mammal distribution and abundance patterns, from which to measure and assess any potential changes after the onset of offshore wind construction and regional-scale operation activities.** Integrate density modeling and/or visual survey data, passive acoustic monitoring data, tagging data, oceanography/habitat data, and climate data to characterize pre-development levels of spatial and temporal variability in marine mammal distribution and abundance patterns.

-   **Continue to update and improve marine mammal density models.** Use outputs to understand drivers of marine mammal distribution and movement and to assess/detect change, displacement, and/or potential impacts.
    Periodically evaluate model performance and use validation and evaluation results to continually inform and advance model/framework development and applications.

    -   Integrate the latest observational and environmental data every 2-3 years.

    -   Integrate data from multiple additional methods (strandings, digital aerial surveys, passive acoustic data, tagging) and covariates (oceanographic and prey distribution).
        Apply results to inform research designs, determine baseline abundance/distribution estimates, best practices, etc.

    -   Consider how to structure future model "eras" to reflect offshore wind pre-construction and construction/operation.

    -   The modeling framework should be scalable to individual projects and the whole region such that individual project-specific outputs could be pooled into regional-scale versions of the model.

-   **Repeat a power analysis to optimize the design of the long-term archival passive acoustic monitoring network every 3-5 years.** Ensure that new monitoring assets and analysis results are accounted for and that existing or new hypotheses and questions can be addressed by the regional network.

-   **Inform and evaluate the effectiveness of mitigation strategies meant to minimize impacts resulting from increases in vessel traffic (i.e., noise, collision, displacement) from construction and maintenance of offshore wind projects.**

    -   Develop or update existing vessel and marine mammal co-occurrence models with information from the offshore wind industry regarding vessel types and numbers.
        Validate models with AIS and effort-corrected whale sightings data.

    -   Conduct studies to assess the effectiveness of mitigation strategies such as speed restrictions, establishment of traffic corridors, etc.

-   **Model and assess entanglement risks associated with floating offshore wind.**

-   **Build off [Project WOW](https://offshorewind.env.duke.edu/) and apply lessons learned to studies in and around other lease areas outside Southern New England and New York/New Jersey Bight.** Use Project WOW Frameworks to identify stressors, species, and geographic areas to conduct assessments of displacement, attraction, or other changes to wildlife abundance, distribution, behavior, and/or health.

-   **Integrate multiple types of data (e.g., acoustic, visual, stable isotopes, bycatch estimates, vessel trip reports) to understand potential changes in marine mammal feeding behaviors.**

-   **Determine whether prey distribution, abundance and/or behavior is altered due to hydrodynamic changes caused by offshore wind structures and from EMF/cables (heat and electromagnetic field).**

-   **Scope studies of EMF and marine mammals.** Include studies of whether animals can detect EMF, what the sensing capabilities are, and over what distance.
