# Protected Fish Species {#sec-protected-fish}

*Authors: [Protected Fish Species Subcommittee](append-rosters.qmd#pf)*

*For more detail on any of these topics, read [the Protected Fish Species Appendix](append-pf.qmd)*.

The RWSC Steering Committee formed a Protected Fish Species Subcommittee to address data collection and research for Endangered Species Act (ESA)-listed fish species, recognizing that these species likely fell outside of the focus of other research collaboratives such as the [Responsible Offshore Science Alliance (ROSA)](https://www.rosascience.org/), whose focus is commercial and recreational fisheries.
The scope of the RWSC Science Plan does not include fisheries or commercially managed fish species.
For research needs and considerations on those topics, visit [ROSA](https://www.rosascience.org/).
To ensure close coordination on issues in the RWSC Science Plan that might relate to ROSA's work, ROSA staff participate in the RWSC Protected Fish Species and Habitat & Ecosystem Subcommittees.

The Subcommittee has expressed some concern regarding potential impacts of offshore wind development on fish species that are not ESA-listed or commercially managed (e.g., some shark species) that overlap with offshore wind development in the western Atlantic.
The RWSC, ROSA, and participants in both organizations will work together to ensure that fish in the region will not be omitted from research and monitoring activities.

Given the considerations above, this chapter addresses fish species that are listed as [Endangered, Threatened, petitioned, candidate, or proposed under the ESA](https://www.fisheries.noaa.gov/species-directory/threatened-endangered) in the RWSC study area.
This list may be updated as listed statuses change, as more research is conducted, and as more information becomes available about non-listed and non-commercially managed fish species.

Table 5.
List of federally protected fish species in the RWSC study area.

+----------------------------------------------------+-------------------------------------------------------------------------------------------+
| **Species**                                        | **ESA Status**                                                                            |
+----------------------------------------------------+-------------------------------------------------------------------------------------------+
| Atlantic salmon (*Salmo salar*)                    | Endangered - Gulf of Maine Distinct Population Segment (DPS)                              |
+----------------------------------------------------+-------------------------------------------------------------------------------------------+
| Atlantic sturgeon (*Acipenser oxyrinchus*)         | -   Endangered - New York Bight DPS, Chesapeake Bay DPS, Carolina DPS, South Atlantic DPS |
|                                                    |                                                                                           |
|                                                    | -   Threatened - Gulf of Maine DPS                                                        |
+----------------------------------------------------+-------------------------------------------------------------------------------------------+
| Shortnose sturgeon (*Acipenser brevirostrum*)      | Endangered                                                                                |
+----------------------------------------------------+-------------------------------------------------------------------------------------------+
| Giant manta ray (*Mobula birostris*)               | Threatened                                                                                |
+----------------------------------------------------+-------------------------------------------------------------------------------------------+
| Oceanic whitetip shark (*Carcharhinus longimanus*) | Threatened                                                                                |
+----------------------------------------------------+-------------------------------------------------------------------------------------------+
| Nassau grouper (*Epinephelus striatus*)            | Threatened                                                                                |
+----------------------------------------------------+-------------------------------------------------------------------------------------------+
| Scalloped hammerhead shark (*Sphyrna lewini*)      | Threatened -- Central and Southwest Atlantic DPS                                          |
+----------------------------------------------------+-------------------------------------------------------------------------------------------+
| Smalltooth sawfish (*Pristis pectinata*)           | Endangered                                                                                |
+----------------------------------------------------+-------------------------------------------------------------------------------------------+
| Whitespotted eagle ray (*Aetobatus narinar*)       | Petitioned                                                                                |
+----------------------------------------------------+-------------------------------------------------------------------------------------------+

## Data management

The Protected Fish Species Subcommittee will work with individuals and entities who collect data relevant to protected fish studies to ensure that data are collected and stored in consistent formats.
This will enhance comparisons and pooling across individual projects in the RWSC study area to conduct regional-scale assessments and to develop and maintain regional-scale data products.

The Subcommittee recommends the following data management activities:

-   Leverage ROSA's work to standardize offshore wind fisheries monitoring plans and trawl surveys so that protected fish species data are accessible for use in RWSC's and partners' analyses and research.

-   Develop guidance to reconcile (or appropriately leverage) any redundancy among the various existing telemetry data repositories (Movebank, ATN, and the regional telemetry data nodes).

-   Characterize the acoustic telemetry receiver network with the purpose of integrating multiple individual efforts into a coordinated and intentional regional network for offshore wind studies that addresses gaps in coverage.
    Develop maps that show the receiver network in the RWSC study area over time with attribution/contact information for receiver owners.

    -   Characterize the length of ongoing and planned deployments, as there may be gaps in the regional network due to short-term arrays.

    -   Identify critical locations for receiver arrays to be placed long term and identify funding institutions to purchase, deploy, and maintain the arrays.

    -   Coordinate the co-location of receivers with other ocean-deployed sensors (e.g., with the RWSC Marine Mammal Subcommittee and regional IOOS associations).

-   *Cross taxa*) Convene an Offshore Wind & Telemetry Data Collaborative to coordinate on the deployment of acoustic telemetry receivers and acoustic and satellite tags on protected fish and other species of focus in the context of offshore wind development.
    Include ROSA, the Animal Telemetry Network, and Atlantic Cooperative Telemetry Network, and other relevant RWSC Subcommittees.

    -   Develop and encourage the use of best practices for consistent data collection, QA/QC, management, storage, and development of data products that represent metrics such as distribution, abundance, occupancy, and/or movement that allow comparisons and pooling across individual projects in the RWSC study area to conduct regional-scale assessments and the development of regional-scale data products.

    -   Develop maps that show the acoustic telemetry receiver network in the RWSC study area with attribution/contact information for receiver owners.
        Coordinate the co-location of receivers with other ocean-deployed sensors.

The following table lists the existing centralized or accepted repositories and standards that should be used and identifies data types for which no or limited data management capacity (i.e., repositories and standards) currently exists.

Table 6.
Recommended repositories and standards for protected fish species data collection.

+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Method(s) and data type(s)**                                                                                                  | **Repository**                                                                                                                                                                                                           | **Existing Standards**                                                                                                                                                                                                                                                                                                                                                     |
+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Observational surveys; telemetry data; acoustic monitoring; photo identification; oceanographic data products; model outputs    | [**OBIS-SEAMAP**](https://seamap.env.duke.edu/)(Ocean Biogeographic Information System -- Spatial Ecological Analysis of Megavertebrate Populations                                                                      | [OBIS-SEAMAP minimum data fields and acceptable formats,](https://seamap.env.duke.edu/content/provider_faq) Duke Marine Geospatial Ecology Lab                                                                                                                                                                                                                             |
+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Satellite tagging data; acoustic tagging data through the regional nodes Atlantic Cooperative Telemetry (ACT) and FACT networks | [**Animal Telemetry Network**](https://ioos.noaa.gov/project/atn/) (ATN)                                                                                                                                                 | -   [Animal Telemetry Network DAC Data Management Policy Guidance](https://cdn.ioos.noaa.gov/media/2022/03/ATN-DAC-Data-Management-Policy-Guidance_v.202201.pdf): includes data [submission requirements](https://atn.ioos.us/help/submit-data/) and instructions for submitting project-level metadata and deployment records via an app and by using Research Workspace. |
|                                                                                                                                 |                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                            |
|                                                                                                                                 |                                                                                                                                                                                                                          | -   Need to develop guidance specific to protected fish species and to projects lacking federal funding                                                                                                                                                                                                                                                                    |
+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Acoustic tagging data                                                                                                           | [**FACT Network**](https://secoora.org/fact/)                                                                                                                                                                            | -   [FACT Network Metadata Template](https://secoora.org/fact/how-to-submit-data/), SECOORA                                                                                                                                                                                                                                                                                |
|                                                                                                                                 |                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                            |
|                                                                                                                                 |                                                                                                                                                                                                                          | -   Need to develop guidance specific to protected fish species                                                                                                                                                                                                                                                                                                            |
+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Acoustic tagging data                                                                                                           | [**Atlantic Cooperative Telemetry Network**](https://www.theactnetwork.com/home)(ACT Network Data are managed in the [ACT-MATOS database](https://matos.asascience.com/) following the merger of ACT and MATOS in 2020). | -   ACT Network Metadata Template (available for members to download when logged into website)                                                                                                                                                                                                                                                                             |
|                                                                                                                                 |                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                            |
|                                                                                                                                 |                                                                                                                                                                                                                          | -   Need to develop guidance specific to protected fish species                                                                                                                                                                                                                                                                                                            |
+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Satellite tagging, Acoustic tagging, VHF tagging, other tagging                                                                 | [**Movebank**](https://www.movebank.org/)                                                                                                                                                                                | -   [Archiving in the Movebank Data Repository](https://datarepository.movebank.org/help/submission-guidelines): archiving, DOI assignment, licensing, submission guidelines                                                                                                                                                                                               |
|                                                                                                                                 |                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                            |
|                                                                                                                                 |                                                                                                                                                                                                                          | -   Need to develop guidance specific to protected fish species                                                                                                                                                                                                                                                                                                            |
+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| High-definition aerial imagery                                                                                                  | None; records of observations from photos go to OBIS-SEAMAP                                                                                                                                                              | -   None -- needs development                                                                                                                                                                                                                                                                                                                                              |
+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| eDNA                                                                                                                            | None -- needs development                                                                                                                                                                                                | -   None -- needs development                                                                                                                                                                                                                                                                                                                                              |
+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## Data collection

There is a lack of baseline data on most protected fish species and all their life stages in areas where offshore wind projects will or may occur.
The lack of baseline data is compounded by the varied and unknown impacts to these species from climatic change.
An urgent priority is to improve understanding of distribution and movement for most life stages in wind energy areas so that it is possible to properly assess, monitor, and mitigate any impacts.
The Subcommittee recommends using multi-modal approaches (telemetry, eDNA, trawl surveys, aerial surveys) to fill data gaps, though acoustic and satellite telemetry appear to be the quickest and most effective means to enhance understanding.
The Subcommittee stresses the importance of relying on local experts as the ecosystems differ greatly throughout the region, as does protected fish use of each wind energy area.
Each individual project becomes even more valuable when data can be compared and integrated at broader scales.

Several entities are requiring, funding, and/or advocating for protected fish species research and data collection activities with respect to offshore wind.
All ongoing and planned activities, including protected fish species monitoring that is required by agencies, are captured in the [Offshore Wind & Wildlife Research Database](https://database.rwsc.org/).
To scope future studies, the Subcommittee is guided by earlier research on protected fish species and their interactions with wind energy areas in both Europe and the United States.
The descriptions of potential effects to protected fish such as underwater noise, vessel collision, entanglement, introduction of new structures, and electromagnetic fields are summarized in the [Environmental Effects of U.S. Offshore Wind Energy Development: Compilation of Educational Research Briefs](https://tethys.pnnl.gov/sites/default/files/summaries/SEER-Booklet.pdf) [@seer2022a] and the Synthesis of the Science [@hogan2023].
The gaps and needs are captured in the [Atlantic Offshore Wind Environmental Research Recommendations](https://tethys.pnnl.gov/atlantic-offshore-wind-environmental-research-recommendations)[@regionalsynthesisworkgroupoftheenvironmentaltechnicalworkinggroup] as well as [@hogan2023].

Most offshore-wind-specific monitoring to-date of protected fish species in the U.S.
Atlantic is occurring in Southern New England and the New York/New Jersey Bight on Atlantic sturgeon [@frisk2019; @haulsee2020; @ingram2019; @rothermel2020], with the goal of characterizing baseline distribution and movement.
In the Gulf of Maine, protected fish species monitoring at the University of Maine's Vulturn US 1:8 floating turbine indicated no change in the detection frequency of tagged Atlantic salmon, Atlantic Sturgeon, or shortnose sturgeon on receivers near the turbine following energization [@brady2015].
There are also significant and ongoing data collection efforts in estuaries and coastal areas throughout the RWSC study area.
While most of these efforts are not explicitly related to offshore wind, their findings can be used to augment the baseline understanding of protected fish species in the region.

Relevant long-term protected species, fisheries, and ecosystem surveys conducted by the NOAA Fisheries Northeast Fisheries Science Center include:

-   Autumn bottom trawl survey

-   Spring bottom trawl survey

-   Gulf of Maine Cooperative Bottom Longline Survey

-   Ecosystem Monitoring Survey (6 times per year)

-   Coastal Shark Bottom Longline Survey

-   Cooperative Atlantic States Shark Pupping and Nursery Longline/Gillnet Survey

Individuals and entities should consult with the Protected Fish Species Subcommittee prior to collecting protected fish species data with respect to offshore wind to ensure that any new data collection does not duplicate existing efforts and is consistent with the tools and approaches already in use.
Any individual or entity may join public Protected Fish Species Subcommittee meetings by obtaining meeting links on the [RWSC website](https://rwsc.org/), where all past meeting materials are also available.

The Subcommittee recommends the following data collection activities:

-   Deploy fine-scale acoustic receiver arrays in and around every leased and proposed Wind Energy Area and along associated cable routes.
    Pair deployments with acoustic and satellite tagging of protected fish.

    -   Plan and implement telemetry data collection activities in a consistent way, such that data and metadata from individual projects is standardized and interoperable.

    -   Expand projects like Buoys of Opportunity across the region to co-locate acoustic receivers to structures already in/going in the water.

    -   Couple on-bottom deployment of acoustic receivers with bottom temperature measurements to the extent possible.

    -   Encourage all new tags/groups to submit data to the Animal Telemetry Network and/or appropriate regional nodes in an agreed upon time frame to allow for archiving, securing, and publishing. 

-   Design a distributed region wide system of receiver arrays that serve as the backbone for projects throughout the region.
    This includes receivers offshore/along the shelf, which are limited in the current project landscape.

    -   Ensure that this system has sustained investment for operation and maintenance.

    -   Encourage all new tags/groups to submit data to the Animal Telemetry Network and/or appropriate regional nodes in an agreed upon time frame to allow for archiving, securing, and publishing.

-   Pair additional methods with telemetry data collection, including conventional tagging (i.e., non-electronic), eDNA, and aerial surveys to aid the identification of changes in residency or usage of the area.

-   Evaluate the risks of known impact producing factors to protected fish from offshore wind development.

    -   Develop tools and monitoring mechanisms to better understand if/when vessel strikes occur and what vessels are typically involved.

        -   Coordinate with state agencies for recorded information on protected fish sightings, incidental catches, and beach strandings, particularly Atlantic and shortnose sturgeon.

        -   Ensure sufficient human and financial resources to support local salvage operations.

        -   Create and test mitigation measures to prevent vessel strikes.

    -   Conduct further laboratory and field studies of EMF effects on protected fish species, especially Chondrichthyes and sturgeons, to assess potential impacts including changes in migration patterns, feeding, or behavior.
        Conduct similar studies on protected fish prey species.

    -   Conduct in situ examinations of noise impacts to protected fish species.

    -   Assess primary and secondary entanglement risk to all protected fish species given the potential for increased recreational fishing near wind turbines and increased possibility of secondary entanglement. 

-   Align data collection and research activities with the recommendations in the NOAA Fisheries & BOEM Federal Survey Mitigation Strategy [@hare2022].

-   Collaborate with other Subcommittees to maximize data collection efforts.

    -   Marine Mammal: maintain a shareable database and/or map of the acoustic telemetry receivers that may be co-located with bottom-mounted passive acoustic hydrophones.

    -   Technology: Test and implement any technological advancements that may be required to continue long-standing scientific surveys and data collection in areas that are no longer accessible or are accessible in a limited extent that will influence continuity of surveys.

    -   Sea Turtle: Ensure that sea turtle researchers can access telemetry receiver data if desired.

    -   Habitat and Ecosystem: Work to ensure that key oceanographic and habitat data are collected and available to use in coordination with studies on protected fish. 

Technology advancements to improve protected fish research and monitoring:

-   Develop and test telemetry tags with further miniaturization for use with smaller individuals.

-   Improve data resolution and positional accuracy of telemetry tags and test adding sensors (magnetometers, sound, dissolved oxygen, chlorophyll, etc.) to existing tags.

-   Investigate the use of eDNA to measure species abundance in addition to occurrence.

-   Improve or develop machine learning and/or Artificial Intelligence detection for soniferous protected fish in passive acoustic data.

In the **Gulf of Maine,** where offshore wind projects are still in the planning phases, baseline data about the occurrence, distribution, and movement of protected fish species is needed.
Floating offshore structures include cables and mooring lines that span the entire water column, including some that emit EMFs.
Potential effects from EMF and secondary entanglement should be monitored.
Focal species in these regions include Atlantic salmon, Atlantic sturgeon and shortnose sturgeon.
The oceanic whitetip shark and giant manta ray may also be found in this region.

In **Southern New England and New York/New Jersey Bight**, existing baseline data collection from multiple tools such as acoustic telemetry, satellite telemetry, eDNA, and trawl surveys, need to be better integrated to characterize protected fish species' distribution and movement pre-offshore wind construction.
These data should also continue to be collected throughout all phases of development to characterize changes from pre-construction baselines.
Focal species in these regions include Atlantic sturgeon and shortnose sturgeon.
The oceanic whitetip shark and giant manta ray are also found in this region.

In the **U.S.** **Central Atlantic and U.S. Southeast Atlantic,** baseline data collection on the occurrence, distribution, and movement of protected fish is most urgent in the U.S.
Central Atlantic where projects are farther along in the development process.
The U.S. Central Atlantic is home to the Atlantic sturgeon, shortnose sturgeon, giant manta ray, and whitespotted eagle ray.
These species are also present in the U.S.
Southeast Atlantic, in addition to the listed Central & Southwest Atlantic distinct population segments of scalloped hammerhead shark, Nassau grouper, and smalltooth sawfish.

## Data analysis

Data analyses should characterize oceanographic and habitat drivers of protected fish species distribution, abundance, and behavior, seek to assess whether offshore wind is causing any observed changes, and inform where new data collection is needed.
Individuals and entities should consult with the Protected Fish Species Subcommittee prior to conducting analyses of protected fish species data with respect to offshore wind to ensure that the study leverages all available data and contributes to addressing the key issues described below to the extent possible.
The following data analysis activities are needed:

-   Identify and use historical data collections from multiple sources (e.g., data affiliated with offshore wind projects, coastal and estuarine data collection efforts, and NOAA Fisheries long-term surveys) to generate a baseline of distribution and abundance of protected fish species.
    Determine/describe useful baseline parameters to use when adequate abundance and density data are not available.

-   Develop best practices for producing consistent movement data products for protected fish that can be replicated throughout the region.

-   Develop best practices for integrating data from multiple methods (telemetry, eDNA, trawl surveys, aerial surveys) across scales to model baseline species' distribution and movement using oceanographic variables and other contextual information (e.g., quantifications of vessel traffic).
    The modeling framework should be applicable to individual projects and at regional scales such that consistent approaches are used across projects, and eventually in other subregions of the RWSC study area.

-   Analyze existing plankton camera data for presence of protected fish early life stages and prey which can be used to develop dispersal models.

-   Develop analyses of vessel and protected fish species co-occurrence that model nearshore vessel traffic.

-   Leverage available passive acoustic monitoring data to both characterize changes in the soundscape and detect soniferous protected fish species.
    Study potential effects from noise during pile driving and geophysical surveys on protected fish distribution, movement, and behavior.

-   Inform approaches meant to mitigate impacts related to sediment resuspension by advancing predictive modeling of sedimentation/resuspension patterns.

-   Ensure that protected fish species are included in risk modeling that is similarly being applied to other species, e.g., Project WOW.

    -   Population Viability Analyses

    -   Population Consequences of Disturbance (PCOD)

    -   Population Consequences of Multiple Stressors (PCOMS)

-   Continually evaluate the performance of existing models and statistical frameworks.

    -   Use validation and evaluation results to continually inform and advance the model/framework development and application.

    -   Models should be updated as new information becomes available.

-   Attempt to determine the causality of any changes in protected fish abundance, distribution, or behavior.
    This includes disentangling effects related to offshore wind development from those due to climate change, natural variability, or other causes.
