# Sea Turtles {#sec-sea-turtles}

*Authors: [Sea Turtle Subcommittee](append-rosters.qmd#st)*

*For more detail on any of these topics, read [the Sea Turtle Appendix](append-st.qmd)*.

Among the taxa-based groups covered by the RWSC Science Plan, sea turtles are the only protected species where there are almost no impact data available from existing wind installations.
At the same time, these species may also represent the most abundant species listed under the Endangered Species Act (ESA) that will be affected by offshore wind energy activities in U.S.
Atlantic waters, especially in the U.S.
Central and Southern Atlantic subregions.
Seasonal limits on offshore wind construction established specifically to protect North Atlantic right whales may also provide protection for other listed marine mammal and bird species in northern subregions but will not provide similar protection in the subregions where sea turtles are most abundant (i.e., New York/New Jersey Bight and south).
With the lack of available data on impacts of offshore wind on sea turtles, it may be prudent to look at a variety of risk assessment methodologies to begin the process of identifying the potential for negative impacts on this species group.
The Sea Turtle Subcommittee recommends exploring the use of cumulative impact assessment to quantify multiple threats to sea turtles, as were applied following the Gulf of Mexico Deep Water Horizon Oil Spill.
The Subcommittee found that among active offshore wind-related research, sea turtle data is being collected ancillary to other species, and studies are often not designed to detect or study sea turtles.
To understand the potential impacts of offshore wind activities on this protected species group, research focused on sea turtles should be prioritized.
To scope future activities, the Subcommittee is guided by the descriptions of potential effects such as vessel collision, entanglement, underwater noise, introduction of new structures, and electromagnetic fields summarized in Environmental Effects of U.S.
Offshore Wind Energy Development: Compilation of Educational Research Briefs [@seer2022a] and the gaps and needs captured in the [Atlantic Offshore Wind Environmental Research Recommendations](https://tethys.pnnl.gov/atlantic-offshore-wind-environmental-research-recommendations) [@regionalsynthesisworkgroupoftheenvironmentaltechnicalworkinggroup].

## Data Management

There are few existing data management standards developed specifically for sea turtles.
The Sea Turtle Subcommittee will work with individuals and entities who conduct research to encourage that data are collected and stored in consistent formats that allow comparisons and pooling across individual projects in the RWSC study area.
This standardization is intended to support regional-scale assessments and the development and maintenance of regional data products and tools (e.g., sea turtle surface density models).

To support these efforts, the Sea Turtle Subcommittee recommends:

-   Maintenance of an up-to-date resource list of recommended repositories, data and metadata standards, guidance, and protocols for use by all data collectors.
    The current recommended resources are detailed in the table below.

-   Development of standard language for inclusion in requests for proposals and funding agreements to encourage or require the use of recommended resources.

-   Establishment of data sharing workflows, including formal agreements if necessary, to appropriately manage access to sensitive industry-collected datasets necessary for research.

-   (*Cross taxa*) Convene an Offshore Wind & Telemetry Data Collaborative to coordinate on the deployment of acoustic telemetry receivers and acoustic and satellite tags on sea turtles and other species of focus in the context of offshore wind development.
    Include ROSA, the Animal Telemetry Network, and Atlantic Cooperative Telemetry Network, and other relevant RWSC Subcommittees.

    -   Develop and encourage the use of best practices for consistent data collection, QA/QC, management, storage, and development of data products that represent metrics such as distribution, abundance, occupancy, and/or movement that allow comparisons and pooling across individual projects in the RWSC study area to conduct regional-scale assessments and the development of regional-scale data products.

    -   Develop maps that show the acoustic telemetry receiver network in the RWSC study area with attribution/contact information for receiver owners.
        Coordinate the co-location of receivers with other ocean-deployed sensors.

-   Develop or adopt existing best practices for other sea turtle telemetry/imagery data collected using DTAGs, ROVs, AUVs, including for QA/QC, programming parameters, management, storage, and sharing/accessibility and encourage consistent use across taxa/projects.

The following table lists the repositories and standards that are recommended for use in sea turtle data collection and identifies data types for which no or limited data management capacity (i.e., standard repositories and guidance) currently exists.

::: callout-important
## Since the publication of this Science Plan in January 2024, the RWSC Data Governance Subcommittee has posted [updated recommendations for data repositories](https://rwscollab.github.io/repositories-data-catalog/repositories-data-catalog.html). Updates will continue to be posted at that link prior to a formal update to the Science Plan.
:::

Table 4.
Recommended repositories and standards for sea turtle data collection.

+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Method(s) and data type(s)**                                                                                 | **Current Repository**                                                                                                                                                                                              | **Existing Standards/comments**                                                                                                                                                                                                                                                                                                                                            |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Observational surveys; telemetry data; oceanographic data products; model outputs                              | [**OBIS-SEAMAP**](https://seamap.env.duke.edu/)(Ocean Biodiversity Information System -- Spatial Ecological Analysis of Megavertebrate Populations                                                                  | [OBIS-SEAMAP minimum data fields and acceptable formats](https://seamap.env.duke.edu/content/provider_faq)                                                                                                                                                                                                                                                                 |
|                                                                                                                |                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                                                                                                                                            |
|                                                                                                                | [Loggerhead (*Caretta caretta*)](https://seamap.env.duke.edu/species/173830)                                                                                                                                        | Data are batch uploaded (i.e., not one sighting at a time), uploads can be automated for long-term monitoring data.                                                                                                                                                                                                                                                        |
|                                                                                                                |                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                                                                                                                                            |
|                                                                                                                | [Kemp's ridley (*Lepidochelys kempii*)](https://seamap.env.duke.edu/species/551770)                                                                                                                                 | OBIS-SEAMAP may require funding to tailor sea turtle specific user access to these data.                                                                                                                                                                                                                                                                                   |
|                                                                                                                |                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                                                                                                                                            |
|                                                                                                                | [Green (*Chelonia mydas*)](https://seamap.env.duke.edu/species/551770)                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                                            |
|                                                                                                                |                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                                                                                                                                            |
|                                                                                                                | [Leatherback (*Dermochelys coriacea*)](https://seamap.env.duke.edu/species/551770)                                                                                                                                  |                                                                                                                                                                                                                                                                                                                                                                            |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Satellite tag data; acoustic tag and detection data through Atlantic Cooperative Telemetry Network (see below) | [**Animal Telemetry Network**](https://ioos.noaa.gov/project/atn/) (ATN)                                                                                                                                            | -   [Animal Telemetry Network DAC Data Management Policy Guidance](https://cdn.ioos.noaa.gov/media/2022/03/ATN-DAC-Data-Management-Policy-Guidance_v.202201.pdf): includes data [submission requirements](https://atn.ioos.us/help/submit-data/) and instructions for submitting project-level metadata and deployment records via an app and by using Research Workspace. |
|                                                                                                                |                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                                                                                                                                            |
|                                                                                                                |                                                                                                                                                                                                                     | -   Need to develop guidance specific to sea turtles and to projects lacking federal funding                                                                                                                                                                                                                                                                               |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Acoustic tag and detection data                                                                                | [**Atlantic Cooperative Telemetry Network**](https://www.theactnetwork.com/) (ACT) which includes FACT and the Ocean Tracking Network, and leverages the Mid-Atlantic Acoustic Telemetry Observation System (MATOS) | -   Users need to join ACT to access membership guidelines and other materials.                                                                                                                                                                                                                                                                                            |
|                                                                                                                |                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                                                                                                                                            |
| (Canadian Maritimes to Bahamas)                                                                                |                                                                                                                                                                                                                     | -   [FACT Network Metadata Template](https://secoora.org/fact/how-to-submit-data/), SECOORA                                                                                                                                                                                                                                                                                |
|                                                                                                                |                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                                                                                                                                            |
|                                                                                                                |                                                                                                                                                                                                                     | -   Need to develop guidance specific to sea turtles                                                                                                                                                                                                                                                                                                                       |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Multiple telemetry types of telemetry data                                                                     | [**Movebank**](https://www.movebank.org/)                                                                                                                                                                           | -   [Archiving in the Movebank Data Repository](https://datarepository.movebank.org/help/submission-guidelines): archiving, DOI assignment, licensing, submission guidelines                                                                                                                                                                                               |
|                                                                                                                |                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                                                                                                                                            |
| (International)                                                                                                |                                                                                                                                                                                                                     | -   Need to develop guidance specific to sea turtles                                                                                                                                                                                                                                                                                                                       |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Stranding data (floating, beached, live, dead, entangled), incidental capture, vessel strike                   | [**Sea Turtle Stranding and Salvage Network (STSSN)**](https://www.fisheries.noaa.gov/national/marine-life-distress/sea-turtle-stranding-and-salvage-network)                                                       | [Sea turtle stranding database data management](https://rwscorg.sharepoint.com/:b:/s/SeaTurtleSubcommittee/EeJZEUR-ZChFlMAou-eBGTABNKiDipDTL62wsUpa2NEk3g?e=83HYaN)                                                                                                                                                                                                        |
|                                                                                                                |                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                                                                                                                                            |
|                                                                                                                | [STSSN State Coordinators](https://www.fisheries.noaa.gov/marine-life-distress/state-coordinators-and-state-liaisons-sea-turtle-stranding-and-salvage-network)                                                      | Inshore observations of stranded sea turtles should be reported to state coordinators; EEZ observations should be reported to regional coordinators                                                                                                                                                                                                                        |
|                                                                                                                |                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                                                                                                                                            |
|                                                                                                                | [U.S. EEZ Maine-Virginia:]{.underline} Northeast Marine Mammal & Sea Turtle Stranding & Entanglement Hotline (866-755-6622)                                                                                         |                                                                                                                                                                                                                                                                                                                                                                            |
|                                                                                                                |                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                                                                                                                                            |
|                                                                                                                | [U.S. EEZ North Carolina-Florida]{.underline}: NOAA Fisheries Southeast Sea Turtle Stranding and Salvage Network Hotline (844-732-8785)                                                                             |                                                                                                                                                                                                                                                                                                                                                                            |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| High-definition aerial imagery                                                                                 | None -- needs development                                                                                                                                                                                           | None -- needs development                                                                                                                                                                                                                                                                                                                                                  |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ROV video data                                                                                                 | None -- needs development                                                                                                                                                                                           | None -- needs development                                                                                                                                                                                                                                                                                                                                                  |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| eDNA                                                                                                           | None -- needs development                                                                                                                                                                                           | None -- needs development                                                                                                                                                                                                                                                                                                                                                  |
+----------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## Data Collection

Individuals and entities are encouraged to attend Sea Turtle Subcommittee meetings while planning new sea turtle-offshore wind research and data collection to leverage the available resources and guidance compiled by the Subcommittee.
The Subcommittee is comprised of sea turtle experts from federal agencies, states, research institutions, and other private entities.
Any individual or entity may join public Sea Turtle Subcommittee meetings by obtaining meeting links on the RWSC website.

Currently, there are limited fine-scale baseline data on abundance and density of sea turtles in the U.S.
Atlantic.
The primary methodology for determining sea turtle abundance and density is to employ manned aerial surveys, but this methodology is not designed to detect small individuals such as the Kemp's ridley turtle that is critically endangered.
The appropriate variables for describing baseline behavior, physiology, and distribution have not been established.
Without established baselines effective for all species and size classes, assessing and mitigating effects of offshore wind on sea turtles will be extremely difficult.

Few large-scale ongoing or proposed offshore wind studies include sea turtles as the target species group.
The [Offshore Wind & Wildlife Research Database](https://database.rwsc.org/) captures [targeted studies of sea turtles and offshore wind](https://database.rwsc.org/sea-turtles), [offshore wind studies where sea turtle data may be recorded in an ancillary fashion](https://database.rwsc.org/sea-turtles), and existing and long-term sea turtle monitoring programs [that were not specifically designed to measure potential offshore wind impacts](https://database.rwsc.org/sea-turtles#other-proj).
Where sea turtles will be studied as an ancillary research target, it is unclear how or whether sea turtle data will be analyzed.

The Subcommittee recommends the following regional-scale data collection efforts for sea turtles (recommendations appropriate for other taxa are labeled as *cross taxa*):

-   Use expert input to develop standardized data collection methods to quantify impacts of offshore wind on sea turtles in the context of limited baseline data and climate change effects.

-   (*Cross taxa*) Leveraging BOEM's ongoing efforts, ensure that the required Protected Species Observer data collected by offshore wind companies during construction and operations described within mitigation plans (e.g., Pile Driving Monitoring Plans and Vessel Strike Avoidance Plans) follow 1) a consistent reporting approach, 2) are eventually submitted to a designated repository and are available for use in sea turtle research, mitigation, and management.

-   Increase data collection on sea turtle species at the regional-scale for a variety of baseline parameters through new and existing federal partnerships (e.g., BOEM's Environmental Studies Program, AMAPPS, U.S. Navy projects, NMFS projects).

-   (*Cross taxa*) Align new data collection activities with the objectives in the NOAA Fisheries and BOEM Federal Survey Mitigation Strategy [@hare2022].
    Review the strategy where it directly addresses sea turtle survey needs and support the development of a Northeast Survey Mitigation Program and similar efforts for the Southeast Region.

-   (*Cross taxa*) Once protocols are developed for assessing sea turtle baseline parameters using consistent phase-gradient experimental designs, prioritize data collection at individual project areas during construction, operation, and demolition to determine if activities displace or attract sea turtles.

-   (*Cross-taxa*) Coordinate regular high-definition aerial surveys that cover multiple lease areas using comparable tools and methods.
    This effort should leverage the considerable amount of high-definition aerial photography data collected during site assessment by multiple offshore wind developers.

-   Employ NOAA Fisheries recommendations to enhance AMAPPS loggerhead turtle abundance estimates [@noaafisheries2020] and expand detection studies to all sea turtle species and sizes under a variety of conditions.

-   Collect surface time and dive data on all species in all subregions, and appropriate seasons, to contribute to baseline knowledge of 3D distribution, dive behavior, and surface time/availability estimates that can be used to inform sea turtle surface density models.

-   Collaborate with additional partners to facilitate data and information sharing, including the Sea Turtle Stranding and Salvage Network, organizations conducting sea turtle nest monitoring, sea turtle rescue organizations operating under USFWS permits and authorization as well as researchers collecting satellite, acoustic, and other tag data.

Technology needed to improve sea turtle detection and access:

-   Develop and test smaller tags with depth sensors capable of surface time calculations for availability bias calculations in smaller turtles.

-   Develop and test (non-archival) tags and/or tag attachment techniques with low drag for capture/release in difficult (offshore) environments.

-   Develop and test remote tag attachment techniques for in-water work.

-   Continue development, testing, and deployment of safe, long term external attachment and/or internal insertion methods [@innis2023] for acoustic tags on sea turtles in order to efficiently make use of this resource.

-   (*Cross taxa*) Develop and test eDNA assays/surveys/sampling regimes to understand efficacy of use in developing indices of occurrence/abundance, including testing the effect of carcasses in the environment on eDNA detection.

Each subregion has differences in both sea turtle occurrence and the scale and timeline of offshore wind development.
Subregion specific recommendations are:

In the **Gulf of Maine**, where floating offshore wind development is planned, but where development areas are still being identified, baseline data collection is needed.
Small, focused studies on individual animal movement and behavior that are site specific may be the most effective strategies for assessing impacts.
Data collection in this subregion should include efforts to characterize and monitor gelatinous prey (i.e., jellyfish and ctenophores) as it is unclear how/whether floating turbines will affect this important sea turtle prey group.

In **Southern New England and the New York/New Jersey Bight**, approved offshore wind projects pose the first opportunity to study sea turtle behavior during construction and operation and to identify potential impacts to sea turtles.
It is unclear whether baseline abundance/density data for loggerhead and leatherback turtles in this subregion will be sufficient to detect changes or attribute causes of detected changes in abundance/density using distance sampling techniques.
Thus, data collection should focus within and distant from the project envelopes in this subregion and should also include vessel corridors.
Turbine construction activities are designed to avoid times when critically endangered North Atlantic right whales were historically in the area (January-April), but these limitations may not avoid the times of highest sea turtle occurrence.

In the **U.S. Central Atlantic** subregion, it appears that there is little voluntary sea turtle research or monitoring associated with offshore wind projects with the exeception of the Maryland Offshore Wind project (U.S. Wind lease).
This subregion, however, is likely to have 1) higher turtle densities of most species, 2) longer seasonal sea turtle occurrence and 3) active breeding and nesting adults compared with projects to the north.
In addition, restrictions on turbine construction activities designed to avoid critically endangered right whales will mean that construction will occur when densities for most sea turtle species in subregion are highest.
Impact studies and data collection in the U.S.
Central Atlantic subregion should be focused in and adjacent to lease areas and nearby vessel corridors.

All four sea turtle species have a year-round presence in the **U.S. Southeast Atlantic** which provides foraging, nesting, and breeding habitat for all species.
However, there are currently no ongoing or planned research projects related to offshore wind and sea turtles in the RWSC Database in this subregion.

## Data Analysis

Data analyses should inform where new data collection is needed, characterize oceanographic and habitat drivers of sea turtle distribution, abundance, and behavior, and seek to assess whether offshore wind is impacting sea turtles either negatively or positively.

Individuals and entities are encouraged to consult with the Sea Turtle Subcommittee prior to conducting analyses of sea turtle data with respect to offshore wind to ensure that studies leverage all available data and contribute to addressing key issues described below to the extent possible.

Due to the lack of fine scale baseline abundance/density data, other baseline parameters and understanding of drivers of sea turtle behavior, distribution, and movement are needed.
Design for the studies below should be tailored to detect and understand potential effects on sea turtles specifically, with other wildlife data to be collected ancillary to the target species.

**Inform where new data collection is needed:**

-   Use expert input to assess experimental design and develop data analysis methods and parameters to quantify impacts of offshore wind on sea turtles in the context of multiple data streams, limited baseline data, and climate change effects.

-   Determine/describe useful baseline parameters for sea turtle distribution and behavior to be used where abundance/density data are not available.

-   Develop robust vertical water column use understanding for all sea turtle species in all subregions and seasons to assist in the development of baseline behavior and abundance estimates for sea turtle species.

-   Analyze datasets collected for other focal species for sea turtle species presence (e.g., high-definition aerial imagery, eDNA).

-   Determine the efficacy of acoustic telemetry for sea turtles, especially if internal tag placement is accepted as a methodology in sea turtles [@innis2023].

    -   Identify concerns/hindrances of acoustic telemetry deployment on turtles (permitting, attachment options, turtle access, etc.).

    -   Work with other user groups to understand and improve receiver deployment (designs) and share data.

**Characterize oceanographic and habitat drivers of sea turtle distribution, abundance, and behavior:**

-   Coordinate with federal agencies (U.S. Navy, NOAA Fisheries) to help update and refine sea turtle abundance/density estimates and surface density models.

    -   Integrate the latest observational and environmental data every 2-3 years.

    -   Integrate data from multiple additional methods (strandings, digital aerial surveys, tagging, fishery and dredge take data) and covariates (oceanographic and prey distribution).
        Apply results to inform research designs, determine baseline abundance/distribution estimates, best practices, etc.

    -   Consider how to structure future model "eras" to reflect offshore wind pre-construction and construction/operation.

    -   Use results to understand broad scale drivers of sea turtle distribution and movement and to assess/detect change, displacement, and/or potential impacts.

    -   Create a modeling framework that is scalable to individual projects and the whole region such that individual project-specific outputs could be pooled into regional-scale versions of the model.

-   Compile and analyze historic satellite and acoustic sea turtle tag data in the study area.
    Analysis should focus on seasonal migratory timing, (seasonal) offshore distribution, dive behavior in a variety of seasons/subregions/depths, and environmental variables correlated with animal movement.
    Develop standardized data products for sea turtles from movement data that can be replicated across sites and scales.
    Apply results to inform research designs, determine baseline parameters, best practices, etc.

**Determine whether offshore wind is impacting sea turtles negatively or positively:**

-   Apply methods similar to those used for impact assessment of the Deep Water Horizon Oil Spill on sea turtles [@love2017] to quantify potential impacts of offshore wind on sea turtles and to compare those impacts with other known cumulative stressors.

-   Conduct a power analysis and/or assess the ability of aerial survey data to detect changes in turtle abundance/density in the vicinity of offshore development.

    -   Describe current limitations of visual aerial and digital surveys (e.g., depth of detection by size, sea state, and other environmental parameters; small animals (\>40cm carapace length)) and identify existing or develop new turtle-specific and multispecies best practices and needed technology to improve detection.

    -   (*Cross taxa*) Work with other taxa groups to develop plans on how to consistently conduct aerial surveys near turbines in a manner comparable to previous survey data.

-   (*Cross taxa*) Develop protocols for consistent phase-gradient experimental designs assessing sea turtle density, distribution, and behavior to be applied at individual project areas during construction and operation to determine if activities displace or attract sea turtles, such that data and results can be pooled into larger regional scale studies.

-   Develop an understanding of sea turtle hearing and reaction to offshore wind noises by species and life stage including behavioral and physiological impact of noise created by offshore wind construction and operation.

-   (*Cross taxa*) Develop or update existing vessel and sea turtle/marine mammal co-occurrence models with vessels of various type and size associated with turbine construction and operation with the ultimate goal of modeling/estimating mortality attributable to vessel strikes associated with offshore wind.

-   (*Cross taxa*) Some effects of offshore wind development on sea turtles, both individually and at population levels, are likely to be indirect, cumulative, synergistic, and difficult to assign to a single cause.
    Separating the effects on sea turtles of climate change from any potential effects of offshore wind will be a challenge.
    RWSC should support efforts to address this challenge for a variety of species.
