blank_issues_enabled: false
contact_links:
  - name: Report a Typo
    url: https://github.com/RWSCollab/science-plan/blob/main/.github/ISSUE_TEMPLATE/issue_form_typo.yml
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.