name: Update a Missing Link or Citation
description: Suggest new/updated URLs or references.
title: "[Update or add citation]: "
labels: ["reference"]
projects: ["RWSCollab/science-plan"]
assignees:
  - eshumchenia
body:
  - type: markdown
    attributes:
      value: |
        Thanks for keeping the citations in the Science Plan current!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: location
    attributes:
      label: In what section is the outdated or missing citation?
      description: Scroll up from the typo to the first section heading. Hover over the heading to reveal the 🔗. Copy and paste the URL below.
      placeholder: Paste section URL here.
      value: "Update or add a citation in this section!"
    validations:
      required: true
  - type: textarea
    id: update
    attributes:
      label: Provide us with the new or updated citation.
      description: Copy and paste the new or updated URL, reference, and/or any description that you think will be helpful.
      placeholder: Paste the new info here.
      value: "Update or add this citation!"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
