name: Research Recommendation
description: Suggest a revised or new research recommendation
title: "[Research Recommendation]: "
labels: ["research"]
projects: ["RWSCollab/science-plan"]
assignees:
  - eshumchenia
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to recommend improvements to the Science Plan!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: location
    attributes:
      label: Where should the new or updated recommendation be added?
      description: Scroll up from the typo to the first section heading. Hover
      over the heading to reveal the 🔗. Copy and paste the URL below.
      placeholder: Paste section URL here.
      value: "This section needs a new or updated recommendation!"
    validations:
      required: true
  - type: textarea
    id: update
    attributes:
      label: Provide us with the recommendation that you'd like to see.
      description: Suggest some wording for an updated or new recommendation,
      reasons why it should be included, and any additional information that you
      think will be helpful.
      placeholder: Write your suggestion here.
      value: "Consider this recommendation!"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
